### ISSUE TITLE
[ NEW PAGE ] Transpiler plugins

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#102]
## What the new page should cover:

- [ ] Using other open source plugins (or create your own, link to custom pass manager section)
- [ ] turn your passmanager into a plugin

## SME collaborators (involve for planning and review):
@mtreinish @haimeng-zhang

## Existing resources to build upon
- https://medium.com/qiskit/release-news-qiskit-v0-39-0-is-here-389a63ab6857
- https://qiskit.org/documentation/apidoc/transpiler_plugins.html
- https://qiskit.org/documentation/apidoc/transpiler_synthesis_plugins.html
- https://www.youtube.com/watch?v=k-tf-aFV0BQ&t=1s

**Comment by abbycross** [comment]
See #391

**Comment by kevinsung** [comment]
blocked by https://github.com/Qiskit/qiskit/issues/11356

**Comment by kevinsung** [comment]
blocked by https://github.com/Qiskit/qiskit/pull/11549
