### ISSUE TITLE
Update verify Aer pages to use aer primitives v2

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#1025]
Once aer is updated to use v2 primitives we should update these pages to use them: 

- https://docs.quantum.ibm.com/verify/simulate-with-qiskit-aer
- https://docs.quantum.ibm.com/verify/stabilizer-circuit-simulation

**Comment by kevinsung** [comment]
We could also consider rewriting this page to use "local testing mode" with an Aer backend. See https://github.com/Qiskit/qiskit-aer/issues/2078#issuecomment-2012736552.

**Comment by kevinsung** [comment]
Updating https://docs.quantum.ibm.com/verify/stabilizer-circuit-simulation is blocked by https://github.com/Qiskit/qiskit-aer/issues/2140.

**Comment by kevinsung** [comment]
Updating https://docs.quantum.ibm.com/verify/stabilizer-circuit-simulation is blocked by https://github.com/Qiskit/qiskit-aer/issues/2164

**Comment by kevinsung** [comment]
Closed by #1490 and #1496
