### ISSUE TITLE
[ NEW PAGE ] Representing Quantum Computers

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#103]
## What the new page should cover:

- [x] coupling map
- [ ] error map
- [ ] link to page explaining stages in transpile
- [x] build your own target

## SME collaborators (involve for planning and review):
@mtreinish @haimeng-zhang

## Existing resources to build upon
https://qiskit.org/documentation/apidoc/transpiler.html#representing-quantum-computers

**Comment by beckykd** [comment]
According to @nbronn , Error map is not intended for users, so we're not including that.
