### ISSUE TITLE
[NEW PAGE] Local Testing with Fake Backends using Qiskit Runtime

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#1031]
The Qiskit fake backends now live in Qiskit Runtime and you can use them with Runtime's "local testing mode". I believe the cloud simulator migration guide will include some info about this but it would be good to have a permanent page in the verify section as well

**Comment by beckykd** [comment]
> Do we need a whole new page for this? I'd just point people to the local testing mode section on Get started with Qiskit Runtime

I can just move that section to a new page for a clear split between "run" and "verify".

**Comment by beckykd** [comment]
Will be added with #1023

**Comment by javabster** [comment]
closed by #1023
