### ISSUE TITLE
[REFACTOR] verify intro page to include runtime "local testing mode"

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#1032]
Runtime has a new "local testing mode" that leverages Fake backends, meaning that the main ways people can do local simulation with ibm quantum tools are as follows:

- Qiskit built-in simulation with Qiskit SDK Primitives (limited statevector simulation)
- Qiskit Aer primitives (+ noise models, but i cant remember if they can be used with primitives)
- Qiskit Runtime local testing mode (including fake backends with noise)

It would be good to update the verify intro to summarise these options for users. I think @jyu00 may have a diagram we can use

**Comment by beckykd** [comment]
This update will be integrated with https://github.com/Qiskit/documentation/pull/1023

**Comment by jyu00** [comment]
> Qiskit built-in simulation with Qiskit SDK Primitives (limited statevector simulation)
Qiskit Aer primitives (+ noise models, but i cant remember if they can be used with primitives)
Qiskit Runtime local testing mode (including fake backends with noise)

Yes these are the 3 choices IBM Quantum supports.
1. The first one has native primitives support - `StatevectorSampler` and `StatevectorEstimator`. 
2. Qiskit Aer currently only has native support for V1 primitives - i.e. you cannot do `from qiskit_aer.primitives import EstimatorV2`. But you can pass an Aer backend to the 3rd choice.
3. Qiskit Runtime local testing mode has V2 primitives support for both fake backends and Aer backends.

**Comment by javabster** [comment]
closed by #1023
