### ISSUE TITLE
Usage of MatrixOp.to_pauli_op() and quantum instance

### ISSUE THREAD

**Issue by manu123416** [Qiskit/documentation#1037]
### Select all that apply

- [ ] typo
- [ ] code bug
- [ ] out-of-date content
- [ ] broken link
- [ ] other

### Describe the fix.

Hi everyone, 
I am not able to understand the usage of MatrixOp. I am not sure what exactly is the function of this API. There is no well defined  documentation which can explain what is its use and refer me to some paper.
```
import numpy as np
from qiskit.opflow import MatrixOp
from qiskit.circuit.library import EfficientSU2
from qiskit.algorithms.optimizers import COBYLA
from qiskit.utils import QuantumInstance 
from qiskit import IBMQ, transpile
from qiskit import Aer

from qiskit.algorithms import VQE
    
    # This Hamiltonian is not unitary.It is generated from matrix A and B (AX =B)
    Hamiltonian =  np.array([[ 4.07981221, -3.6713615,   1.3943662,  -1.05164319], 
     [-3.6713615,   5.88262911, -4.14084507,  1.37558685],
     [ 1.3943662,  -4.14084507,  5.83098592, -3.54929577],
     [-1.05164319,  1.37558685, -3.54929577,  3.79812207]])
    

    H_op = MatrixOp(Hamiltonian).to_pauli_op()
    print(H_op)
    print(type(H_op)) 

    ansatz = EfficientSU2(num_qubits=2,        
                                entanglement= 'linear',  
                                reps= 5,          
                                skip_final_rotation_layer= True).decompose() 
    # backend
    simulator_used= "statevector_simulator"
    backend = Aer.get_backend(simulator_used)
    ansatz_opt = transpile(circuits=ansatz, 
                                backend= backend, 
                                optimization_level =1)     
    
    optimizer = COBYLA(maxiter= 15000)
    # What is the usage of QuantumInstance. I have never seen its usage in basic quantum circuits?
    quantum_instance = QuantumInstance(backend= backend, 
                                                    shots= 2000,     
                                                    seed_simulator= 28,    
                                                    seed_transpiler= 28, 
                                                    basis_gates= None, 
                                                    optimization_level=1)
    
    initial_point_values = 2*np.pi*np.random.rand(ansatz_opt.num_parameters)
    vqe = VQE(ansatz=ansatz_opt, 
                    optimizer= optimizer,
                    quantum_instance=quantum_instance,
                    initial_point=initial_point_values
                    )
    
    result = vqe.compute_minimum_eigenvalue(H_op)
```

I am using the `qiskit==0.46.0`
Also, it would be great if you can explain the `QuantumInstance` API? Why it needs shots why we are using "statevector_similator"?

**Comment by javabster** [comment]
hi @manu123416 are you asking for new documentation on MatrixOp? Or is there specific documentation pages that you think need updating?

**Comment by manu123416** [comment]
Thank you for the response. I tried but I am not able to understand how this MatrixOp works? Which research paper is used for creating this API?
________________________________

**Comment by javabster** [comment]
hi @manu123416 taking another look at your code it looks like you're using `MatrixOp` from `qiskit.opflow` which was deprecated in qiskit v0.44. You can have a look at the migration guide here for more info: https://docs.quantum.ibm.com/api/migration-guides/qiskit-opflow-module

**Comment by manu123416** [comment]
Hi @javabster.  My problem is still not resolved. I really could not find what API should I put in place of `H_op = MatrixOp(Hamiltonian).to_pauli_op()`
It would be really great if you can provide me the API name I should use to replace `MatrixOp`.
