### ISSUE TITLE
Session best practices 

### ISSUE THREAD

**Issue by jyu00** [Qiskit/documentation#1041]
### Describe the new content you are requesting.

With the upcoming changes to execution modes, we should provide some best practices, especially for Session, so the modes can be used efficiently. 

Key points:
- Always close your session!
- There is a fixed overhead associating with running each job. In general, if your each of your jobs consumes less than a minute of QPU time, consider combining them into a larger job (this applies to all execution modes). QPU time here refers to time spent by the QPU complex to process your job. You can find this information here. 
- If your job already consumes more than 1 minute of QPU time, or if combining jobs is not practical, you can still run multiple jobs in parallel. Every job goes through both classical and quantum processing. While a QPU can process only 1 job at a time, classical processing can be parallelize. You can take advantage of this parallelism by submitting multiple jobs in Batch or Session execution modes. The degree of parallelism is set by the server and is currently 5, meaning up to 5 jobs can run in parallel. 
    - Example/link showing parallel jobs for both Batch and Session
- What we described above is the general guideline, and we encourage you to tune your workload to find the optimal ratio, especially when using Session. For example, you may find running smaller jobs in parallel becomes more cost effective because of reduced wall clock time. 

### If this new content request is accepted, do you want to write the content?

I can help the team by providing enough information to write the material

**Comment by beckykd** [comment]
Closed in https://github.com/Qiskit/documentation/pull/783
