### ISSUE TITLE
Backend instantiation inaccurate for primitive examples - advance session options

### ISSUE THREAD

**Issue by david-alber** [Qiskit/documentation#1063]
### URL to the relevant documentation

https://github.com/Qiskit/documentation/blob/main/docs/run/primitives-examples.mdx

### Select all that apply

- [ ] typo
- [X] code bug
- [ ] out-of-date content
- [ ] broken link
- [ ] other

### Describe the fix.

The `backend` should be instantiated before using it in the `generate_preset_pass_manager`.
This can be achieved by moving line 625 to 618.

AS IS:
```python
pm = generate_preset_pass_manager(backend=backend, optimization_level=1)
isa_circuit = pm.run(circuit)
another_isa_circuit = pm.run(another_circuit)
 
service = QiskitRuntimeService()
 
backend = service.least_busy(operational=True, simulator=False, min_num_qubits=127)
```

TO BE: 
```python
backend = service.least_busy(operational=True, simulator=False, min_num_qubits=127)
pm = generate_preset_pass_manager(backend=backend, optimization_level=1)
isa_circuit = pm.run(circuit)
another_isa_circuit = pm.run(another_circuit)
 
service = QiskitRuntimeService()
```

**Comment by Eric-Arellano** [comment]
Thanks @david-alber for reporting! A PR would definitely be welcomed :) You'll also need to move up the `service` definition before `backend`. See this for a valid example

https://github.com/Qiskit/documentation/blob/9ff00250401453df6a164185e9038f57f6579d42/docs/run/primitives-examples.mdx#L571-L579

**Comment by david-alber** [comment]
@Eric-Arellano jup thanks for the hint.
Can you please assign me to this issue?
