### ISSUE TITLE
Primitive Unified "Bloc" not "Block

### ISSUE THREAD

**Issue by kevinsung** [Qiskit/documentation#1066]
### URL to the relevant documentation

https://docs.quantum.ibm.com/api/qiskit/primitives#overview-of-samplerv2

### Select all that apply

- [x] typo
- [ ] code bug
- [ ] out-of-date content
- [ ] broken link
- [ ] other

### Describe the fix.

We should consistently use the [correct](https://github.com/Qiskit/qiskit/blob/dd2570bc0e71a830d6078edb4854f95705fce932/qiskit/primitives/__init__.py#L41) name.

**Comment by abbycross** [comment]
This is an API doc issue, so I opened an [issue](https://github.com/Qiskit/qiskit/issues/12130) and a [PR](https://github.com/Qiskit/qiskit/pull/12131) to fix it in Qiskit/qiskit.

**Comment by abbycross** [comment]
Fixed by https://github.com/Qiskit/qiskit/pull/12131
