### ISSUE TITLE
Primitives V2 MVP2 

### ISSUE THREAD

**Issue by jyu00** [Qiskit/documentation#1083]
### Describe the new content you are requesting.

Primitives V2 MVP2 is scheduled to release on April 1. This release will including the following enhancements:

- Support dynamic circuits (without DD) in SamplerV2
- Support measurement level 1 in SamplerV2
- Support twirling in SamplerV2
- Deprecation of primitives V1
- Deprecation of backend.run

We'll need corresponding docs
- 

 [ ] Migration guide to go from backend.run to SamplerV2. This will include dynamic circuits & measurement level 1 that are currently supported by backend.run
 [ ] Update existing V1->V2 migration guide to include twirling in SamplerV2
 [ ] Some examples of using dynamic circuits / meas level 1 in https://docs.quantum.ibm.com/run/primitives-examples
 [ ] Probably need to update / clean up the whole "Migrate to Qiskit Runtime" section

### If this new content request is accepted, do you want to write the content?

I can help the team by providing enough information to write the material

**Comment by beckykd** [comment]
I think the name of the current migration guide file will be confusing (qiskit-runtime-from-provider).  So I could rename it to something like qiskit-runtime-from-backend-run.  Thoughts, @jyu00 @ElePT ?
