### ISSUE TITLE
Bad attribute in `qiskit.algorithms.eigensolvers.VQD`

### ISSUE THREAD

**Issue by arnaucasau** [Qiskit/documentation#1120]
In the `qiskit.algorithms.eigensolvers.VQD` page for historical versions of qiskit, we have a weird attribute with a text description as a name:

![Captura desde 2024-04-03 15-21-14](https://github.com/Qiskit/documentation/assets/47946624/08b8d6fc-ad2a-4d9e-91b0-e352dbce1e29)

This attribute has an entry in the ToC as well:

![Captura desde 2024-04-03 15-21-32](https://github.com/Qiskit/documentation/assets/47946624/35f637f8-2157-4707-aa27-1bb4bb3dfdbc)

Link to the page https://docs.quantum.ibm.com/api/qiskit/0.46/qiskit.algorithms.eigensolvers.VQD#one-for-every-k-th-eigenvalue-can-either-be-a-qiskit-optimizer-or-a-callable

**Comment by arnaucasau** [comment]
**Update:** 

Versions of Qiskit affected: 0.43, 0.44, 0.45, and 0.46. 

The issue is with the original [RST](https://github.com/Qiskit/qiskit/blob/5150003fd75ddcf61536d31321276b48b0f116fe/qiskit/algorithms/eigensolvers/vqd.py#L97) and not with the API generation script. In the following screenshot, we can see the HTML of that page downloaded from the artifact stored in Box:

![Captura desde 2024-04-08 18-56-13](https://github.com/Qiskit/documentation/assets/47946624/51d1b6f2-8253-402e-864c-758efbebf7c9)

**Comment by Eric-Arellano** [comment]
@arnaucasau we should fix the bad HTML and re-upload to Box.
