### ISSUE TITLE
Add options table for V2 primitives 

### ISSUE THREAD

**Issue by jyu00** [Qiskit/documentation#1124]
### URL, if applicable

https://docs.quantum.ibm.com/run/advanced-runtime-options

### Describe the new content you are requesting.

Feedback from user mentioned that it was difficult to find the primitive options, since there are many options classes buried i the API reference. It'd be  helpful to have a table that mentions the different categories and links to the respective class. For example:

| Category | Description | Example |
| ----- | ----- | ---- |
| [resilience](https://docs.quantum.ibm.com/api/qiskit-ibm-runtime/qiskit_ibm_runtime.options.ResilienceOptionsV2) | Advanced options for configuring error mitigation. Estimator only. | estimator.options.resilience.measure_mitigation = True |
| [dynamical_decoupling](https://docs.quantum.ibm.com/api/qiskit-ibm-runtime/qiskit_ibm_runtime.options.DynamicalDecouplingOptions) | Options for dynamical decoupling. | estimator.options.dynamical_decoupling.enable = True |

### If this new content request is accepted, do you want to write the content?

I can help the team by providing enough information to write the material

**Comment by abbycross** [comment]
@lenaper has created a table based on questions coming in to the support team. Tagging her here to contribute her ideas

**Comment by abbycross** [comment]
Here is the draft @LenaPer shared:


1. Noiseless simulation = exact simulation without sampling noise
https://qiskit.github.io/qiskit-aer/stubs/qiskit_aer.primitives.Sampler.html#qiskit_aer.primitives.Sampler using sampler.run(…, shots=None) (old samplerV1 interface)
2. Shotnoise simulation = shot-based ideal simulation, only noise is the sampling
StatevectorSampler https://docs.quantum.ibm.com/api/qiskit/qiskit.primitives.StatevectorSampler
https://qiskit.github.io/qiskit-aer/stubs/qiskit_aer.primitives.Sampler.html#qiskit_aer.primitives.Sampler (old samplerV1 interface)
https://docs.quantum.ibm.com/api/qiskit-ibm-runtime/qiskit_ibm_runtime.SamplerV2 + ideal aer simulator https://docs.quantum.ibm.com/api/migration-guides/local-simulators#aersimulator
3. Simulated device noise
https://qiskit.github.io/qiskit-aer/stubs/qiskit_aer.primitives.Sampler.html#qiskit_aer.primitives.Sampler (old samplerV1 interface)
https://docs.quantum.ibm.com/api/qiskit-ibm-runtime/qiskit_ibm_runtime.SamplerV2 + fake backend or aer simulator with noise
4. Running on actual hardware
https://docs.quantum.ibm.com/api/qiskit-ibm-runtime/qiskit_ibm_runtime.SamplerV2 + real backend from QiskitRuntimeService

Not in this list :
- Sampler v1 of Qiskit.primitives and qiskit-ibm-runtime : bound to be deprecated
- BaseSampler V1/V2 : abstract base class for each version that define a common interface for implementing primitives
- BackendSampler https://docs.quantum.ibm.com/api/qiskit/qiskit.primitives.BackendSampler ==> not that useful when running within the ibm quantum ecosystem

Questions :
- Are the aer primitives going to be updated to v2? https://github.com/Qiskit/qiskit-aer/issues/2078
- For case 2 : which one for what?
- For case 3 : which one for what?
- For case 2 and 3 : several ways to do the same thing, is there a plan to have only one in the future?

**Comment by jyu00** [comment]
I don't quite understand what the different simulation/real environments have to do with the options Qiskit Runtime supports.

**Comment by beckykd** [comment]
> Here is the draft @LenaPer shared:
> 
> 1. Noiseless simulation = exact simulation without sampling noise
>    https://qiskit.github.io/qiskit-aer/stubs/qiskit_aer.primitives.Sampler.html#qiskit_aer.primitives.Sampler using sampler.run(…, shots=None) (old samplerV1 interface)
> 2. Shotnoise simulation = shot-based ideal simulation, only noise is the sampling
>    StatevectorSampler https://docs.quantum.ibm.com/api/qiskit/qiskit.primitives.StatevectorSampler
>    https://qiskit.github.io/qiskit-aer/stubs/qiskit_aer.primitives.Sampler.html#qiskit_aer.primitives.Sampler (old samplerV1 interface)
>    https://docs.quantum.ibm.com/api/qiskit-ibm-runtime/qiskit_ibm_runtime.SamplerV2 + ideal aer simulator https://docs.quantum.ibm.com/api/migration-guides/local-simulators#aersimulator
> 3. Simulated device noise
>    https://qiskit.github.io/qiskit-aer/stubs/qiskit_aer.primitives.Sampler.html#qiskit_aer.primitives.Sampler (old samplerV1 interface)
>    https://docs.quantum.ibm.com/api/qiskit-ibm-runtime/qiskit_ibm_runtime.SamplerV2 + fake backend or aer simulator with noise
> 4. Running on actual hardware
>    https://docs.quantum.ibm.com/api/qiskit-ibm-runtime/qiskit_ibm_runtime.SamplerV2 + real backend from QiskitRuntimeService
> 
> Not in this list :
> 
> * Sampler v1 of Qiskit.primitives and qiskit-ibm-runtime : bound to be deprecated
> * BaseSampler V1/V2 : abstract base class for each version that define a common interface for implementing primitives
> * BackendSampler https://docs.quantum.ibm.com/api/qiskit/qiskit.primitives.BackendSampler ==> not that useful when running within the ibm quantum ecosystem
> 
> Questions :
> 
> * Are the aer primitives going to be updated to v2? [Support for PrimitivesV2 qiskit-aer#2078](https://github.com/Qiskit/qiskit-aer/issues/2078)
> * For case 2 : which one for what?
> * For case 3 : which one for what?
> * For case 2 and 3 : several ways to do the same thing, is there a plan to have only one in the future?


> Here is the draft @LenaPer shared:
> 
> 1. Noiseless simulation = exact simulation without sampling noise
>    https://qiskit.github.io/qiskit-aer/stubs/qiskit_aer.primitives.Sampler.html#qiskit_aer.primitives.Sampler using sampler.run(…, shots=None) (old samplerV1 interface)
> 2. Shotnoise simulation = shot-based ideal simulation, only noise is the sampling
>    StatevectorSampler https://docs.quantum.ibm.com/api/qiskit/qiskit.primitives.StatevectorSampler
>    https://qiskit.github.io/qiskit-aer/stubs/qiskit_aer.primitives.Sampler.html#qiskit_aer.primitives.Sampler (old samplerV1 interface)
>    https://docs.quantum.ibm.com/api/qiskit-ibm-runtime/qiskit_ibm_runtime.SamplerV2 + ideal aer simulator https://docs.quantum.ibm.com/api/migration-guides/local-simulators#aersimulator
> 3. Simulated device noise
>    https://qiskit.github.io/qiskit-aer/stubs/qiskit_aer.primitives.Sampler.html#qiskit_aer.primitives.Sampler (old samplerV1 interface)
>    https://docs.quantum.ibm.com/api/qiskit-ibm-runtime/qiskit_ibm_runtime.SamplerV2 + fake backend or aer simulator with noise
> 4. Running on actual hardware
>    https://docs.quantum.ibm.com/api/qiskit-ibm-runtime/qiskit_ibm_runtime.SamplerV2 + real backend from QiskitRuntimeService
> 
> Not in this list :
> 
> * Sampler v1 of Qiskit.primitives and qiskit-ibm-runtime : bound to be deprecated
> * BaseSampler V1/V2 : abstract base class for each version that define a common interface for implementing primitives
> * BackendSampler https://docs.quantum.ibm.com/api/qiskit/qiskit.primitives.BackendSampler ==> not that useful when running within the ibm quantum ecosystem
> 
> Questions :
> 
> * Are the aer primitives going to be updated to v2? [Support for PrimitivesV2 qiskit-aer#2078](https://github.com/Qiskit/qiskit-aer/issues/2078)
> * For case 2 : which one for what?
> * For case 3 : which one for what?
> * For case 2 and 3 : several ways to do the same thing, is there a plan to have only one in the future?

Moved these to issue #1186
