### ISSUE TITLE
Figure out the design for the link's icon for classes, functions, and attributes

### ISSUE THREAD

**Issue by arnaucasau** [Qiskit/documentation#1126]
The permalink icon we use for the headings needs a new design, given that we will remove all `<h3>` for methods and attributes. The current icon is displayed on the left side of the titles, and if we move it to the signatures directly, it will have an overlapping problem with the new left-colored bars.

This is an example of the icon overlapping with the bars in a method inside an inlined class:

<img width="907" alt="Screenshot 2024-04-04 at 17 45 45" src="https://github.com/Qiskit/documentation/assets/47946624/c94a4df4-bfd7-4b93-89bb-cdd94cc2105e">

This is an example of the icon overlapping with the bars in a method in a regular class:

<img width="699" alt="Screenshot 2024-04-04 at 17 47 09" src="https://github.com/Qiskit/documentation/assets/47946624/62dd84ab-5a75-462c-8f9a-286c0b7e4a95">

This is a method on a dedicated page:

<img width="949" alt="Screenshot 2024-04-04 at 17 49 43" src="https://github.com/Qiskit/documentation/assets/47946624/1f0bcd25-a616-4e96-a28b-1b07620e654e">

**Comment by gracelindsell** [comment]
Designs have been [updated](https://www.figma.com/file/sNXucK1uMaZ8XXyLTZrdrs/IBM-Quantum-Documentation?type=design&node-id=5646%3A42031&mode=design&t=TRLRcdtsUN4IuYuQ-1) showing the movement of the link to the right

**Comment by Eric-Arellano** [comment]
The change is in review for headers, which will use 8px padding-left. For code objects, it should be 4px padding-left because there already is padding-right with the code. 
<img width="696" alt="Screenshot 2024-04-16 at 3 55 57 PM" src="https://github.com/Qiskit/documentation/assets/14852634/14b27bbb-7885-4da4-8436-45c641bbe7fb">
