### ISSUE TITLE
Mention the need for classical register name in SamplerV2

### ISSUE THREAD

**Issue by jyu00** [Qiskit/documentation#1130]
### URL, if applicable

- [x] https://docs.quantum.ibm.com/api/migration-guides/v2-primitives#steps-to-migrate-to-sampler-v2

- [x] https://docs.quantum.ibm.com/run/primitives-get-started#4-invoke-the-sampler-and-get-results

### Describe the new content you are requesting.

The output of SamplerV2 is grouped by the names of the classical registers in the input circuit. The default is `meas` if `measure_all()` is used, but it's `c` if `measure()` is used. This has caused some confusion with the users. #1088 has this note

<img width="769" alt="image" src="https://github.com/Qiskit/documentation/assets/28284230/e8a9cf25-7e1a-42e8-838a-80fbd57c993b">

We should add this so the general SamplerV2 docs as well. 

### If this new content request is accepted, do you want to write the content?

I can help the team by providing enough information to write the material

**Comment by beckykd** [comment]
These topics all have the note added: 

- migration-guides/qiskit-runtime-examples
- migration-guides/qiskit-runtime-use-case
- migration-guides/v2-primitives (2 locations)
- run/primitives-examples
- run/primitives

These changes will all be part of https://github.com/Qiskit/documentation/pull/1088 and will go live on Monday
