### ISSUE TITLE
Generally improve "Hello world" page

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/documentation#1132]
### URL to the relevant documentation

https://docs.quantum.ibm.com/start/hello-world

### Select all that apply

- [ ] typo
- [ ] code bug
- [ ] out-of-date content
- [ ] broken link
- [X] other

### Describe the fix.

The page feels really convoluted for what is supposed to be the simplest possible Qiskit program. I imagine our [time to hello world](https://en.wikipedia.org/wiki/%22Hello,_World!%22_program#Time_to_Hello_World) is pretty poor.

Things we could improve:
- [ ] Remove the long admonition on bit-ordering
- [ ] Remove the long admonition on ISA circuits (this especially feels like it's for existing users)
- [ ] Remove any jargon not needed for the example (ISA, PUB)
- [ ] Maybe simplify the example code

**Comment by Eric-Arellano** [comment]
> Remove any jargon not needed for the example (ISA, PUB)

We should probably use the Sampler primitive so we don't need to explain PUB and use a list of circuits instead.

**Comment by frankharkins** [comment]
Sadly that doesn't seem like it'll fly (see https://github.com/Qiskit/documentation/issues/699#issuecomment-1997631798). It might still be possible to avoid focussing on "PUB" by just saying "circuit + observables".

**Comment by abbycross** [comment]
Will/should/could any of #1158 satisfy the fixes requested here?

**Comment by beckykd** [comment]
> Will/should/could any of #1158 satisfy the fixes requested here?

Seems sensible to pause this work until @kaelynj finishes #1158

**Comment by beckykd** [comment]
> > Remove any jargon not needed for the example (ISA, PUB)
> 
> We should probably use the Sampler primitive so we don't need to explain PUB and use a list of circuits instead.

We could just say something like "Ensure the circuits will run on the backend" and call them "ISA"

**Comment by frankharkins** [comment]
Yep will close as I think Kaelyn's PR addresses most of these issues.
