### ISSUE TITLE
Update blog link on Qiskit 1.0 migration guide

### ISSUE THREAD

**Issue by jdc2003** [Qiskit/documentation#1148]
### URL to the relevant documentation

The IBM blog link on [Qiskit 1.0 migration guide](https://docs.quantum.ibm.com/api/migration-guides/qiskit-1.0) points to the Dec 2023 [Qiskit 1.0 Upcoming Release](https://www.ibm.com/quantum/blog/qiskit-1-launch) post and should have added or be updated to more recent Mar 2024 [Qiskit 1.0 Release Summary](https://www.ibm.com/quantum/blog/qiskit-1-0-release-summary) 

### Select all that apply

- [ ] typo
- [ ] code bug
- [X] out-of-date content
- [ ] broken link
- [ ] other

### Describe the fix.

Update or add blog link to recent Mar 2024 [Qiskit 1.0 Release Summary](https://www.ibm.com/quantum/blog/qiskit-1-0-release-summary)

**Comment by abbycross** [comment]
Thank you @jdc2003 for the report! Updating the link in #1161.
