### ISSUE TITLE
Add warning for open plan sessions users

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#1156]
Add a warning to sessions docs about open plan, something like this (but maybe more detail?)

"Session execution mode is not supported in the open plan. Jobs will run in job mode instead."

cc @jyu00 @AndreiConstantin00

**Comment by Eric-Arellano** [comment]
>  Jobs will run in job mode instead.

Should that be "single job mode instead"? "single" is missing I think.

**Comment by beckykd** [comment]
FYI, this does not apply to batch mode.
