### ISSUE TITLE
[ REMOVE ] Run on quantum backends

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#116]
Much of the info on this page is superseded by the primitives section that is due to be moved to the run section (see https://github.com/Qiskit/documentation/issues/39)

In addition, certain sections of this page will be added to a new "get backend information" page, (see https://github.com/Qiskit/documentation/issues/112)

As a result, once #39 and #112 are complete, this page can be removed

**Comment by abbycross** [comment]
This page will be removed in https://github.com/Qiskit/documentation/pull/182

**Comment by Eric-Arellano** [comment]
Completed in https://github.com/Qiskit/documentation/pull/182
