### ISSUE TITLE
Fix bad docs for `BaseSchema.mdx` and `VQD.mdx`

### ISSUE THREAD

**Issue by arnaucasau** [Qiskit/documentation#1162]
There are two files with issues in the documentation that should be fixed by modifying the HTML in the [Box](https://ibm.ent.box.com/folder/246867452622) folder.

The first issue is in the `qiskit.algorithms.eigensolvers.VQD.mdx` for qiskit 0.46, 0.45, 0.44, and 0.43. In the list of parameters, the parameter optimizer has the description split into two bullet points. This issue was fixed in the `Qiskit/qiskit` [repo](https://github.com/Qiskit/qiskit/pull/12168) for 0.46, and in the `qiskit-algorithms` [repo](https://github.com/qiskit-community/qiskit-algorithms/pull/168), so the only thing left is to modify versions 0.45, 0.44, and 0.43 HTML + regenerate the docs here.

![Captura desde 2024-04-11 18-58-53](https://github.com/Qiskit/documentation/assets/47946624/e3b1e143-be55-4896-9eed-1dc9a5ca8eda)

The second issue can be found in the `docs/api/qiskit/0.19/qiskit.validation.BaseSchema.mdx` file, only affecting qiskit 0.19. The file has a strange [attribute](https://github.com/arnaucasau/documentation/blob/78dcb36d8f31b2cf0afcfb8f7b199f9af7b40321/docs/api/qiskit/0.19/qiskit.validation.BaseSchema.mdx?plain=1#L29) that needs investigation to see why it has that name.

**Comment by Eric-Arellano** [comment]
Closing as low priority. We're focused more on 0.46+
