### ISSUE TITLE
Some improvements to install

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#1163]
Using this issue to collect ideas for improving the install page:

- [x] embed the latest CWQ install video into the page (https://www.youtube.com/watch?v=dZWz4Gs_BuI)
- [x] In step 1 - mention other python environments, like anaconda and miniconda
- [x] In step 2 - mention that you only need to install pip if you dont use a python environment, otherwise its already installed in the env

**Comment by iheuze** [comment]
I think a newcomer could easily be overwhelmed by all the text. I would strip back the steps to the absolute basics and then any extras can be included after. For example the note in step 3. I would either have that after the steps or as something you have to click to open. 

I also don't think it is very clear where you put "pip install qiskit." Could add a bit about command prompts if you are using something like Spyder or else for Jupyter / Google Colab, you just run it like you would any other piece of code. 

What do you think about including some screengrabs? I think it could make some parts easier to follow.
