### ISSUE TITLE
review/refactor Krylov tutorial (HIGH PRIORITY)

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#1166]
This was originally [a summit demo](https://learning.quantum.ibm.com/tutorial/krylov-subspace-expansion) that has been converted into a 10q tutorial by Nate's team and is almost ready to deploy to learning as an open tutorial. Please work with Mirko (+ pedro?) on this issue

- [ ] move [source file](https://github.com/IBM-Quantum-Technical-Enablement/quantum-enablement/blob/main/docs/notebooks/krylov.ipynb) into this repo (retain author/commit history if possible)
- [ ] explain at a high level how to take this tutorial further and scale
- [ ] review and refactor 
- [ ] get a final product review and deploy to learning, update access controls to "open"

**Comment by abbycross** [comment]
@frankharkins can you assist with moving this tutorial to this repo, preserving the author/commit history?
