### ISSUE TITLE
Test the safe parts of notebooks that run on hardware in every CI run

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/documentation#1173]
We cannot easily test notebooks that run on hardware in CI for every PR because a) there is often a queue and b) it costs actual resources. So, we currently skip those notebooks in PR runs:

https://github.com/Qiskit/documentation/blob/8642507fc2c5fc4982e79f16f414ba66fc629708/scripts/nb-tester/test-notebook.py#L33-L43

We then run those notebooks every two weeks in a cron job with GH Actions.

However, we can actually run part of the notebooks safely! We can run every code cell up until the point when we call `Estimator.run()` and `Sampler.run()`, or do some other slow thing with Qiskit Runtime. All the code up to that point is safe to run.

We can add a Jupyter notebook tag like `submits-job` to the code cells that use hardware. Then teach `nb-tester` to only run up to that code block, but stop there. We wouldn't run any subsequent code blocks since they may depend on the tagged code block.

**Comment by Eric-Arellano** [comment]
@frankharkins think we should close this as not worth the complexity? In hello world, we would only be able to test about 25% of the notebook with this strategy, which isn't that big of a win. 

Removing tutorials changed the value, imo. This is what would be impacted:

https://github.com/Qiskit/documentation/blob/632cb2cc4c83432212d30f4e2b8262cba2831d3a/scripts/config/notebook-testing.toml#L48-L54

I lean towards closing this as not worth it. The cron job does a good job as is.

**Comment by frankharkins** [comment]
Yeah I agree

**Comment by johannesgreiner** [comment]
an idea is to have the notebooks modified such that our test_* backends will be used for pipeline testing wherever possible
