### ISSUE TITLE
Communicate to users which requirements are necessary for the notebook

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/documentation#1189]
This is quite similar to https://github.com/Qiskit/documentation/issues/922, but a bigger scope that we need to communicate what all the top-level requirements are for the notebook. For now, those are the same thing actually:

https://github.com/Qiskit/documentation/blob/124e14359dd1da55fa34ff2ffe2d0c06ab0155a0/scripts/nb-tester/requirements.txt#L3-L10

All the non Qiskit requirements are not directly imported. But there will be some tutorials in `tutorials/` that may use additional tools like rustworkx. We need to signal to the user what they should install.

This would be nice to automate, although we have to keep in mind that the `tutorials/` folder is deployed to a different app than `docs/`. That implies we can't easily use an MDX component like `<VersionTable>`. We'd need to insert the version information into the `tutorials/` notebook folders at build-time, not run-time. 

Ideally we could list which versions were used, but this isn't a hard requirement.

**Comment by frankharkins** [comment]
We don't handle tutorials any more, but I think this would still be helpful in our docs notebook. Maybe we can add version info at the bottom or something?
