### ISSUE TITLE
Update `README.md` with contributing info

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#12]
To include:
- What types of contributions we do and do not accept
- what the process is for suggesting/contributing a new page
- what types of contributions we recommend/encourage
- how to make each type of contribution
- how to run the docs locally
- a short bit of info about how the deployment pipeline works
- how we triage API ref feedback

**Comment by Eric-Arellano** [comment]
This should mention the forking work flow of open source. An internal IBM contributor was confused on this.
