### ISSUE TITLE
Qiskit API: group modules into logical sections

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/documentation#1211]
For example

![image](https://github.com/Qiskit/documentation/assets/14852634/b3af19bd-fcbe-49a2-8609-68a6f943ac57)

![image](https://github.com/Qiskit/documentation/assets/14852634/e3446ffa-1bf3-4213-afd8-afd2eb464d97)

The main changes:

1. group related modules into new categories
2. flatten submodules to reduce overall nesting

## Qiskit 1.0 modules

<details><summary>code to find modules</summary>

```python
from pathlib import Path
import json

raw = Path("docs/api/qiskit/_toc.json").read_text()
content = json.loads(raw)

all_modules = set()

def add_modules(entry) -> None:
    if entry.get("title").startswith("qiskit."):
        all_modules.add(entry["title"])
    if "children" in entry:
        for child in entry["children"]:
            add_modules(child)


add_modules(content)
print("\n".join(sorted(all_modules)))
```

</details>

<details><summary>module list</summary>

qiskit.assembler
qiskit.circuit
qiskit.circuit.classical
qiskit.circuit.classicalfunction
qiskit.circuit.library
qiskit.circuit.singleton
qiskit.compiler
qiskit.converters
qiskit.dagcircuit
qiskit.exceptions
qiskit.passmanager
qiskit.primitives
qiskit.providers
qiskit.providers.basic_provider
qiskit.providers.fake_provider
qiskit.providers.models
qiskit.pulse
qiskit.qasm2
qiskit.qasm3
qiskit.qobj
qiskit.qpy
qiskit.quantum_info
qiskit.result
qiskit.scheduler
qiskit.synthesis
qiskit.synthesis.unitary.aqc
qiskit.transpiler
qiskit.transpiler.passes
qiskit.transpiler.passes.synthesis.plugin
qiskit.transpiler.preset_passmanagers
qiskit.transpiler.preset_passmanagers.plugin
qiskit.utils
qiskit.visualization
</details>

**Comment by javabster** [comment]
I'm sure the qiskit devs will have a better suggestion, but how about something like this for the grouping? I tried to group things into sections according to what users might be most likely to look for:

Circuit & Operator Construction

- qiskit.circuit
- qiskit.circuit.classical
- qiskit.circuit.classicalfunction
- qiskit.circuit.library
- qiskit.circuit.singleton
- qiskit.quantum_info

Transpilation
- qiskit.dagcircuit
- qiskit.passmanager
- qiskit.synthesis (not sure about this one)
- qiskit.synthesis.unitary.aqc (not sure about this one)
- qiskit.transpiler
- qiskit.transpiler.passes
- qiskit.transpiler.passes.synthesis.plugin
- qiskit.transpiler.preset_passmanagers
- qiskit.transpiler.preset_passmanagers.plugin

Primitives and providers
- qiskit.primitives
- qiskit.providers
- qiskit.providers.basic_provider
- qiskit.providers.fake_provider
- qiskit.providers.models

Results and visualisations
- qiskit.qpy
- qiskit.result
- qiskit.visualization

OpenQASM support
- qiskit.qasm2
- qiskit.qasm3

Pulse calibration
- qiskit.scheduler
- qiskit.pulse

Other
- qiskit.assembler
- qiskit.compiler
- qiskit.converters
- qiskit.exceptions
- qiskit.qobj
- qiskit.utils

**Comment by Eric-Arellano** [comment]
Module list when you include 0.19 up to 1.0:

Circuit construction
* qiskit.circuit
* qiskit.circuit.classical
* qiskit.circuit.classicalfunction
* qiskit.circuit.library
* qiskit.circuit.qpy_serialization
* qiskit.circuit.singleton

Quantum Information (qiskit.quantum_info)
* qiskit.quantum_info

Transpilation
* qiskit.dagcircuit
* qiskit.passmanager
* qiskit.synthesis
* qiskit.synthesis.unitary.aqc
* qiskit.transpiler
* qiskit.transpiler.passes
* qiskit.transpiler.passes.synthesis.plugin
* qiskit.transpiler.preset_passmanagers
* qiskit.transpiler.preset_passmanagers.plugin
* qiskit.transpiler.synthesis.aqc

Primitives and providers
* qiskit.primitives
* qiskit.providers
* qiskit.providers.aer
* qiskit.providers.aer.extensions
* qiskit.providers.aer.jobs
* qiskit.providers.aer.library
* qiskit.providers.aer.noise
* qiskit.providers.aer.pulse
* qiskit.providers.aer.utils
* qiskit.providers.basic_provider
* qiskit.providers.basicaer
* qiskit.providers.fake_provider
* qiskit.providers.ibmq
* qiskit.providers.ibmq.credentials
* qiskit.providers.ibmq.experiment
* qiskit.providers.ibmq.job
* qiskit.providers.ibmq.managed
* qiskit.providers.ibmq.random
* qiskit.providers.ibmq.runtime
* qiskit.providers.ibmq.utils
* qiskit.providers.models

Results and visualisations
* qiskit.result
* qiskit.qpy
* qiskit.validation
* qiskit.visualization
* qiskit.visualization.pulse.interpolation
* qiskit.visualization.pulse.qcstyle

Opflow
* qiskit.opflow
* qiskit.opflow.converters
* qiskit.opflow.evolutions
* qiskit.opflow.expectations
* qiskit.opflow.gradients
* qiskit.opflow.list_ops
* qiskit.opflow.primitive_ops
* qiskit.opflow.state_fns

OpenQASM support
* qiskit.qasm
* qiskit.qasm2
* qiskit.qasm3

Pulse-level programming
* qiskit.pulse
* qiskit.pulse.channels
* qiskit.pulse.instructions
* qiskit.pulse.library
* qiskit.pulse.library.discrete
* qiskit.pulse.pulse_lib
* qiskit.pulse.pulse_lib.discrete
* qiskit.scheduler
* qiskit.scheduler.methods.basic
* qiskit.scheduler.schedule_circuit
* qiskit.scheduler.utils

Other
* qiskit.assembler
* qiskit.compiler
* qiskit.converters
* qiskit.exceptions
* qiskit.qobj
* qiskit.tools
* qiskit.tools.jupyter
* qiskit.utils
* qiskit.utils.mitigation

Not sure?
* qiskit.execute
* qiskit.execute_function
* qiskit.extensions

Algorithms
* qiskit.algorithms
* qiskit.algorithms.eigensolvers
* qiskit.algorithms.gradients
* qiskit.algorithms.linear_solvers
* qiskit.algorithms.minimum_eigensolvers
* qiskit.algorithms.optimizers
* qiskit.algorithms.optimizers.nlopts
* qiskit.algorithms.optimizers.optimizer_utils
* qiskit.algorithms.state_fidelities
* qiskit.algorithms.time_evolvers.trotterization
* qiskit.algorithms.time_evolvers.variational

Qiskit Aqua
* qiskit.aqua
* qiskit.aqua.algorithms
* qiskit.aqua.algorithms.minimum_eigen_solvers.cplex
* qiskit.aqua.circuits
* qiskit.aqua.components
* qiskit.aqua.components.eigs
* qiskit.aqua.components.feature_maps
* qiskit.aqua.components.initial_states
* qiskit.aqua.components.iqfts
* qiskit.aqua.components.multiclass_extensions
* qiskit.aqua.components.neural_networks
* qiskit.aqua.components.optimizers
* qiskit.aqua.components.optimizers.nlopts
* qiskit.aqua.components.oracles
* qiskit.aqua.components.qfts
* qiskit.aqua.components.reciprocals
* qiskit.aqua.components.uncertainty_models
* qiskit.aqua.components.uncertainty_problems
* qiskit.aqua.components.variational_forms
* qiskit.aqua.operators
* qiskit.aqua.operators.converters
* qiskit.aqua.operators.evolutions
* qiskit.aqua.operators.expectations
* qiskit.aqua.operators.gradients
* qiskit.aqua.operators.legacy
* qiskit.aqua.operators.list_ops
* qiskit.aqua.operators.primitive_ops
* qiskit.aqua.operators.state_fns
* qiskit.aqua.utils

Qiskit Ignis
* qiskit.ignis
* qiskit.ignis.characterization
* qiskit.ignis.logging
* qiskit.ignis.measurement
* qiskit.ignis.mitigation
* qiskit.ignis.verification
* qiskit.ignis.verification.basis

Finance
* qiskit.finance
* qiskit.finance.applications
* qiskit.finance.applications.ising
* qiskit.finance.applications.ising.portfolio
* qiskit.finance.applications.ising.portfolio_diversification
* qiskit.finance.components
* qiskit.finance.components.uncertainty_problems
* qiskit.finance.data_providers

Chemistry 
* qiskit.chemistry
* qiskit.chemistry.algorithms
* qiskit.chemistry.algorithms.pes_samplers
* qiskit.chemistry.applications
* qiskit.chemistry.components
* qiskit.chemistry.components.bosonic_bases
* qiskit.chemistry.components.initial_states
* qiskit.chemistry.components.variational_forms
* qiskit.chemistry.core
* qiskit.chemistry.drivers
* qiskit.chemistry.drivers.gaussiand
* qiskit.chemistry.drivers.psi4d
* qiskit.chemistry.drivers.pyquanted
* qiskit.chemistry.drivers.pyscfd
* qiskit.chemistry.results
* qiskit.chemistry.transformations

Machine Learning
* qiskit.ml
* qiskit.ml.circuit.library
* qiskit.ml.datasets

Optimization
* qiskit.optimization
* qiskit.optimization.algorithms
* qiskit.optimization.applications
* qiskit.optimization.applications.ising
* qiskit.optimization.applications.ising.clique
* qiskit.optimization.applications.ising.common
* qiskit.optimization.applications.ising.docplex
* qiskit.optimization.applications.ising.exact_cover
* qiskit.optimization.applications.ising.graph_partition
* qiskit.optimization.applications.ising.knapsack
* qiskit.optimization.applications.ising.max_cut
* qiskit.optimization.applications.ising.partition
* qiskit.optimization.applications.ising.set_packing
* qiskit.optimization.applications.ising.stable_set
* qiskit.optimization.applications.ising.tsp
* qiskit.optimization.applications.ising.vehicle_routing
* qiskit.optimization.applications.ising.vertex_cover
* qiskit.optimization.converters
* qiskit.optimization.problems
