### ISSUE TITLE
"Get backend information" uses cloud simulator

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/documentation#1228]
### URL to the relevant documentation

https://docs.quantum.ibm.com/run/get-backend-information

Here's the problem cell:

```python
service.backend("ibmq_qasm_simulator")
```

### Select all that apply

- [ ] typo
- [ ] code bug
- [ ] out-of-date content
- [ ] broken link
- [ ] other

### Describe the fix.

Switch to a different backend. While this should work for open users at the moment, the simulators will be deprecated soon and this notebook will break.

**Comment by beckykd** [comment]
@frankharkins already has a PR open to update this here: https://github.com/Qiskit/documentation/pull/1232  So I removed myself from the assignment.
