### ISSUE TITLE
VQE tutorial takes too long to run

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/documentation#1229]
### URL to the relevant documentation

https://learning.quantum.ibm.com/tutorial/variational-quantum-eigensolver (`tutorials/variational-quantum-eigensolver/vqe.ipynb`).

I ran this overnight and it still had not completed. See #1226 for more context.

### Select all that apply

- [ ] typo
- [X] code bug
- [ ] out-of-date content
- [ ] broken link
- [ ] other

### Describe the fix.

Refactor notebook to run in a reasonable time (once the session actually starts).

**Comment by abbycross** [comment]
Chiming in:
I am running VQE right now on kyiv and it's been going for 73+ minutes. When I ran it on manila (5Q), it completed in about 30.
