### ISSUE TITLE
More explicitly direct people to run notebooks with `tox`

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/documentation#1239]
The majority of our authors use VSCode, which will by default generate PNGs rather than the superior SVGs. We should tell them how to set up VSCode to use SVGs instead.

This is probably a global config you set for Jupyter?

This change would help avoid the need for https://github.com/Qiskit/documentation/pull/1226.

**Comment by frankharkins** [comment]
I'm happy to add the documentation, but I'm not sure how effective it is to keep adding things like this to our READMEs. They already contain a lot of information, only some of which is relevant to each contributor, and I doubt contributors review them regularly for updates.

I think ideally we'd have a unified workflow which everyone follows, then we could do things like switch to SVGs, update packages, etc. without needing contributors to set their config or remember to run another script. This is kinda what I'd hoped for with `tox`, but it doesn't seem to have stuck. Maybe we should chat to the contributors and work out if there's a better way to integrate it.

A potential solution is to incorporate something like the "auto execute" function from #601. We know for a fact all contributors go through PRs, and it makes running tox a one-step process with no local installation.

I do still think it's worth adding processes such as how to deploy tutorials; contributors will seek those out when they need them. I just think it's kinda futile adding rules and guidelines.

**Comment by Eric-Arellano** [comment]
In the backlog sweep, we agreed with you, Frank. Rather than telling people how to better configure VSCode, we should be directing them to use `tox` for the final run. It's fine to use VSCode/Jupyter when iterating, but we want `tox` for the final execution so that we are all using a consistent environment.

So this issue is now revisiting the README to see if we can make this expectation more clear.
