### ISSUE TITLE
Revisit the transpiler module pages for Runtime API docs

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/documentation#1240]
The module pages aren't particularly useful.

https://docs.quantum.ibm.com/api/qiskit-ibm-runtime/transpiler:

<img width="563" alt="Screenshot 2024-04-24 at 3 34 13 PM" src="https://github.com/Qiskit/documentation/assets/14852634/94f2f194-8a63-4c69-b730-af95387a5718">

https://docs.quantum.ibm.com/api/qiskit-ibm-runtime/qiskit_ibm_runtime.transpiler.passes

<img width="585" alt="Screenshot 2024-04-24 at 3 34 31 PM" src="https://github.com/Qiskit/documentation/assets/14852634/1fef94c9-3a68-4660-8667-5d15516d5c9b">

https://docs.quantum.ibm.com/api/qiskit-ibm-runtime/qiskit_ibm_runtime.transpiler.passes.basis: 
<img width="531" alt="Screenshot 2024-04-24 at 3 34 40 PM" src="https://github.com/Qiskit/documentation/assets/14852634/058ffc4b-358b-4ab2-8f38-1b5198c02bca">

https://docs.quantum.ibm.com/api/qiskit-ibm-runtime/qiskit_ibm_runtime.transpiler.passes.scheduling is really useful though.

**Comment by frankharkins** [comment]
What's the solution? To add more information to the docstrings? I wonder if the reason scheduling had so much information is because it's not covered in the rest of the docs, whereas the transpiler is.

**Comment by Eric-Arellano** [comment]
Or consider if we should remove any of the pages. In particular, I don't understand why https://docs.quantum.ibm.com/api/qiskit-ibm-runtime/qiskit_ibm_runtime.transpiler.passes.basis is documented
