### ISSUE TITLE
Document primitive option precedence rules

### ISSUE THREAD

**Issue by ihincks** [Qiskit/documentation#1247]
### Describe the new content you are requesting.

When a user sets options like this,

```python
from qiskit_ibm_runtime import EstimatorV2, QiskitRuntimeService
from qiskit import QuantumCircuit

service = QiskitRuntimeService()
backend = service.backend("ibm_auckland")

estimator = EstimatorV2(backend)

estimator.options.default_shots = 100
estimator.options.resilience_level = 0
estimator.options.resilience.zne_mitigation = True
```

it might not be clear how the resilience level might interact with the other options, because the resilience level itself can modify the mitigation strategy. In this example, does setting the resilience level to 0 have the effect of turning off the attempt to add zne_mitigation? (spoiler: no)

What needs to be documented is that that the resilience level is FIRST used to set a base configuration on any options it thinks are relevant, and THEN any other user-specified options are updated on top of that. So it would be possible, for example, though pointless, to completely undo the effect of setting the resilience level by reversing all of its intentions manually.

### If this new content request is accepted, do you want to write the content?

I can help the team by providing enough information to write the material

**Comment by abbycross** [comment]
Which page do you envision this living on, @ihincks? The [primitives examples](https://docs.quantum.ibm.com/run/primitives-examples) page, the [V2 migration guide](https://docs.quantum.ibm.com/api/migration-guides/v2-primitives), etc.

**Comment by abbycross** [comment]
Thanks @ihincks! What is the timeline for this content? Are you ready to open a PR for it, and how can we support you with it? If it might be more than a few weeks before this is ready, I'll add it to our backlog.

**Comment by beckykd** [comment]
@ihincks , this content is being revamped, so your suggested content ended up on the new options overview page.  See this PR: #1499 It's not totally done yet, but you're welcome to give feedback.
