### ISSUE TITLE
Add back `class` modifier in front of class signatures

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/documentation#1287]
This is how Sphinx renders https://docs.quantum.ibm.com/api/qiskit/dev/circuit#bits-and-registers

<img width="575" alt="Screenshot 2024-05-02 at 4 05 32 PM" src="https://github.com/Qiskit/documentation/assets/14852634/d8931a59-e7fb-45a5-b7ed-a3dec763b364">

Vs us:

<img width="475" alt="Screenshot 2024-05-02 at 4 05 41 PM" src="https://github.com/Qiskit/documentation/assets/14852634/d1ef8613-c98b-4e29-ae05-4e390f0f031f">

https://github.com/Qiskit/documentation/blob/eca9f437aa521d4419fe94e7537e60f405f30863/docs/api/qiskit/dev/circuit.mdx?plain=1#L260

Should we add back the `class` modifier? Should it only be for inline classes, or also dedicated pages like https://docs.quantum.ibm.com/api/qiskit/dev/qiskit.circuit.AnnotatedOperation?

<img width="695" alt="Screenshot 2024-05-02 at 4 09 32 PM" src="https://github.com/Qiskit/documentation/assets/14852634/a3ad8489-78fc-4029-bc44-24d753f7acce">

If so, should it be italicized? If it should be italicized, should we add a new attribute to the component like `signaturePrefix`?

--

What's interesting is some signatures are preserved, like `final class` and `static`. Why is this?

https://github.com/Qiskit/documentation/blob/eca9f437aa521d4419fe94e7537e60f405f30863/docs/api/qiskit/circuit_classical.mdx?plain=1#L63

https://github.com/Qiskit/documentation/blob/eca9f437aa521d4419fe94e7537e60f405f30863/docs/api/qiskit-ibm-runtime/qiskit_ibm_runtime.options.Options.mdx?plain=1#L90

**Comment by Eric-Arellano** [comment]
We decided that we do want to do this. We still need to figure out the design. Devs should create a few examples for us to decide:

* `class` in the code section w/o italics
* `class` in the code section w/ italics (if possible)
* `class` before the code section w/o italics
* `class` before the code section w/ italics

We should audit if there are any other modifiers we've been dropping.

**Comment by arnaucasau** [comment]
Here are the screenshots with an example of how each design would look like. I added the case where we have the modifier w/ bold in and before the code section.

### Inside the code section examples

#### Option 1. `class` in the code section

![Captura desde 2024-05-07 18-26-34](https://github.com/Qiskit/documentation/assets/47946624/506045c5-28fb-4a07-a9cd-f1723b021547)

#### Option 2. `class` in the code section w/ italics
![Captura desde 2024-05-07 18-29-24](https://github.com/Qiskit/documentation/assets/47946624/dd178de1-e8d3-4244-9ca2-ceb5f0f2099c)

#### Option 3. `class` in the code section w/ bold
![Captura desde 2024-05-07 18-34-41](https://github.com/Qiskit/documentation/assets/47946624/b2fed860-24d1-4df7-bdac-fc75cbc74faf)

### Before the code section examples

#### Option 4. `class` before the code section
![Captura desde 2024-05-07 18-32-42](https://github.com/Qiskit/documentation/assets/47946624/6f6d4716-03f2-4012-91c5-a1cec4c5a590)

#### Option 5. `class` in the code section w/ italics
![Captura desde 2024-05-07 18-31-12](https://github.com/Qiskit/documentation/assets/47946624/691ca4cb-e3d7-4ad4-8f65-996cfbb46520)

#### Option 6. `class` before the code section w/ bold
![Captura desde 2024-05-07 18-33-34](https://github.com/Qiskit/documentation/assets/47946624/ca8e4029-a8cd-46ff-98ea-9db535c4ac0c)

**Comment by Eric-Arellano** [comment]
Closed by @arnaucasau in https://github.com/Qiskit/documentation/pull/1337 🚀
