### ISSUE TITLE
API docs headers don't fit the page and create a horizontal scroll

### ISSUE THREAD

**Issue by arnaucasau** [Qiskit/documentation#1290]
Some `<h1>` headers don't fit the page and create a horizontal scroll for qiskit v0.19 but this could happen on other pages/versions too.

Two examples can be found on at [page1](https://docs.quantum.ibm.com/api/qiskit/0.19/qiskit.finance.applications.ising.portfolio), and [page2](https://docs.quantum.ibm.com/api/qiskit/0.19/qiskit.finance.applications.ising.portfolio_diversification). In the following screenshot, we can see the header before and after using the horizontal scroll.
![Captura desde 2024-05-03 12-00-55](https://github.com/Qiskit/documentation/assets/47946624/60d73edd-c4e3-4f31-983a-6734485da925)
![Captura desde 2024-05-03 12-01-02](https://github.com/Qiskit/documentation/assets/47946624/b37a1e7a-150b-4576-9fa1-761ed34355c0)

**Comment by Eric-Arellano** [comment]
Fixed
