### ISSUE TITLE
Docs: Need instructions to cancel a job

### ISSUE THREAD

**Issue by beckykd** [Qiskit/documentation#1304]
We have instructions to cancel a session, but not a job.  It would be a good fit for for the Manage Jobs section under Run.   You can cancel it on the Jobs page from IQP, but this wasn't intuitive to me since it doesn't show up on the IQP home page, nor is there a way to do it if you look at the job from the home page.

**Comment by javabster** [comment]
would be great to include the code way to do this: https://docs.quantum.ibm.com/api/qiskit-ibm-runtime/qiskit_ibm_runtime.RuntimeJobV2#cancel
