### ISSUE TITLE
Consider using Qiskit Serverless for cron job notebook testing

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/documentation#1323]
In our cron job, we run every notebook that submits jobs: 

https://github.com/Qiskit/documentation/blob/83573cc03402cab51743656b779fbb6b0fecd863/.github/workflows/notebook-test-cron.yml#L33

But the jobs might take longer than GH Actions' 6 hour limit when there is a long queue. Notably, we cannot batch the different jobs because they are distinct notebooks so using `with Batch` is not viable. We now use concurrency with `asyncio`, but we still can exceed the time limit.

So, instead, @frankharkins had the great idea of using Qiskit Serverless. On day 1, we'd submit all the notebooks to Qiskit Serverless. On day 2, a new cron job would run that retrieves the results from Qiskit Serverless.

Question: what workflow do we want for local runs?

**Comment by frankharkins** [comment]
Putting this on hold for a bit as the action is actually doing OK at the moment and we might be able to get higher priority if it starts being a problem again. I'm worried serverless would add yet another layer of things to go wrong.

**Comment by Eric-Arellano** [comment]
@frankharkins now that we don't have tutorials, what do you think about this? Should we close it?

**Comment by frankharkins** [comment]
Yeah let's close it, I don't think this is a big problem any more.
