### ISSUE TITLE
Qiskit Transpiler Service: figure out why type hints aren't showing links

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/documentation#1324]
For example:

<img width="676" alt="Screenshot 2024-05-08 at 10 48 17 AM" src="https://github.com/Qiskit/documentation/assets/14852634/a6702e18-b07b-4707-8ab0-756fd8bbd767">

https://github.com/Qiskit/documentation/blob/cd57d83b76a9c726bbaa9d870df950b2f6bbc316/docs/api/qiskit-transpiler-service/qiskit_transpiler_service.transpiler_service.TranspilerService.mdx?plain=1#L18

Compare this with https://docs-pr-1406.preview.quantum.ibm.com/api/qiskit-ibm-runtime/qiskit_ibm_runtime.Batch#from_id, where the type hint is in the actual source code https://github.com/Qiskit/qiskit-ibm-runtime/blob/stable/0.23/qiskit_ibm_runtime/session.py#L333-L376 yet it renders in the function body

<img width="855" alt="Screenshot 2024-05-08 at 10 49 34 AM" src="https://github.com/Qiskit/documentation/assets/14852634/ff1bc76d-41de-47cf-a36e-18956910444b">

I imagine this is an issue with the config we have. This fix should be in Sphinx, not our generation script.

**Comment by frankharkins** [comment]
It seems all type hints inside signatures are not links. See https://docs.quantum.ibm.com/api/qiskit/qiskit.circuit.QuantumCircuit#assign_parameters as an example.

<img width="845" alt="Screenshot 2024-05-16 at 17 51 16" src="https://github.com/Qiskit/documentation/assets/36071638/0b982073-8c20-445f-8d09-3c9eae8db4e0">

The href is present in the HTML. I believe this kicks the problem back to the generation script.

**Comment by Eric-Arellano** [comment]
This was fixed by @frankharkins. The solution was to set 

https://github.com/Qiskit/qiskit/blob/61323662a7b7349aa1d47fc0d39f3bf04fdbc931/docs/conf.py#L105-L107
