### ISSUE TITLE
user feedback: Some small improvements to migration guides

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#1325]
I received some feedback that the migration guides sometime present a ton of options for people to choose from, but what is missing is some intuition to help a user decide which of the alternative options is best for them. For example in the simulator migration guide we show information for `FakeBackend, AerSimulator, Clifford...` etc, but we don't provide much guidance on which should a user choose to use.

Perhaps this could be solved by adding a short comparison table (or even just a paragraph in the intro) that compares the different tools, what features they have, what situations you might want to use them for etc.

**Comment by frankharkins** [comment]
@AbdullahKazi500 this issue is free, would you like to work on this?

**Comment by quarktetra23** [comment]
Hello @javabster,
Can you please assign this issue to me? I can work on the differentiating part.

**Comment by beckykd** [comment]
Closed by PR #1928
