### ISSUE TITLE
An user should be able to understand how IBM Quantum charges for failed jobs

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/documentation#1347]
### Describe the new content you are requesting.

IBM Quantum bills usage for some failed jobs, but not others.  What is the criteria for charging for some failed jobs, but not others?

### If this new content request is accepted, do you want to write the content?

I only want to review the material when it's finished

**Comment by abbycross** [comment]
Consulting with the Support team on this

**Comment by javabster** [comment]
issue moved to another repo
