### ISSUE TITLE
Need to mention the 'graphviz' library

### ISSUE THREAD

**Issue by beckykd** [Qiskit/documentation#1394]
### URL to the relevant documentation

https://docs.quantum.ibm.com/transpile/custom-backend#visualize-backends

### Select all that apply

- [ ] typo
- [ ] code bug
- [ ] out-of-date content
- [ ] broken link
- [X] other

### Describe the fix.

Plotting a coupling map requires the graphviz library.  We should list it as a requirement in this topic. 

On Mac it seems simple to install, but on Windows, there's a whole big process.   I didn't have time to investigate further, but wanted to note the requirement. 

MissingOptionalLibraryError: "The 'graphviz' library is required to use 'plot_coupling_map'. You can install it with ''brew install graphviz' if on Mac, or by downloding it from their website'."

**Comment by javabster** [comment]
related to #1286
