### ISSUE TITLE
Properly support global variables in API docs (`.. py:data::`) 

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/documentation#1401]
This builds on top of https://github.com/Qiskit/documentation/issues/935, which is about broken cross-references. This issue is to also have a more intentional visual design for `.. py:data::`, such as an MDX component like `<GlobalVariable>` (name tbd).

<details><summary>unannotated screenshot</summary>

<img width="869" alt="Screenshot 2024-05-17 at 1 31 41 PM" src="https://github.com/Qiskit/documentation/assets/14852634/b80417e4-018d-4e4c-a1cb-696f5e287074">
</details>

<details><summary>annotated screenshot</summary>

<img width="869" alt="Screenshot 2024-05-17 at 1 31 41 PM" src="https://github.com/Qiskit/documentation/assets/14852634/56657b16-a913-4709-9ca7-88440dfd46ee">
</details>

<details><summary>offending code</summary>

https://github.com/Qiskit/documentation/blob/394ca77e604b7c58dd916c7ad8f104b6c1e339ac/docs/api/qiskit/dev/circuit.mdx?plain=1#L883-L893
</details>

I propose the design should look the same as our other components: a purple or blue left bar, header inside the component (https://github.com/Qiskit/documentation/issues/1395) with whatever the correct surrounding level would be, and ensure there is a `<span id>` or that the header has the ID.

**Comment by jakelishman** [comment]
Oh boy - "A `EquivalenceLibrary" haha. No points for English for me.
