### ISSUE TITLE
Deprecation & Subsequent Removal of Custom Programs

### ISSUE THREAD

**Issue by drew-distefano** [Qiskit/documentation#142]
### URL to the relevant documentation

For example, e.g. [time limit page](https://qiskit.org/ecosystem/ibm-runtime/faqs/max_execution_time.html#session-time-limits) still talks about custom ("private") programs

### Select all that apply

- [ ] typo
- [ ] code bug
- [X] out-of-date content
- [ ] broken link
- [ ] other

### Describe the fix.

We are deprecating and then removing Custom Programs for external users. Internal users will still have access to custom programs.

For user awareness, we will need to update the public facing documentation. This should be done in two phases – once when we deprecate custom programs ([#291](https://github.ibm.com/ibm-q-software/ws-qiskit-runtime-api/issues/291)) and again when we remove custom programs ([#292](https://github.ibm.com/ibm-q-software/ws-qiskit-runtime-api/issues/292)).

Both documentation sources will need to be updated:

https://qiskit.org/ecosystem/ibm-runtime/
https://docs.quantum-computing.ibm.com/

**Comment by jyu00** [comment]
Note, the actual deprecation date is still TBD, so don't update the docs yet! 

Also should talk about the replacement + [migration guide](https://qiskit-extensions.github.io/quantum-serverless/migration/migration_from_qiskit_runtime_programs.html).

**Comment by abbycross** [comment]
Thanks @drew-distefano ! For the changes to the qiskit.org page, the repo is, I believe, https://github.com/Qiskit/qiskit.org/issues.

I was about to ask when the deprecation dates are, but @jyu00 posted while I was typing :)

**Comment by javabster** [comment]
we can update the https://docs.quantum-computing.ibm.com/ pages here in this repo, but to update the files in https://qiskit.org/ecosystem/ibm-runtime/ the updates will need to be made in https://github.com/Qiskit/qiskit-ibm-runtime (not https://github.com/Qiskit/qiskit.org). If you want these docs updates published before 1st Dec then it will need to be updated in both repos. After 1st Dec it will only need updating in this repo (we're in the middle of migrating content from one place to the other, so temporarily the content lives in both places)

If you can let us know what updates need to be done by what dates we can start working on that and get it updated in both places, or just one if the deadline is post 1st Dec

**Comment by drew-distefano** [comment]
@javabster I'll let you know when I have firm dates. Please plan to make the first round of updates (for deprecation) prior to Dec 1 and the second round (for removal) some time after Summit (Dec 6).

Do you need me to add a story to https://github.com/Qiskit/qiskit-ibm-runtime to cover the updates there?

**Comment by javabster** [comment]
> Do you need me to add a story to https://github.com/Qiskit/qiskit-ibm-runtime to cover the updates there?
yes that would be helpful, and please reference this issue in the description, thank-you :)

**Comment by drew-distefano** [comment]
Issue in `qiskit-ibm-runtime`: https://github.com/Qiskit/qiskit-ibm-runtime/issues/1149

@javabster @beckykd the tentative release dates for the changes are Nov 1 (deprecation) & Nov 27 (removal). I will update here if the dates change.

**Comment by jyu00** [comment]
Here's the migration guide we should point people to: https://qiskit-extensions.github.io/quantum-serverless/migration/migration_from_qiskit_runtime_programs.html

**Comment by Eric-Arellano** [comment]
@jyu00 should this migration guide be moved to live in our new migration guides section at https://docs.quantum-computing.ibm.com/api/migration-guides?

**Comment by jyu00** [comment]
If we do move it, we'd need to give a lot of context on what Quantum Serverless is. I thought the docs team isn't ready to move Serverless into 1doc yet?

**Comment by abbycross** [comment]
We will have a live doc on Nov 1 -- work is being done here: https://github.com/Qiskit/documentation/pull/209

**Comment by abbycross** [comment]
Mentions of custom/private programs are removed from the docs now, with the exception of this migration guide, which has relevant sections marked as "to be deprecated" -- please let us know if anyone comes across any allusion to them that we've missed in our search. cc: @beckykd

**Comment by drew-distefano** [comment]
@abbycross The custom program deprecation has been pushed back to Nov 2. Please hold off on publishing these changes until after the announcement has been made. cc @jyu00

**Comment by abbycross** [comment]
I believe this can be closed as far as work in qiskit/documentation goes -- any objections?

**Comment by jyu00** [comment]
There is some work needed to remove `/programs` endpoints from the API page. I don't know if that's tracked here or a separate issue.

**Comment by beckykd** [comment]
That's tracked here: https://github.ibm.com/cloud-docs/quantum-computing/issues/143

**Comment by drew-distefano** [comment]
I see https://github.com/Qiskit/documentation/pull/209 is meged. OK to close this issue.
