### ISSUE TITLE
Aer simulators support V2

### ISSUE THREAD

**Issue by beckykd** [Qiskit/documentation#1422]
### URL to the relevant documentation

https://docs.quantum.ibm.com/verify
https://docs.quantum.ibm.com/verify/simulate-with-qiskit-aer

### Select all that apply

- [ ] typo
- [ ] code bug
- [X] out-of-date content
- [ ] broken link
- [ ] other

### Describe the fix.

As of qiskit-aer 0.14 or later, the Aer simulators do support the V2 interface.

**Comment by kevinsung** [comment]
https://docs.quantum.ibm.com/verify/simulate-with-qiskit-aer may need some rewriting because apparently, Qiskit Aer no longer supports computing an exact expectation value (I might be wrong about this).

**Comment by kevinsung** [comment]
Ah I confused this issue with https://github.com/Qiskit/documentation/issues/1025.
