### ISSUE TITLE
QiskitBackendNotFoundError: 'No backend matches the criteria.' errors.

### ISSUE THREAD

**Issue by kiki1123** [Qiskit/documentation#1428]
### URL to the relevant documentation

In tutorials of local testing mode (https://docs.quantum.ibm.com/api/qiskit-ibm-runtime/runtime_service) and AerSimulator (https://docs.quantum.ibm.com/api/qiskit-ibm-runtime/fake_provider), QiskitBackendNotFoundError: 'No backend matches the criteria.' errors are found.

### Select all that apply

- [ ] typo
- [X] code bug
- [ ] out-of-date content
- [ ] broken link
- [ ] other

### Describe the fix.

Env:
qiskit 1.0.2 
python 3.12.2
MacOS

**Comment by abbycross** [comment]
Hi @kiki1123 - what version of qiskit-ibm-runtime are you using? Thanks!

**Comment by kiki1123** [comment]
Sorry, I was using an outdated version. It works now, thank you!
