### ISSUE TITLE
Update the CHSH tutorial

### ISSUE THREAD

**Issue by beckykd** [Qiskit/documentation#1443]
### URL to the relevant documentation

https://learning.quantum.ibm.com/tutorial/chsh-inequality

### Select all that apply

- [ ] typo
- [ ] code bug
- [X] out-of-date content
- [ ] broken link
- [ ] other

### Describe the fix.

Issues identified by Paul N:

The CHSH tutorial is tagged "scheduling", but there is no scheduling involved.

Also the text below the final figure references simulation results that no longer exist in the tutorial

**Comment by beckykd** [comment]
@frankharkins @Eric-Arellano - can we change this tag?

**Comment by Eric-Arellano** [comment]
@beckykd we'll be update the tag in this repo after landing https://github.com/Qiskit/documentation/pull/1421. In the meantime, @frankharkins could you please update it?

**Comment by beckykd** [comment]
Fixed by #1447 -- @frankharkins , could you please close this issue after publishing the CHSH tutorial live?

**Comment by beckykd** [comment]
Verified that it was published.
