### ISSUE TITLE
Add information on how to turn off error mitigation / suppression

### ISSUE THREAD

**Issue by jyu00** [Qiskit/documentation#1453]
### URL, if applicable

https://docs.quantum.ibm.com/run/configure-error-mitigation

### Describe the new content you are requesting.

Many researchers want total control over their experiments and don't want the primitives to transform their circuits. For `EstimatorV2`, one can just set `resilience_level=0` and `optimization_level=0`. It is however not obvious how to do this for `SamplerV2`, since there is no `resilience_level` in SamplerV2. 

We should have a few words in the docs on how to accomplish this. For SamplerV2, measurement twirling is enabled by default. So one needs to set `options.twirling.enable_measure = False`. 

These defaults can change in the future, so we should decide whether to show code to turn them all off now, or update the docs if/when defaults change. 

My first thought was to add this to the error mitigation page... but this applies to both error mitigation _and_ suppression. Perhaps we can repurpose the compilation page to error suppression, since our compilation is just error suppression now (i.e. no layout and routing). 

### If this new content request is accepted, do you want to write the content?

I can help the team by providing enough information to write the material

**Comment by beckykd** [comment]
I like the idea of repurposing the compilation page for error mitigation, but we'll need signoff from @javabster on that.  But as a temporary fix, I can add some words about disabling it.
