### ISSUE TITLE
Docs reorg: audit new URLs

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/documentation#1466]
URLs are hard to change, so we want the new URLs to be well named. We want to be confident that they will last us in the future, even if the slug is longer. 

To do this, you'd look at https://github.com/Qiskit/documentation/blob/main/scripts/patterns-reorg/redirects.json. Each line has the original URL on the left, and the new URL on the right, but without the `guides/` prefix showing. For example, line 2 `"start/install": "install-qiskit",` means `start/install` -> `guides/install-qiskit`

--

If you want to look at the page title for context, it may be helpful to instead look at `entries.py`, like this:

https://github.com/Qiskit/documentation/blob/640bd7ae0764aca8b3c05fc1f0020331e3f50d9c/scripts/patterns-reorg/entries.py#L35-L39

The first value is the page title. `from_file` is the old URL (minus the extension). `slug` is the new URL without the `guides/` prefix.

--

You can leave suggestions as a comment on this issue.

**Comment by abbycross** [comment]
I do have a vague, maybe-unfounded concern that page titles do change more often than URLs, so if we try to be *too* precise in our filenames, those could go stale. Thoughts @beckykd ?

**Comment by Eric-Arellano** [comment]
> I do have a vague, maybe-unfounded concern that page titles do change more often than URLs, so if we try to be too precise in our filenames, those could go stale. Thoughts @beckykd ?

I totally agree. For example, `qiskit-serverless` is titled "Qiskit Serverless Workloads", and right now it's the only page about Qiskit Serverless. But we could imagine adding more pages about Qiskit Serverless in the future. The `qiskit-serverless` page would still probably act like the introduction page to the tool, so maybe we'd do something like this:

```
Qiskit Serverless
|-  Introduction to Qiskit Serverless (qiskit-serverless)
|_ Advanced workflows (qiskit-serverless-advanced-workflows)
```

In other words, it is good to keep the page name generic as `qiskit-serverless` because it is flexible to us renaming `Qiskit Serverless Workflows` to `Introduction to Qiskit Serverless`. Whereas the URL `qiskit-serverless-workflows` would have been overly precise.

--

On the other end of the spectrum, a page like `configuration` is way too generic.

**Comment by Eric-Arellano** [comment]
> Are actual file names changing then? For example "start/install": "install-qiskit" ?

Yes, every single file is going to need a redirect from the old folders like `start/` to the new `guides/` folder. That means that now is our opportunity to rename the files if we want.

**Comment by beckykd** [comment]
They seem mostly fine, but I think we should pull any with articles in the file names:

  "transpile/create-a-transpiler-plugin": "create-transpiler-plugin",
"run/run-jobs-in-session": "run-jobs-session"

**Comment by abbycross** [comment]
I propose:
- circuit-visualization -> visualize-circuits
- quantum-serverless -> qiskit-serverless (I think we have an issue open for that already)
- circuit-construction -> construct-circuits
- unitary-synthesis -> synthesize-unitary-operators
- representing-quantum-computers -> represent-quantum-computers
- building_noise_models -> build-noise-models
- stabilizer-circuit-simulation -> simulate-stabilizer-circuits
-  primitives-get-started -> start-with-primitives or get-started-with-primitives 
- fair-share-queue -> fair-share-scheduler
- verify/index -> debug or debugging-tools 
-  execution-modes-intro -> execution-modes
-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by Eric-Arellano** [comment]
This is now complete. Thank you everyone!
