### ISSUE TITLE
Update basis gate set documentation 

### ISSUE THREAD

**Issue by lerongil** [Qiskit/documentation#1471]
### URL, if applicable

https://docs.quantum.ibm.com/build

### Describe the new content you are requesting.

We will be add additional gates to the basis gate set including rx, rzx on Eagle and rzz on Heron. There will some limitations to these gate that will need proper documentation.  

### If this new content request is accepted, do you want to write the content?

I can help the team by providing enough information to write the material

**Comment by abbycross** [comment]
Thanks for the heads-up @lerongil! Keep us posted on timeline, whom we should be in touch with as an SME, and what support we can provide.
