### ISSUE TITLE
Incorrect operator ordering

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/documentation#1477]
### URL to the relevant documentation

https://docs.quantum.ibm.com/start/hello-world

### Select all that apply

- [X] typo
- [ ] code bug
- [ ] out-of-date content
- [ ] broken link
- [ ] other

### Describe the fix.

The order of operators in the ZZ expval description are out of order .

**Comment by shraddha-aangiras** [comment]
Could I please work on this? Thanks!

**Comment by nonhermitian** [comment]
This issue is very much still open: https://docs.quantum.ibm.com/guides/hello-world#scale-to-large-numbers-of-qubits
