### ISSUE TITLE
What's new in the docs? product updates should be viewable from the documentation page

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/documentation#1483]
### URL, if applicable

https://docs.quantum.ibm.com/

### Describe the new content you are requesting.

What's new in the docs? product updates should be viewable from the documentation page

### If this new content request is accepted, do you want to write the content?

no

**Comment by javabster** [comment]
related: https://github.com/Qiskit/documentation/issues/1301

**Comment by abbycross** [comment]
This is fixed by the introduction of the Latest updates page #1411
