### ISSUE TITLE
Clarify `backend=backend` runs things in job mode for v2 primitives

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#1486]
If you set `backend=backend` in a v2 primitive it will run the program in job mode, even if it's inside a batch/session context
```
with Batch(backend=backend):
    sampler = SamplerV2(backend=backend)
```

so in general we should emphasise to users that they should not do this and instead use this formats:
```
with Batch(backend=backend):
    sampler = SamplerV2()
```
(note `session=batch` is confusing and will likely be changed in future)

**Comment by arujjval** [comment]
@javabster I want to take this one

**Comment by jyu00** [comment]
> (note session=batch is confusing and will likely be changed in future)

Yeah we are deprecating both `session` and `backend` parameters in primitive `__init__` to avoid this confusing in the next release (hopefully coming out this week). The replacement is [mode](https://github.com/Qiskit/qiskit-ibm-runtime/blob/e0aed7082289fb479496666e6d46e49458777271/qiskit_ibm_runtime/estimator.py#L111).

**Comment by javabster** [comment]
thanks @arujjval go ahead and work on this, make sure to check out the README for contribution instructions before you get started.

@jyu00 for now we'll just mention the version without `session` or `backend` and then update with `mode` in a later PR
