### ISSUE TITLE
from "takes circuit" to "takes the circuit"

### ISSUE THREAD

**Issue by dlete** [Qiskit/documentation#1505]
### URL to the relevant documentation

https://docs.quantum.ibm.com/transpile

### Select all that apply

- [X] typo
- [ ] code bug
- [ ] out-of-date content
- [ ] broken link
- [ ] other

### Describe the fix.

Paragraph two (second paragraph after the title) reads "The process of transpilation takes circuit that contains your instructions:". I believe it should read "The process of transpilation takes **the** circuit that contains your instructions:"

Thanks for the documentation, it is most useful!

**Comment by abbycross** [comment]
Thanks for the catch @dlete!
