### ISSUE TITLE
could not update user's information Request failed with status code 400

### ISSUE THREAD

**Issue by Ghzal818** [Qiskit/documentation#1509]
### URL to the relevant documentation

<img width="1510" alt="Screenshot 2024-06-07 at 11 36 34 PM" src="https://github.com/Qiskit/documentation/assets/171982472/1e3e7163-e33c-420f-b923-25d977136368">

### Please describe the UI problem.

whenever i navigate to the platform to create account i get: could not update user's information
Request failed with status code 400,i am unable to retrieve my API token. how can I resolve it?

**Comment by abbycross** [comment]
Hi @Ghzal818 - this problem should be resolved now - please try again. Thanks!

**Comment by Ghzal818** [comment]
> Hi @Ghzal818 - this problem should be resolved now - please try again. Thanks!

yes, it has been solved. Thank you
