### ISSUE TITLE
Qiskit serverless in Run page is out dated

### ISSUE THREAD

**Issue by akihikokuroda** [Qiskit/documentation#1515]
### URL to the relevant documentation

https://docs.quantum.ibm.com/run/quantum-serverless

### Select all that apply

- [ ] typo
- [ ] code bug
- [X] out-of-date content
- [ ] broken link
- [ ] other

### Describe the fix.

In this page: https://docs.quantum.ibm.com/run/quantum-serverless

IBMServerlessProvider : [Deprecated since version 0.10.0] Use :class:`.IBMServerlessClient` instead. 
```
from qiskit_serverless import IBMServerlessProvider
serverless = IBMServerlessProvider("YOUR_IBM_QUANTUM_TOKEN")
```

and

```
# Run pattern remotely
job = serverless.run("My-Qiskit-Pattern")
```
has changed to
```
# Run pattern remotely
pattern = serverless.get("My-Qiskit-Pattern")
pattern.run()
```

**Comment by abbycross** [comment]
Thank you @akihikokuroda!

**Comment by jenglick** [comment]
@akihikokuroda I believe we also need to update `QiskitPattern` to `QiskitFunction` on that page as well. Could you check that?

**Comment by akihikokuroda** [comment]
@jenglick You are right.  Those 2 lines have to be changed, too.
