### ISSUE TITLE
tables suck

### ISSUE THREAD

**Issue by beckykd** [Qiskit/documentation#1530]
### URL to the relevant documentation

https://qiskit-docs-preview-pr-1499.1799mxdls7qz.us-south.codeengine.appdomain.cloud/run/runtime-options-overview#options-classes

### Please describe the UI problem.

As Jessie pointed out in this PR (https://github.com/Qiskit/documentation/pull/1499#issuecomment-2160954530), with a wide screen, the text (and table) doesn't get wider; you just get a lot of white space.  Would it be possible to allow the content area to be wider for a wider screen?  The problem in this case is that there's a hidden column in the table and a Mac doesn't show a scroll bar; so you don't even know there's more content.   I've hit this issue many times. 

Here's the preview:  https://qiskit-docs-preview-pr-1499.1799mxdls7qz.us-south.codeengine.appdomain.cloud/run/runtime-options-overview#options-classes 

![image](https://github.com/Qiskit/documentation/assets/66339736/6e88aacb-b5af-4729-abc4-1894adeb0b1f)

**Comment by javabster** [comment]
example of annoying table scroll: https://docs.quantum.ibm.com/run/configure-error-mitigation#advanced-resilience-options-v1-primitives

**Comment by gracelindsell** [comment]
@Eric-Arellano to make Tables more visible, we should add Border-Subtle-00 to the border of the table.

**Comment by Eric-Arellano** [comment]
This is now live. Thanks @gracelindsell!

![image](https://github.com/user-attachments/assets/1aabf646-85a5-4dc3-a425-ddd9994025f9)

For now, we're not adding a permanent scrollbar because it goes against OS defaults. We can revisit if people still find tables confusing.
