### ISSUE TITLE
incomplete sentence due to conversion script

### ISSUE THREAD

**Issue by dr-kinder** [Qiskit/documentation#1534]
### URL to the relevant documentation

https://docs.quantum.ibm.com/api/qiskit/0.42/qiskit.transpiler.preset_passmanagers.generate_preset_pass_manager

### Select all that apply

- [X] typo
- [ ] code bug
- [ ] out-of-date content
- [ ] broken link
- [ ] other

### Describe the fix.

The second sentence describing this method ends abruptly.  There should be more ...

> This function provides a convenient and simple method to construct a standalone [PassManager](https://docs.quantum.ibm.com/api/qiskit/0.42/qiskit.transpiler.PassManager) object that mirrors what the transpile

**Comment by Eric-Arellano** [comment]
@arnaucasau can this be closed?

**Comment by arnaucasau** [comment]
I was waiting until we have the sync to closed source done, but the issues were fixed, so it can be closed :+1:
