### ISSUE TITLE
Add links to release notes to every page in intro paragraph

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#1538]
Request from product:

In the intro to every tools page (so not workflow pages) we should include a link to the latest release notes for the tools that are used in that page. So e.g. the circuit library page should include a link to the latest qiskit sdk release notes somewhere in the intro paragraph. 

The goal of this work is to address feedback that users don't know the details of what's been included in the latest release

**Comment by beckykd** [comment]
See PR #1782 for thoughts.

**Comment by javabster** [comment]
This will be addressed by a broader revamp of announcements in platform
