### ISSUE TITLE
Some pages in the preview do not render

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/documentation#1551]
Some pages in the documentation PR previews are not rendering, for example `/run/dynamic-circuits-considerations`:

<img width="1171" alt="Screenshot 2024-06-14 at 16 44 26" src="https://github.com/Qiskit/documentation/assets/36071638/9248f4af-cbdc-475b-866b-4542b4296809">

**Comment by frankharkins** [comment]
I don't think this was caused by the most recent docker image deploy as previews created before the most recent deploy also have the same problem: https://qiskit-docs-preview-pr-1507.1799mxdls7qz.us-south.codeengine.appdomain.cloud/build/interoperate-qiskit-qasm3

**Comment by Eric-Arellano** [comment]
> I don't think this was caused by the most recent docker image deploy as previews created before the most recent deploy also have the same problem:

Note that every PR was updated to use the new docker image, i.e. the "preview" app rather than full web app. To see if it works with the web app, you'd need to use the `:latest` tag in `Dockerfile` rather than `:open-source`, but that should only be done locally and not in CI.
