### ISSUE TITLE
incorrect local host url when running creating website's container

### ISSUE THREAD

**Issue by arujjval** [Qiskit/documentation#1561]
### Select all that apply

- [ ] typo
- [ ] code bug
- [ ] out-of-date content
- [X] broken link
- [ ] other

### Describe the fix.

I started the container of the website using docker and got this 
![Screenshot from 2024-06-16 07-37-21](https://github.com/Qiskit/documentation/assets/106719640/84770f16-0290-4b36-b35f-157b2d381077)
the link to the local is incorrect, the correct one is http://localhost:3000/ which is mentioned correctly in the readme, but here it is incorrect.

**Comment by Eric-Arellano** [comment]
Thanks for opening this up! I agree this is confusing. I've opened up a change in the closed source repository that will fix this. I'll update the issue when it's fixed.

**Comment by Eric-Arellano** [comment]
This is now fixed after running `docker pull qiskit/documentation`

```
❯ ./start     
Warning: this may be using an outdated version of the app. Run `docker pull qiskit/documentation` to check for updates.
  ▲ Next.js 14.2.3
  - Local:        http://localhost:3000
  - Network:      http://0.0.0.0:3000

 ✓ Starting...
```
