### ISSUE TITLE
Overview of V2 `PrimitiveResult` and associated result objects

### ISSUE THREAD

**Issue by kaelynj** [Qiskit/documentation#1565]
### URL, if applicable

Add a new section to https://docs.quantum.ibm.com/run/visualize-results to go over extracting results.

Add a new section to https://docs.quantum.ibm.com/run/advanced-runtime-options to go over what data is returned in the `DataBin` for the corresponding runtime  options.

### Describe the new content you are requesting.

The result data returned by the Estimator primitive once a job has completed contains a variety of data depending on the error mitigation options.  For example, when using ZNE, the `PubResult`and `PrimitiveResult` objects returned possess extrapolated expectation values, noise factors used, metadata about the learned noise model, among other things.

The documentation on how this is organized is fairly sparse, including in the API documentation. This (I assume) is partly due to the fact that the underlying `DataBin` objects possess different values depending on the runtime options specified for the job(s). I think we should add the following

- [ ] An explanation of the relationship between `PrimitiveResult`, `PubResult`, and the `DataBin` objects
- [ ] A table or something similar depicting the corresponding (meta)data that gets included in the `DataBin` for the various runtime options available.

### If this new content request is accepted, do you want to write the content?

I will write a draft of the proposed content

**Comment by javabster** [comment]
After team dicsussion, we think this should be combined with #1566 in a single new page that lives in the primitives subsection
