### ISSUE TITLE
Dynamical decoupling listed under error mitigation

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/documentation#1569]
### URL to the relevant documentation

https://docs.quantum.ibm.com/run/error-mitigation-explanation#dynamical-decoupling

### Select all that apply

- [ ] typo
- [ ] code bug
- [ ] out-of-date content
- [ ] broken link
- [X] other

### Describe the fix.

dynamical decoupling is an error suppression technique, not mitigation

**Comment by abbycross** [comment]
Thanks @nonhermitian for opening the issue. We're going to update the page title.
