### ISSUE TITLE
Create a "how to create a provider" based on Target+Primitives

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/documentation#1584]
### Describe the new content you are requesting.

Qiskit is moving towards a less backend centric architecture, where hardware definition is done via `Target` and execution models are via primitives. All this needs a deep explanation for new providers.

(FYI, BackendV2 will still continue being supported for some major versions to come)

### If this new content request is accepted, do you want to write the content?

I only want to review the material when it's finished

**Comment by javabster** [comment]
cc @tmittal947
