### ISSUE TITLE
Incorrect specification of inner product in Phase-Estimation and Factoring lecture of Fundamentals of Quantum Algorithms

### ISSUE THREAD

**Issue by harrylippy** [Qiskit/documentation#1591]
### URL to the relevant documentation

https://learning.quantum.ibm.com/course/fundamentals-of-quantum-algorithms/phase-estimation-and-factoring

### Select all that apply

- [ ] typo
- [ ] code bug
- [ ] out-of-date content
- [ ] broken link
- [X] other

### Describe the fix.

The inner product equation is wrong. The value should be 1 for y = z, and 0 for y != z in the "Unitarity" section.
![phase-estimation-error](https://github.com/Qiskit/documentation/assets/81269900/5c3d9414-6002-49e3-ac51-af9016d303d3)

Screenshot attached.

**Comment by harrylippy** [comment]
@abbycross here is another bug for the Quantum Learning team. Thanks for all your help redirecting these!

**Comment by Eric-Arellano** [comment]
This is now fixed. Thank you @harrylippy for reporting this! It's a huge help.
