### ISSUE TITLE
two headers both called "default configurations" on Representing quantum computers for the transpiler page

### ISSUE THREAD

**Issue by abbycross** [Qiskit/documentation#1609]
Investigate and adjust this (see https://docs.quantum.ibm.com/transpile/representing_quantum_computers#default-configuration)

**Comment by abbycross** [comment]
@kaelynj were you one of the original authors? This file has changed file formats so we may have lost the original intention for the first two sections along the way. Do you have a recommendation on the right way to fix -- would we, for example, remove the first `Default configuration` header, or change it to something else?

**Comment by javabster** [comment]
update: remove 2nd heading, adjust paragraph to talk more generally about the defaults. 

also remove "(Note that if a target is specified in the transpile function, this will override the target from the backend.)"
