### ISSUE TITLE
Error in General Formulation of Quantum Information course - Density matrices unit

### ISSUE THREAD

**Issue by harrylippy** [Qiskit/documentation#1618]
URL to relevant documentation: https://learning.quantum.ibm.com/course/general-formulation-of-quantum-information/density-matrices

In "The completely mixed state" subsection, there is an error in the probability specifications for the state |1>. Screenshot attached, with error circled and an arrow indicating where the error is corrected just below the error in the text.

![error-density-matrix-1](https://github.com/Qiskit/documentation/assets/81269900/07d9a730-1732-499f-8d04-b31ea9411a11)

ERROR:

If the state is |1>, we obtain the outcomes 0 and 1 with probabilities

    |<0|U|1>|^2 and |<1|U|0>|^2

CORRECTION:

If the state is |1>, we obtain the outcomes 0 and 1 with probabilities

    |<0|U|1>|^2 and |<1|U|1>|^2

**Comment by harrylippy** [comment]
@abbycross Here is another issue from Quantum Learning, if you could pass it on. Thanks!

**Comment by abbycross** [comment]
Sending it along now!

**Comment by jhwatrous** [comment]
Fixed. Thank you!
