### ISSUE TITLE
Error in Bloch Sphere portion of "Density matrices" module in "General Formulation of Quantum Information" course

### ISSUE THREAD

**Issue by harrylippy** [Qiskit/documentation#1619]
### URL to the relevant documentation

https://learning.quantum.ibm.com/course/general-formulation-of-quantum-information/density-matrices

### Select all that apply

- [ ] typo
- [ ] code bug
- [ ] out-of-date content
- [ ] broken link
- [X] other

### Describe the fix.

In the third paragraph of the section, I believe there is an error when specifying the psi vector in the case where θ = π. Screenshot attached.
![Screenshot_20240630_084438_Chrome](https://github.com/Qiskit/documentation/assets/81269900/74b67d94-2e4e-442c-a7a5-675ad17444f1)

INCORRECT:

Similarly, if θ = π, then we have |ψ> = e^((-φ)|1>

CORRECT:

Similarly, if θ = π, then we have |ψ> = e^(iφ)|1>

**Comment by abbycross** [comment]
Hi @harrylippy, thanks for submitting an issue! The learning/course content belongs to a different team and I will forward this to them.

**Comment by jhwatrous** [comment]
Thank you @harrylippy, much appreciated — this is fixed now.
