### ISSUE TITLE
Incorrect Hamiltonian for max cut problem graph in `Variational Algorithm Design` badge

### ISSUE THREAD

**Issue by GuillermoAbadLopez** [Qiskit/documentation#1623]
### URL to the relevant documentation

[Max cut problem in `Ansatze and Variational Forms` of the `Variational Algorithm Design` badge](https://learning.quantum.ibm.com/course/variational-algorithm-design/ansatze-and-variational-forms#optimization)

### Select all that apply

- [X] typo
(typo but in IBM Quantum Learning)

-----

# Problem

Hey! I was doing the [Variational Algorithm Design badge](https://learning.quantum.ibm.com/course/variational-algorithm-design), from IBM Quantum learning, and I noticed that in [the max-cut problem](https://learning.quantum.ibm.com/course/variational-algorithm-design/ansatze-and-variational-forms#optimization), the SparsePauliOp that is given as a Hamiltonian, looked a bit off:

(notice the Z's positions in each term [from right to left], indicate an edge (the connectivity) between two nodes:
`IIZZ` means there are 4 qubits, and that qubit 0 is connected to qubit 1)

<img width="704" alt="Screenshot 2024-07-01 at 18 49 07" src="https://github.com/Qiskit/documentation/assets/109400222/cde19e05-135a-40a5-b34c-e347a9463ab4">

## Possible origin of the Problem

I think this comes from a copypaste from [this other graph in another page](https://learning.quantum.ibm.com/tutorial/quantum-approximate-optimization-algorithm#step-1-map-classical-inputs-to-a-quantum-problem), where its actually correct (different graph)

<img width="607" alt="Screenshot 2024-07-01 at 18 52 03" src="https://github.com/Qiskit/documentation/assets/109400222/50294344-8123-4b84-b320-b2868a94bca8">

------ 

# Solution
 This `IIIZZ+IIZIZ+IZIIZ+ZIIIZ`, has to change into `IIZZ+IZIZ+IZZI+ZIIZ+ZZII`, both in:
 - [x] the text
 - [x] and in the code-block under
 
(or the graph image has to change, but that would be weird, since in the next page we use it...)
 
## Checks:
I searched a bit, and found this [old documentation, from Qiskit textbook](https://qiskit-community.github.io/qiskit-optimization/tutorials/06_examples_max_cut_and_tsp.html#Max-Cut-problem), which has what I would have guessed is correct:

<img width="607" alt="Screenshot 2024-07-01 at 18 06 41" src="https://github.com/Qiskit/documentation/assets/109400222/96f1e19d-9a51-4b5a-a72c-26d341ddc7e6">

Also, a bit later, I arrived at the [next page of the Badge (Cost Functions)](https://learning.quantum.ibm.com/course/variational-algorithm-design/cost-functions#example-mapping-to-non-physical-systems), and there it was correctly written as well:

![image](https://github.com/Qiskit/documentation/assets/109400222/2d30db02-6a4f-4a53-ac59-86c2b8a862f7)

**Comment by GuillermoAbadLopez** [comment]
Opening the Issue here, since I didn't know where else to open it,
 and @Eric-Arellano told me to do it, and that he would tag the relevant people 👍

**Comment by GuillermoAbadLopez** [comment]
@Eric-Arellano I see the Issue has already been addressed by your colleagues!
(Who I never got to know, sadly 😢)

<img width="519" alt="Screenshot 2024-07-17 at 16 42 34" src="https://github.com/user-attachments/assets/a404499e-f535-4838-a5e9-2ea1e61e1786">

Should we then, close this Issue, as it is resolved?

**Comment by Eric-Arellano** [comment]
Great, thanks!
