### ISSUE TITLE
[ NEW PAGE ] Write your first serverless program

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#1640]
Headings this page should include:
- Basic local example — with custom dependency, and inputs
- Wrap a local example to run remotely on Qiskit Serverless
- Add custom dependencies to your workload
- Deploy a Qiskit Serverless workload

You should re-use content from these pages:
- [Running a remote workload](https://docs.quantum.ibm.com/run/quantum-serverless#run-a-qiskit-pattern-remotely-on-qiskit-serverless)
- [Running and deploying a Qiskit Pattern as a function](https://qiskit.github.io/qiskit-serverless/getting_started/basic/01_running_program.html)
- [Passing input arguments to your Qiskit Function](https://qiskit.github.io/qiskit-serverless/getting_started/basic/02_arguments_and_results.html)
- [Using python packages with your QiskitPattern](https://qiskit.github.io/qiskit-serverless/getting_started/basic/03_dependencies.html)

**Comment by abbycross** [comment]
Was closed by #1783
