### ISSUE TITLE
[ NEW PAGE ] Manage data and compute resources

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#1642]
headings to include in this page:
- Parallel workflows
- Automated backend selection
- Manage data

you should use content from these existing pages:
- [Resource Management (alpha)](https://docs.quantum.ibm.com/run/quantum-serverless#resource-management-alpha)
- [Parallel workflows in QiskitPatterns](https://qiskit.github.io/qiskit-serverless/getting_started/basic/04_distributed_workloads.html)
- [File download](https://qiskit.github.io/qiskit-serverless/getting_started/experimental/file_download.html)
- [Shared data directory](https://qiskit.github.io/qiskit-serverless/getting_started/experimental/manage_data_directory.html)

**Comment by abbycross** [comment]
Closed by #1783
