### ISSUE TITLE
update patterns pages to reference serverless

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#1645]
Once the serverless docs have been refactored and the component has been included in the patterns diagram it would be good if we could link out to these pages from the patterns index pages. Not sure exactly what the best way to do this would be, maybe include it just in the first "intro to patterns" page? 

NOTE: the intro pages should be sure to mention the connection with quantum centric supercomputing (@tmittal947 can advise on how to do this best)

**Comment by abbycross** [comment]
Being addressed in https://github.com/Qiskit/documentation/pull/1783

**Comment by abbycross** [comment]
We now link out to the Serverless docs from the intro to patterns page. @javabster which intro pages do you mean, when you say "the intro pages should be sure to mention the connection with quantum centric supercomputing"? I believe that's still an outstanding to-do on this - do we still need input from @tmittal947 for it?
