### ISSUE TITLE
Hello world video includes deprecated code

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/documentation#1661]
### URL to the relevant documentation

https://docs.quantum.ibm.com/guides/hello-world

### Select all that apply

- [ ] typo
- [ ] code bug
- [X] out-of-date content
- [ ] broken link
- [ ] other

### Describe the fix.

The hello world video includes Runtime code that is deprecated, and is to be removed at some point, e.g. `service.get_backed`.

**Comment by shraddha-aangiras** [comment]
Hello! How can we go about this: do we mention the deprecation on the documentation page, or should it be added somewhere in the video's description? I'm interested in working on this issue if I can!

**Comment by javabster** [comment]
I've notified the YouTube squad to see if theres a way we can update the video itself, if not we'll need to add a note below the video on the page. In the meantime @shraddha-aangiras could you check through the rest of the docs pages to see if there is anywhere we are using `get_backend` and replace it with `backend`. I think for the most part we only use `least_busy` but there may be a few we've missed
