### ISSUE TITLE
Re-design docs homepage to feature qiskit 1.0 more

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#1663]
redesign the api referene tile components based on tushar's feedback:

The main point I think that should be put across here is the there are multiple API references associated with a single product. E.g. Qiskit Runtime is the product but there are 2 api refs associated with it. Same for the transpiler service. Qiskit SDK only has one api ref though

<img width="1395" alt="Screenshot 2024-07-08 at 10 29 08 AM" src="https://github.com/Qiskit/documentation/assets/23662430/d9848ac7-835e-42e9-a00e-084b8827f8d3">
<img width="1390" alt="Screenshot 2024-07-08 at 10 28 59 AM" src="https://github.com/Qiskit/documentation/assets/23662430/8fd74e45-a7fb-4f94-a8a7-9d9396b2acb7">

**Comment by gracelindsell** [comment]
@Eric-Arellano Designs for the homepage are complete and can be found [here](https://www.figma.com/design/sNXucK1uMaZ8XXyLTZrdrs/IBM-Quantum-Documentation?node-id=7138-51274&t=5iRWyCVqIs2AvIAt-1)

**Comment by Eric-Arellano** [comment]
Tracking implementation in closed source. Thanks, Grace!
