### ISSUE TITLE
Example code in Migrate to Qiskit Runtime is not functional

### ISSUE THREAD

**Issue by austingmhuang** [Qiskit/documentation#1667]
### URL to the relevant documentation

In both [here](https://docs.quantum.ibm.com/api/migration-guides/qiskit-runtime-from-ibmq-provider) and [here](https://docs.quantum.ibm.com/api/migration-guides/qiskit-runtime-from-ibm-provider#save-accounts) we get this line of code 
```
from qiskit_ibm_runtime import QiskitRuntimeService
 
# IBM Quantum channel; set to default 
 
QiskitRuntimeService.save_account(channel="ibm_quantum", token="<IQP_TOKEN>", overwrite=True, default=true)
```

which does not run at all. 

### Select all that apply

- [ ] typo
- [X] code bug
- [ ] out-of-date content
- [ ] broken link
- [ ] other

### Describe the fix.

Should be

`QiskitRuntimeService.save_account(channel="ibm_quantum", token="<IQP_TOKEN>")` instead.

**Comment by abbycross** [comment]
Thank you @austingmhuang for flagging this! The `overwrite=True` should work just fine, but `default` has errors, which I will open a PR to fix. It should be `set_as_default=True`
