### ISSUE TITLE
Duplicate headers for overloaded methods

### ISSUE THREAD

**Issue by kevinsung** [Qiskit/documentation#167]
### URL to the relevant documentation

https://docs.quantum-computing.ibm.com/api/qiskit/qiskit.circuit.QuantumCircuit

### Please describe the UI problem.

For example, look at the right sidebar:
![image](https://github.com/Qiskit/documentation/assets/4296166/43e1dec7-525d-4559-9f0b-84e2129a130e)

Each Example and Notes section should have the most indentation, but they have the least. Also, there are duplicates like `if_test` that show up with the same indentation.

**Comment by Eric-Arellano** [comment]
@frankharkins fixed the bad `Example` headers in https://github.com/Qiskit/documentation/pull/683. But the issue with duplicate headers remains. This is specifically when methods are overloaded, and probably also when functions or exceptions are overloaded; like they have multiple signatures. https://docs.quantum.ibm.com/api/qiskit/qiskit.circuit.QuantumCircuit#if_test is a good example

I renamed the issue title to focus on that problem.
