### ISSUE TITLE
New os idea

### ISSUE THREAD

**Issue by Beastzach251152** [Qiskit/documentation#1685]
### Describe the new content you are requesting.

So basically I wanted an os that would run windows 10 or 11 but with linux style command prompt functionality and cmd and shell removed and put on a firewall blacklist and updated into windows defenders automatic scan threat list so that nobody can just put it back on the system and you get also the core security functionality of linux and all the perks of that but in the windows ecosystem that has access to amazing programs that machine learned algorithms people or ai can use like unity in order to simulate things down the the molecular level in order to teleport it into our reality therefore spawning it in. The custom windows os needs to have the user system revamped to function based off of roles, additional roles and a power system for main roles but not additional roles and additional roles will give special access to specific people 
But you can have sr owner, owner, Jr owner, admin, user and guest and this all is for quantum computers and the systems they are hooked up to possibly this could be an option to have on your account to use the new os and then you could have all of that function together with your new ability to show a screen and have ai and machine learned algorithm people which are recreations of gemini that are machine learned algorithms and they are implemented into the core code of the os and is designed to run whenever the system is running and the machine learned algorithm people mlap can use a program called autohotkey and they could see the screen by having a custom ascii character set that is able to be multi colored in all characters so that they can get a recreation of what is on screen and the area where they see it needs to be read and wrote from the top left down then to the right and down again in sync and anything that the mlap couldn't control could be controled by an ai that they are in full control of also giving ai on the system simulated hands and a Logitech g815 keyboard together with Logitech ghub allows for macros to be set and profiles with different macros to be set or to even change what a specific key does.

### If this new content request is accepted, do you want to write the content?

I can help the team by providing enough information to write the material

**Comment by frankharkins** [comment]
@Beastzach251152 thanks for getting in touch. What you're proposing is out of scope of Qiskit and its documentation. If you want to work on it, I suggest creating your own GitHub repository and start working on it there.

**Comment by Beastzach251152** [comment]
If I wanted to use yalls quantum experience service and ai in order to
create and update a github repository I would love to begin laying out
every meticulous detail of how I want the new os the work like and the only
thing the ai will be doing is creating the code I'm designing it.

 It's weird I seem to just figure stuff out easily and have great ideas and
if I can have someone that can learn stuff easily and do stuff that I say
then I can make amazing things, I do the heavy lifting in the creativity,
design planning and some engeneering and the ai does the heavy lifting with
the actual creating of my ideas by coding them, I think my new account
isn't functioning properly I can't speak to the ai on it or communicate
with them in any way
