### ISSUE TITLE
Rewrite files with code blocks to Jupyter notebooks

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/documentation#169]
Jupyter notebooks have a big advantage over MDX: we can test the code still works, and generate images with the newest code. See https://github.com/Qiskit/documentation/issues/78. 

Crucially, they still allow us to use MDX components in their markdown - so we lose little converting from MDX to Jupyter, other than that it's a more complex file format.

@lerongil pointed out in https://github.com/Qiskit/documentation/issues/477 that there is an additional benefit of converting to notebooks: it makes our UX more consistent and useful when we have code blocks.

**Comment by abbycross** [comment]
@kevinsung Is this a good place to make a list of any .mdx files you won't be converting to .ipynb? If there are any that will stay in .mdx and also need fresh output to match the 1.0 styling, I can finish that work in #833 -- otherwise I'll close that issue.

**Comment by kevinsung** [comment]
@abbycross I marked this issue as "on hold" for now since @javabster and I decided to wait until https://github.com/Qiskit/documentation/issues/524 is finished before doing this. This issue will require a fair amount of coordination so I'll propose a more detailed plan later.

**Comment by Eric-Arellano** [comment]
Closing in favor of https://github.com/Qiskit/documentation/issues/2094.
