### ISSUE TITLE
Nit in `set-optimization`

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/documentation#1694]
Recommendations says

> To learn how to use the `transpile` function, start with the [Transpilation default settings and configuration options](https://docs.quantum.ibm.com/guides/defaults-and-configuration-options) topic.

but the linked page doesn't use `transpile`

**Comment by javabster** [comment]
we should remove any text referring to the `transpile()` function and talk about `generate_preset_passmanager` instead
