### ISSUE TITLE
[ NEW PAGE ] add pages to additional resources tab

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#1698]
The additional resources tab should have the following structure:

- migration guides
- open-source resources
    - Contributor License Agreements
         - individual
         - corporate
    - Qiskit SDK
         - version strategy
         - contributor guide (external link to github)
         - deprecation policy (external link to github)
- Responsible quantum computing
~- FAQs~

This issue is to track moving all the content to the appropriate place. In particular:
- version strategy content should be moved from [here ](https://docs.quantum.ibm.com/guides/install-qiskit#qiskit-versioning)to a dedicated page, and instead of the expandable dropdowns it should have proper H2 headings
~- the FAQs should be moved from the support page to a dedicated page, and instead of the expandable dropdowns it should have proper H2 headings~

**Comment by abbycross** [comment]
FYI - confirmed with @Eric-Arellano that migration guides will not move until phase two of the Additional Resources tab work.
