### ISSUE TITLE
Update options dictionary structure as needed

### ISSUE THREAD

**Issue by beckykd** [Qiskit/documentation#1729]
### URL to the relevant documentation

 DeprecationWarning: Specifying options without the full dictionary structure is deprecated as of qiskit-ibm-runtime 0.24.0 and will be removed no sooner than 3 months after the release date. Instead, pass in a fully structured dictionary. For example, use {'environment': {'log_level': 'INFO'}} instead of {'log_level': 'INFO'}.
  estimator = Estimator(backend, options={"init_qubits": False})

### Select all that apply

- [ ] typo
- [ ] code bug
- [X] out-of-date content
- [ ] broken link
- [ ] other

### Describe the fix.

Check for code like this: 

estimator = Estimator(backend, options={"optimization_level": 0})

Update it like this: (resilience_level is a first level option; measure_mitigation is a lower-level) 

estimator = Estimator(backend, options={'resilience_level': 2,'resilience': {'measure_mitigation': False}})

**Comment by javabster** [comment]
todo: speak to @frankharkins about how we can catch this with cron job testing

**Comment by beckykd** [comment]
I ran all the rest of the code and didn't find any others with the deprecated styling.
