### ISSUE TITLE
Improve Primitive Introduction Pages

### ISSUE THREAD

**Issue by kaelynj** [Qiskit/documentation#1733]
### URL, if applicable

https://docs.quantum.ibm.com/guides/primitives

### Describe the new content you are requesting.

Our introduction to primitives page at this point reads more like a migration guide rather than a proper introduction to the concept and usage of primitives. I'd suggest we reorganize the content in here (or perhaps incorporate the content included being created in #1566 once that's done).

### If this new content request is accepted, do you want to write the content?

I will write a draft of the proposed content

**Comment by beckykd** [comment]
Can you also add that Sampler requires circuit measurements?

**Comment by kaelynj** [comment]
Will check the current status of this issue given that #1809  has been closed.

**Comment by kaelynj** [comment]
Ok looking over the updated page, I just have a few tweaks I'd like to add in that I'll list here for me to keep track:

- [ ] Rework the intro section to provide an initial definition of the Sampler and Estimator primitive before moving on to discussing where they are defined/implemented (or just add links to their section to draw the eyes more).
- [ ] Move 'Benefits of Qiskit Primitives' to just below intro section.
- [ ] Explain more about the relationship between the `qiskit` implementations of the primitives and the Qiskit Runtime service.
