### ISSUE TITLE
Spelling cleanup

### ISSUE THREAD

**Issue by abbycross** [Qiskit/documentation#1778]
As seen in the spellcheck linter - some need to be added to the dictionary and "unti" needs to be fixed in the code.
<img width="345" alt="Screenshot 2024-07-29 at 4 11 54 PM" src="https://github.com/user-attachments/assets/001c7db1-02c6-4309-b276-922192d1b2c0">

**Comment by Eric-Arellano** [comment]
This is because closed source is out-of-sync with open source. I have a TODO to sync the open source config to closed source.

**Comment by Eric-Arellano** [comment]
Closed source PR is up for review and fixes it so that there are zero errors.
