### ISSUE TITLE
Update requirements and add serverless

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/documentation#1784]
We should update our dependencies and add Qiskit Serverless to test the notebooks added in https://github.com/Qiskit/documentation/pull/1783. We'll need to check the dependencies update doesn't break anything.

**Comment by Eric-Arellano** [comment]
@frankharkins do we still need to set the env var for authentication with Serverless?

**Comment by frankharkins** [comment]
Actually I don't think we do, looks like it detects and uses the `qiskit-ibm-runtime` details which we already save. See [`IBMServerlessClient.__init__`](https://qiskit.github.io/qiskit-serverless/_modules/qiskit_serverless/core/client.html#IBMServerlessClient.__init__).
