### ISSUE TITLE
Remove Qiskit IBM Provider API reference

### ISSUE THREAD

**Issue by jyu00** [Qiskit/documentation#1797]
### URL to the relevant documentation

https://docs.quantum.ibm.com/api/qiskit-ibm-provider/ibm_provider

### Select all that apply

- [ ] typo
- [ ] code bug
- [X] out-of-date content
- [ ] broken link
- [ ] other

### Describe the fix.

`qiskit-ibm-provider` was deprecated earlier this year and has since been archived. Its API reference page should be removed since it's no longer supported.

**Comment by Eric-Arellano** [comment]
We should set up a custom 404 error page that has links to the migration guide https://docs.quantum.ibm.com/migration-guides/qiskit-runtime-from-ibm-provider

**Comment by frankharkins** [comment]
@jyu00 will users still be able to retrieve old jobs using the Qiskit IBM Provider package? If not, is there another way they could do that?

**Comment by jyu00** [comment]
> @jyu00 will users still be able to retrieve old jobs using the Qiskit IBM Provider package? If not, is there another way they could do that? Just working out what to say in the docs on getting old jobs.

Kind of. `qiskit-ibm-provider` uses Qiskit Runtime, so users can continue to use it or `qiskit-ibm-runtime` to retrieve old jobs submitted by `qiskit-ibm-provider`. 

However, jobs submitted by `qiskit-ibmq-provider` (notice the extra `q`), which was deprecated 2 years ago, can only be retrieved by `qiskit-ibm-provider` (for now anyway, I believe IQP plans to disable that path entirely).
