### ISSUE TITLE
Upcoming removal of V1 primitive support

### ISSUE THREAD

**Issue by jyu00** [Qiskit/documentation#1802]
### Describe the new content you are requesting.

We plan to drop V1 primitives support on Aug 15. Various pages will need to be cleaned up to remove V1 reference. 

### If this new content request is accepted, do you want to write the content?

I can help the team by providing enough information to write the material

**Comment by Eric-Arellano** [comment]
For legacy users who have not yet migrated, will the V1 migration guide be sufficient for them? I'm wondering how we can make the migration path smoother since not everyone will upgrade immediately.

**Comment by jyu00** [comment]
The migration guide should be sufficient. At least I haven't heard any feedback about it being inadequate. The biggest complaint I heard was that Qiskit application modules, which are no longer maintained by IBM, were not updated to use V2. But there's little we can do besides reaching out to the maintainers. 

Having said that, if you have ideas to help people make the transition, please feel free to share!

**Comment by beckykd** [comment]
> The migration guide should be sufficient.

Notably, most of the examples that are in the regular guides are in the migration guide.
