### ISSUE TITLE
Remove reference to qiskit-ibm-provider

### ISSUE THREAD

**Issue by jyu00** [Qiskit/documentation#1819]
### URL to the relevant documentation

https://qiskit.github.io/documentation/pr-1809/guides/instances#connect-to-an-instance is an example, but there are probably others

### Select all that apply

- [ ] typo
- [ ] code bug
- [X] out-of-date content
- [ ] broken link
- [ ] other

### Describe the fix.

`qiskit-ibm-provider` was archived on July 24, and any reference to it should be removed.

**Comment by abbycross** [comment]
Thanks @jyu00! Do we also remove the [migration guide](https://docs.quantum.ibm.com/migration-guides/qiskit-runtime-from-ibm-provider) at this time, or keep it around for now?

**Comment by abbycross** [comment]
Is it ok to keep this bit as-is, since it is referring to jobs run in the past using qiskit ibm provider?

<img width="866" alt="Screenshot 2024-08-14 at 1 58 35 PM" src="https://github.com/user-attachments/assets/a0ce7cfc-2106-4d48-9e4c-f7fab3ad74b0">

**Comment by Eric-Arellano** [comment]
> Do we also remove the [migration guide](https://docs.quantum.ibm.com/migration-guides/qiskit-runtime-from-ibm-provider) at this time

I'd advocate for _always_ keeping the migration guide. It's not hurting anyone because it's clear it's not relevant to most. It's useful for people who are revisiting quantum 1+ years after their last foray.

**Comment by jyu00** [comment]
Yeah I also think we should keep the migration guide, especially since `qiskit-ibm-provider` was "only" archived in July. We can keep the job retrieval too, but maybe mention it's deprecated and link to the migration guide.
