### ISSUE TITLE
Bug in serverless page

### ISSUE THREAD

**Issue by jyu00** [Qiskit/documentation#1828]
### URL to the relevant documentation

https://docs.quantum.ibm.com/guides/qiskit-serverless#run-a-qiskit-pattern-remotely-on-qiskit-serverless

### Select all that apply

- [ ] typo
- [X] code bug
- [ ] out-of-date content
- [ ] broken link
- [ ] other

### Describe the fix.

The code example is missing a `job = `, e.g.  it should be 

```python
# Run pattern remotely
pattern = serverless.get("My-Qiskit-Pattern")
job = pattern.run()
 
# Retrieve status, logs, results
job.status()
job.logs()
job.result()
```

Otherwise it'd fail with `name job not found`

**Comment by jyu00** [comment]
cc @pandasa123, @jenglick

**Comment by abbycross** [comment]
The docs are being overhauled [in an open PR](https://github.com/Qiskit/documentation/pull/1783), and this code no longer exists as it was - if it still needs fixing in the docs being worked on in this PR, please let me know @pandasa123 @jyu00
