### ISSUE TITLE
Serverless page should mention it's using the same account file

### ISSUE THREAD

**Issue by jyu00** [Qiskit/documentation#1829]
### URL to the relevant documentation

https://docs.quantum.ibm.com/guides/qiskit-serverless

### Select all that apply

- [ ] typo
- [ ] code bug
- [ ] out-of-date content
- [ ] broken link
- [X] other

### Describe the fix.

The code example on this page has 

```python
serverless = IBMServerlessClient("YOUR_IBM_QUANTUM_TOKEN")
```

It should mention that you can use `save_account()` to save the account credential. More importantly, if you do use `save_account`, it uses the same file as `QiskitRuntimeService.save_account()`! People may inadvertently overwrite that file if they don't know both services use the same one. 

cc @pandasa123, @jenglick

**Comment by abbycross** [comment]
Addressing in https://github.com/Qiskit/documentation/pull/1783/commits/88dac2e3206c180d50f70ef754e2939f644b7daa

**Comment by abbycross** [comment]
Merged!
