### ISSUE TITLE
[ NEW PAGE ] Noise learning helper

### ISSUE THREAD

**Issue by kaelynj** [Qiskit/documentation#1830]
### Describe the new content you are requesting.

The newest version of runtime contains an experimental `NoiseLearner` feature for characterizing noise models that PEC and TREX consume. Some API docs for it exist already and they need a new page to give more detail/context on the feature's usage.

### If this new content request is accepted, do you want to write the content?

I will write a draft of the proposed content

**Comment by jyu00** [comment]
@javabster and @kaelynj, any updates on this? Noise learner was released 2 weeks ago.

**Comment by kaelynj** [comment]
Just pushed the PR for it! Feel free to look it over now.
