### ISSUE TITLE
Turn off `--no-progress` with CSpell?

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/documentation#1846]
https://github.com/Qiskit/documentation/pull/1837 would only report this:
```
CSpell: Files checked: 70, Issues found: 1 in 1 file.
```

Until I removed `--no-progress` from here:

https://github.com/Qiskit/documentation/blob/3c416e970400485cbf009e515e84f663cc52b819/scripts/js/commands/checkSpelling.ts#L47

```
-------------------------------------------
Issues found:
docs/guides/latest-updates.mdx:71:179 - Unknown word (Lindblad)
CSpell: Files checked: 70, Issues found: 1 in 1 file.
```

Why is that? Try to reproduce this in other situations. Worst case, we should remove `--no-spelling`, even though it makes things more noisy.

**Comment by beckykd** [comment]
I saw the same issue with my PR: https://github.com/Qiskit/documentation/actions/runs/10584022321/job/29327300044?pr=1882
