### ISSUE TITLE
Use of deprecated `BaseSamplerV1` in 'Basics of Quantum Information' course

### ISSUE THREAD

**Issue by anon1892** [Qiskit/documentation#1851]
### URL to the relevant documentation

https://learning.quantum.ibm.com/course/basics-of-quantum-information/quantum-circuits#quantum-circuits

In course 'Basics of Quantum Information' --> 'Quantum circuits'
In section 'Circuit' --> 'Quantum circuits'

### Select all that apply

- [ ] typo
- [ ] code bug
- [X] out-of-date content
- [ ] broken link
- [ ] other

### Describe the fix.

The last code sample of this section use 'BaseSamplerV1' which is deprecated and will be removed soon.
Code to be replaced : 
```python
results = Sampler().run(circuit).result()
statistics = results.quasi_dists[0].binary_probabilities()
display(plot_histogram(statistics))
```
And also the import code, in the begging of the same section.

**Comment by abbycross** [comment]
Thanks for bringing this to our attention @anon1892 - I am redirecting the issue to the Learning team to address.
