### ISSUE TITLE
Possible mistake in "Measuring in Pauli bases" section

### ISSUE THREAD

**Issue by kcmccormibm** [Qiskit/documentation#1855]
### URL to the relevant documentation

https://docs.quantum.ibm.com/guides/specify-observables-pauli

### Select all that apply

- [ ] typo
- [ ] code bug
- [ ] out-of-date content
- [ ] broken link
- [X] other

### Describe the fix.

I believe that measuring in the Y basis requires applying Sdg followed by a Hadamard, but the code cell on that page mixes up the order of these two gates.

**Comment by frankharkins** [comment]
Thanks for making an issue! I actually believe the existing is correct: We want to transform any Y-basis states to computational basis states ($|0\rangle$ & $|1\rangle$). Here's some Qiskit code to demonstrate.

```python
from qiskit import QuantumCircuit
from qiskit.quantum_info import Statevector

qc = QuantumCircuit(1)
qc.sdg(0)
qc.h(0)

y0 = Statevector.from_label("r")  # 0 in Y-basis
y0.evolve(qc) == Statevector.from_label("0")  # True

y1 = Statevector.from_label("l")  # 1 in Y-basis
y1.evolve(qc) == Statevector.from_label("1")  # True
```

**Comment by kcmccormibm** [comment]
Hi Frank, thanks for your response! 

Totally agree that the code you included above is correct. The problem I'm seeing online is that `qc.sdg(0)` and `qc.h(0)` are swapped, so that the code block above would be:

`from qiskit import QuantumCircuit
from qiskit.quantum_info import Statevector

qc = QuantumCircuit(1)
**qc.h(0)
qc.sdg(0)**


y0 = Statevector.from_label("r")  # 0 in Y-basis
y0.evolve(qc) == Statevector.from_label("0")  # True

y1 = Statevector.from_label("l")  # 1 in Y-basis
y1.evolve(qc) == Statevector.from_label("1")  # True`

This returns False.

**Comment by frankharkins** [comment]
🤦 sorry! You're right. Thanks for bearing with me.

**Comment by kcmccormibm** [comment]
Great, thank you!
