### ISSUE TITLE
Mention twirling options `num_randomizations` and `shots_per_randomization` in shots section

### ISSUE THREAD

**Issue by kt474** [Qiskit/documentation#1857]
### URL, if applicable

https://docs.quantum.ibm.com/guides/specify-runtime-options#shots-sampler-only

### Describe the new content you are requesting.

In the `shots` and `precision` section we should talk about the twirling options `num_randomizations` and `shots_per_randomization` because they can effect the number of shots used. 

If shots are passed in as an option `estimator.options.default_shots = shots` then the value passed in will be altered. This behavior is briefly mentioned in https://docs.quantum.ibm.com/api/qiskit-ibm-runtime/qiskit_ibm_runtime.options.TwirlingOptions

### If this new content request is accepted, do you want to write the content?

I can help the team by providing enough information to write the material

**Comment by beckykd** [comment]
I just updated this page, so I can work on this one.

**Comment by kt474** [comment]
Related to https://github.com/Qiskit/qiskit-ibm-runtime/pull/1884 

https://github.com/Qiskit/qiskit-ibm-runtime/blob/db76b9942534db2761f8a33de43d82be0a6ee481/qiskit_ibm_runtime/options/twirling_options.py#L44-L80
