### ISSUE TITLE
[DESIGN]: Indicate which files code snippets should go in

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/documentation#1861]
We often have code snippets that need to live in different files. It's pretty common to start these snippets with a comment naming the file it belongs to.

```python
# ../config.py
config = {}
```

This is a bit of a problem when testing, as it might not make sense to run the code top-to-bottom. To get round this, I've started using the `%%writefile` magic command to write those cells to a file. The notebook can then run a hidden command to check these files work correctly.

![Screenshot 2024-08-21 at 18 41 20](https://github.com/user-attachments/assets/0912a2e2-d7a8-4572-bc5f-6c9e4a453b00)

Since `%%writefile` is a bit ugly, it might be nice to detect when a cell starts with this command and make it look nicer. One option is to simply replace `%%writefile -> #` to get the old comment.

Another option is to add this information at the top of the code snippet component. I've also seen other websites do this.

For example, this code snippet in [Nuxt](https://nuxt.com/docs/guide/directory-structure/app) belongs in `app.vue`:
![Screenshot 2024-08-21 at 18 33 15](https://github.com/user-attachments/assets/aa1fca97-6cfd-4392-9569-ea7ea4efc54e)

Here's another example in [SvelteKit](https://kit.svelte.dev/docs/load):
![Screenshot 2024-08-21 at 18 47 41](https://github.com/user-attachments/assets/ece92678-b6ec-400b-9105-5ddcc4784e64)

Update: we decided to not worry about having a tab component like some other sites have, e.g. https://www.pantsbuild.org/2.21/docs/python/overview/third-party-dependencies#requirementstxt. The component only needs to handle at most one file name. There will still be many code blocks with no file name.

**Comment by Eric-Arellano** [comment]
@frankharkins Abby and I discussed this in backlog triage. We're wondering when/why you would use multiple files in a notebook? Grepping for `writefile` doesn't show up anything. It would help to better understand the motivating use case before deciding on next steps.

**Comment by frankharkins** [comment]
We have code cells that belong in different files in a couple of places across the docs (e.g. (configuration)[https://docs.quantum.ibm.com/guides/configure-qiskit-local#user-configuration-file] and (create a transpiler plugin)[https://docs.quantum.ibm.com/guides/create-transpiler-plugin]). We don't use `writefile` for testing there but the visual indicator would be helpful for users.

This situation appears a lot in the new serverless docs (#1783), which is what motivated this issue and is where I've been adding the `writefile` commands.

**Comment by gracelindsell** [comment]
Designs have been finalized and can be found [here](https://www.figma.com/design/sNXucK1uMaZ8XXyLTZrdrs/IBM-Quantum-Documentation?node-id=7521-50151&t=FaB38H8b7KCDP30f-1)
