### ISSUE TITLE
bug in Hello World documentation

### ISSUE THREAD

**Issue by hromadka** [Qiskit/documentation#1873]
### URL to the relevant documentation

https://docs.quantum.ibm.com/guides/hello-world

### Select all that apply

- [ ] typo
- [X] code bug
- [ ] out-of-date content
- [ ] broken link
- [ ] other

### Describe the fix.

in Step 3, change
`estimator = Estimator(mode=backend)'
to
'estimator = Estimator(backend=backend)'

**Comment by beckykd** [comment]
Hello 
@hromadka , thank you for opening this issue.  The correct usage is now `mode=backend`.  If this code is not working for you, please make sure you've upgraded to Qiskit Runtime .24 or later.
