### ISSUE TITLE
Implement contributor names on each guides page

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/documentation#1876]
Implement the design from https://www.figma.com/design/sNXucK1uMaZ8XXyLTZrdrs/IBM-Quantum-Documentation?node-id=7174-39884&t=GIeSutsuCJkUNVjg-1

<img width="630" alt="Screenshot 2024-08-26 at 10 58 16 AM" src="https://github.com/user-attachments/assets/892e0c3d-cebc-4005-a445-68ca0fa90bf8">

Because the component is not in the footer, it should probably be a component like `<ContributorsAttribution>`. The other design I was considering is putting metadata at the top of the file.

## How to get usernames

We need to figure out how to store the contributor GitHub usernames/handles. It will be much easier if we save the value to the file in qiskit/documentation, rather than somehow magically pulling the value at build-time in closed source. It would be hard to do the latter because it would require dynamically pulling Git information, even though the closed source and open source repos are not meant to have tight coupling.

I suspect the best approach is to have a script that dynamically adds the usernames to the file. We probably need users to manually run it, unfortunately. CI would lint to check everything is up-to-date.

**Comment by frankharkins** [comment]
We've had to drop this due to legal issues. We can't get GitHub handles as it requires too many API requests to generate the contributors for each file, and we can't use names from the Git log as it's PII, even though it's non-sensitive and publicly available.
