### ISSUE TITLE
Add doc testing to Python client repositories

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/documentation#1893]
It's important that the API docs code blocks do not break with code changes. We have too many docs to manually check that there are not issues, so we should automate it.

For Qiskit SDK, they don't want to run doctests in every PR because it's too slow. So they should have a weekly (nightly?) cron job, and also be able to manually trigger it.

qiskit-ibm-runtime and qiskit-ibm-transpiler might be fast enough to run every PR.

**Comment by frankharkins** [comment]
Update: PR has been made to Qiskit SDK. Qiskit Runtime already uses Jupyter execute, and Qiskit IBM Transpiler does not currently have any code examples.
