### ISSUE TITLE
Dark mode for Patterns diagram

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/documentation#1896]
This looks bad at https://docs.quantum.ibm.com/guides/intro-to-patterns

<img width="836" alt="Screenshot 2024-08-30 at 1 49 09 PM" src="https://github.com/user-attachments/assets/bd45671c-c9e8-427d-8c4e-0cc1e2530cde">

Ditto the four specific index pages we have.

**Comment by gracelindsell** [comment]
@Eric-Arellano The illustrations have been adjusted so that they arent as start on dark mode. They can be found [here](https://www.figma.com/design/sNXucK1uMaZ8XXyLTZrdrs/IBM-Quantum-Documentation?node-id=7461-37577&t=G6FylF6fKlyoJgR6-1)
