### ISSUE TITLE
Behavior when root job is canceled before session activates

### ISSUE THREAD

**Issue by mriedem** [Qiskit/documentation#190]
### URL, if applicable

These seem applicable (the former links to the latter so maybe only documenting it in one of those places is necessary).

https://qiskit.org/ecosystem/ibm-runtime/sessions.html#what-happens-when-a-session-ends

https://qiskit.org/ecosystem/ibm-runtime/how_to/run_session.html#close-a-session

### Describe the new content you are requesting.

For the ibm_cloud pay-go channel, the scheduler is going to be making a behavior change [1] such that if the root/first job in a session is canceled before it runs and activates the session, the session will be closed and any remaining queued jobs in that session will be marked as `Failed`. This is similar to what happens today if a user explicitly closes their session before all jobs are run or if the session closes due to the max time expiring and there are still remaining queued jobs in the session.

Similarly, there are plans to make the same behavior change in the ibm_quantum (IQP) channel [2].

We hope to have both changes done in October but let's hold off on publishing docs around this until we have the changes in production for both cloud pay-go and IQP channels.

[1] https://github.ibm.com/IBM-Q-Software/multi-channel-scheduler/pull/1267
[2] https://github.ibm.com/IBM-Q-Software/sw-api-queue/issues/3163

### If this new content request is accepted, do you want to write the content?

I only want to review the material when it's finished

**Comment by abbycross** [comment]
Thanks @mriedem! Let us know when the changes in production are near.

**Comment by mriedem** [comment]
The related change has been merged to IQP and should be in production next Monday Nov 13. The behavior is _slightly_ different in the IQP channel in that if the root job is canceled _at any point_, even if it's running or already completed, the session will be closed and remaining queued jobs will be marked as `Failed`. That's slightly different from the ibm_cloud channel implementation which only closes the session if the root job is canceled before it ever runs - if the root cloud job is running and then canceled we don't close the cloud pay-go session.

For the purposes of documenting this behavior I doubt you want to get into those details, so maybe it's sufficient to just say that canceling the root job in the session (the job which has the same ID as the session) will close the session and fail any remaining queued jobs in the session.

**Comment by abbycross** [comment]
@beckykd does this need to be tracked on the Cloud side?
