### ISSUE TITLE
responsible quantum page has broken link

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#1926]
### URL to the relevant documentation

https://docs.quantum.ibm.com/responsible-quantum-computing

### Select all that apply

- [ ] typo
- [ ] code bug
- [ ] out-of-date content
- [X] broken link
- [ ] other

### Describe the fix.

The "responsible quantum issue report form" link takes you to a broken airtable link

**Comment by frankharkins** [comment]
I've asked where the new link should point to.

**Comment by frankharkins** [comment]
@javabster the current link is correct and seems to work; maybe it was temporarily down?

**Comment by Eric-Arellano** [comment]
> the current link is correct and seems to work; maybe it was temporarily down?

It's asking me to log in to Airtable to use the form. Is that expected?

**Comment by frankharkins** [comment]
Me too, but once I logged in I was taken to the form
