### ISSUE TITLE
[ REFACTOR ] "get backend information with Qiskit" page with backendV2 info

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#195]
The current "[Get backend information with Qiskit](https://docs.quantum-computing.ibm.com/run/get-backend-information)" page uses information that is outdated and we should update it to include more recent backendV2 info.

Details here on how to migrate from backendV1 to backendV2: https://qiskit.org/documentation/apidoc/providers.html#migrating-between-backend-api-versions

I'm not sure what would be the most helpful for users at this stage:
1. update this page to include both backend v1 and v2 info
2. completely replace the backend v1 info with v2 info (and add a note about the change, including a link to the migration guide?)

I don't have strong feelings either way, maybe @mtreinish or @blakejohnson could weigh in?

**Comment by blakejohnson** [comment]
I would vote for completely replacing with backendV2 info.

**Comment by beckykd** [comment]
I reviewed the content and available materials and will definitely need dev support.  Since everyone is heads-down with Summit, we might need to put this off until then.
