### ISSUE TITLE
Update sessions usage info

### ISSUE THREAD

**Issue by kt474** [Qiskit/documentation#1971]
### URL, if applicable

https://docs.quantum.ibm.com/guides/execution-modes#sessions-versus-batch-usage

https://github.com/Qiskit/documentation/blob/main/docs/migration-guides/sessions.mdx

### Describe the new content you are requesting.

In qiskit-ibm-runtime 0.30.0, we added a new `Session.usage()` and `Batch.usage()` method that can be used instead of `session.details()["usage_time"]`

### If this new content request is accepted, do you want to write the content?

I will write a draft of the proposed content

**Comment by abbycross** [comment]
Thanks @kt474 !

**Comment by abbycross** [comment]
Hi @kt474 - do you have a timeline for this issue, so we can categorize it in our sprints? Thanks!

**Comment by kt474** [comment]
> Hi [@kt474](https://github.com/kt474) - do you have a timeline for this issue, so we can categorize it in our sprints? Thanks!

Just made a PR! https://github.com/Qiskit/documentation/pull/2078 Thanks!
