### ISSUE TITLE
Typo in Qiskit Functions figure

### ISSUE THREAD

**Issue by ElePT** [Qiskit/documentation#1977]
### URL to the relevant documentation

https://docs.quantum.ibm.com/guides/functions

### Select all that apply

- [X] typo
- [ ] code bug
- [ ] out-of-date content
- [ ] broken link
- [X] other

### Describe the fix.

The "Introduction to Qiskit Functions" page contains typos in the figure, see under "Run on hardware" it says "primtives" instead of "primitives":

![Screenshot 2024-09-18 at 14 16 03](https://github.com/user-attachments/assets/87410e80-5533-4a50-9ac3-ac7411d3ee33)

**Comment by Eric-Arellano** [comment]
It's also not using the proper terms for Patterns. It should be "Execute on hardware" and Post-process with a dash

**Comment by abbycross** [comment]
Will pass along to the appropriate member of the design team!

**Comment by mackinziblank** [comment]
Fixed & uploaded here: https://ibm.box.com/s/six6cn2wz7jjacium9pxgfwujaclz8oe

Good eyes y'all!
