### ISSUE TITLE
Clarify inputs/outputs on IBM Circuit Function page

### ISSUE THREAD

**Issue by jyu00** [Qiskit/documentation#1980]
### URL to the relevant documentation

https://docs.quantum.ibm.com/guides/ibm-circuit-function

### Select all that apply

- [ ] typo
- [ ] code bug
- [ ] out-of-date content
- [ ] broken link
- [X] other

### Describe the fix.

- The [Overview](https://docs.quantum.ibm.com/guides/ibm-circuit-function#overview) section talks about abstract PUBs as the input and links to PUBs description under primitives. But it doesn't say anything about what _abstract_ PUBs mean (e.g. how it's different from what Qiskit Runtime Estimator takes). 
- There is no explicitly section on output format. It's only mentioned under the example.

**Comment by abbycross** [comment]
Will check in with author of page!
