### ISSUE TITLE
Modal does not work for dark images

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/documentation#2037]
Clicking an image in dark mode shows an empty modal. Here's an example from https://docs.quantum.ibm.com/guides/algorithmiq-tem#function-description.

<img width="989" alt="Screenshot 2024-09-26 at 13 46 58" src="https://github.com/user-attachments/assets/d5cd6455-7959-4efd-bc23-c5a8440d3f7d">

**Comment by Eric-Arellano** [comment]
Fixed. Thanks for the report!
