### ISSUE TITLE
Recommendation on error mitigation techniques

### ISSUE THREAD

**Issue by jyu00** [Qiskit/documentation#2041]
### Describe the new content you are requesting.

Even though we have a [page](https://docs.quantum.ibm.com/guides/error-mitigation-and-suppression-techniques) describing the different error suppression / mitigation methods, not all users can translate that into the best ones to use for their workloads. It'd be nice to give users some pointers on when to use what, and the cost associated. For example, dynamical decoupling is mostly "free" (does not incur additional QPU time), but should only be used when there is idle time in the circuit. In addition, a longer DD sequence like XY4 should be used if the idle time is long, vs XX for shorter time. 

### If this new content request is accepted, do you want to write the content?

I only want to review the material when it's finished

**Comment by abbycross** [comment]
Update: I've reached out to Nate E-N and Pedro R to get names of potential SMEs

**Comment by abbycross** [comment]
Jessie is talking to Nate's team about creating a tutorial in Learning instead, so closing this.
