### ISSUE TITLE
Follow up on updated links when the runtime api docs are able to sync

### ISSUE THREAD

**Issue by abbycross** [Qiskit/documentation#205]
Check for anything linking out to qiskit.org and learn.qiskit.org in the non-API docs, for example: 

In [this section](https://docs.quantum-computing.ibm.com/run/instances#find-your-instances) there is a link that requires updating to [go here instead](https://docs.quantum-computing.ibm.com/api/qiskit-ibm-runtime/qiskit_ibm_runtime.QiskitRuntimeService#qiskitruntimeservice) (once it is updated/synced)/

There may be more instances of this...

**Comment by javabster** [comment]
duplicate of #297
