### ISSUE TITLE
Downloading a notebook has tables broken locally

### ISSUE THREAD

**Issue by pandasa123** [Qiskit/documentation#2051]
### URL to the relevant documentation

https://docs.quantum.ibm.com/guides/qedma-qesem

### Please describe the UI problem.

When I view the notebook on the docs page, it looks fine:

<img width="864" alt="Screenshot 2024-09-30 at 11 58 07" src="https://github.com/user-attachments/assets/05ec7217-1b3a-4385-85fc-7724986b74c8">

But when I download and view in VSCode, it's not rendering properly:

<img width="920" alt="Screenshot 2024-09-30 at 11 58 44" src="https://github.com/user-attachments/assets/d84b678b-5239-4c30-8946-696257ac9dc3">

I suspect this is because it's escaping the `|` character?

**Comment by frankharkins** [comment]
Yes it does look like it's escaping the pipe, here's some source from a downloaded notebook:

```json
"source":["## Function parameters\n\n\\| Name |  Type | Description | Required ..."
```

**Comment by frankharkins** [comment]
Should be fixed now. The script we use to process notebooks before download was inserting extra newlines everywhere which was mostly harmless but did break the markdown tables.
