### ISSUE TITLE
Bad GitHub source code link in API docs when decorator used

### ISSUE THREAD

**Issue by Shivansh20128** [Qiskit/documentation#2060]
### Environment

- **Qiskit version**: NA
- **Python version**: NA
- **Operating system**: NA

### What is happening?

The link for the GitHub source code redirects to the wrong file. See [here](https://docs.quantum.ibm.com/api/qiskit/dev/qiskit.visualization.dag_drawer#qiskitvisualizationdag_drawer). 
The Github link should redirect to the source code got dag_drawer function, but it is taking us to this [link](https://github.com/Qiskit/qiskit/tree/main/qiskit/utils/lazy_tester.py#L74-L316) instead.

### How can we reproduce the issue?

See the API Docs.

### What should happen?

The GitHub link in the API docs should take us to the source code of dag_drawer, which is [here](https://github.com/Qiskit/qiskit/blob/8ccbc8d28f34e3f2e1e0e8cbb66c4da95754b341/qiskit/visualization/dag_visualization.py#L76).

### Any suggestions?

Update the link to the source code.

**Comment by frankharkins** [comment]
Note this also affects other pages in visualization, including but not limited to:
* https://docs.quantum.ibm.com/api/qiskit/qiskit.visualization.pass_manager_drawer
* https://docs.quantum.ibm.com/api/qiskit/qiskit.visualization.plot_bloch_multivector
* https://docs.quantum.ibm.com/api/qiskit/qiskit.visualization.plot_bloch_vector

**Comment by Eric-Arellano** [comment]
https://docs.quantum.ibm.com/api/qiskit/dev/qiskit.circuit.BreakLoopOp#assemble is also broken, which has a deprecated decorator. The issue seems to be when you use a decorator.

**Comment by Eric-Arellano** [comment]
Fix is being deployed now. Thanks so much @Shivansh20128 for taking the time to report this! I really appreciate it and this ended up fixing a lot of broken links.

**Comment by Shivansh20128** [comment]
Happy to help wherever I can😊.
Thank You
