### ISSUE TITLE
Job limit documentation for gate-folding ZNE

### ISSUE THREAD

**Issue by jfraxanet** [Qiskit/documentation#2075]
### URL to the relevant documentation

The Job limits [documentation](https://docs.quantum.ibm.com/guides/job-limits) contains an error when describing the limits that apply to gate-folding ZNE "The number of two-qubit gates is multiplied by the largest noise factor requested in gate-folding ZNE."

### Select all that apply

- [ ] typo
- [ ] code bug
- [x] out-of-date content
- [ ] broken link
- [ ] other

### Describe the fix.

The sentence should be "The number of two-qubit gates is multiplied by the sum of noise factor requested in gate-folding ZNE."

**Comment by jyu00** [comment]
This will be closed by #2073

**Comment by beckykd** [comment]
#2073 was merged
