### ISSUE TITLE
Rewrite some guides as jupyter notebooks

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#2094]
Some guides were originally created with mdx but should be refactored into jupyter notebooks.

Guides that meet the following criteria should be considered for refactoring:

- They include a lot of code snippets that we want to test with our testing suite
- content that has high traffic or is often linked to from other content

I've identified the following pages that could do with rewriting:

- [x] [get started with primitives](https://docs.quantum.ibm.com/guides/get-started-with-primitives) (#2200)
- [x] [primitives examples](https://docs.quantum.ibm.com/guides/primitives-examples) (#2423)
- [ ] [specify options](https://docs.quantum.ibm.com/guides/specify-runtime-options) (#2452)

**Comment by Eric-Arellano** [comment]
First step is done! Thanks @abbycross. We'll open new issues if we want to convert more guides
