### ISSUE TITLE
should read "now" ready

### ISSUE THREAD

**Issue by acastellane** [Qiskit/documentation#2095]
### URL to the relevant documentation

https://docs.quantum.ibm.com/guides/dynamical-decoupling-pass-manager

### Select all that apply

- [x] typo
- [ ] code bug
- [ ] out-of-date content
- [ ] broken link
- [ ] other

### Describe the fix.

At the end before "next step" we should probably read "now" and not "not":
This transpiled circuit with dynamical decoupling is NOW ready to be sent to the backend.

**Comment by abbycross** [comment]
Thanks for catching that @acastellane !
