### ISSUE TITLE
Mention M3 with Sampler

### ISSUE THREAD

**Issue by jyu00** [Qiskit/documentation#2104]
### Select all that apply

- [ ] typo
- [ ] code bug
- [ ] out-of-date content
- [ ] broken link
- [x] other

### Describe the fix.

One complaint we recently received from the users was that V2 Sampler no longer supports error mitigation. While that's unlikely to change anytime soon, we could recommend people to use [mthree](https://github.com/Qiskit-Extensions/mthree), which was used in V1 Sampler and is still suitable for many use cases.

**Comment by abbycross** [comment]
@jyu00 Do you want this just in the migration guide, or are the other pages where this should appear?

**Comment by jyu00** [comment]
I was thinking about this page: https://docs.quantum.ibm.com/guides/configure-error-mitigation

On this page, it mentions "You cannot specify resilience levels in Sampler. However, you can set custom techniques individually.". While that statement is not technically wrong, since it's a page on _error mitigation_, I was expecting it to say something about "sampler doesn't support error mitigation" (it only supports error suppression). That can then be extended with "But you can use M3 to do error mitigation locally".
