### ISSUE TITLE
V1 to V2 Migration Guide Improvement Suggestion

### ISSUE THREAD

**Issue by acastellane** [Qiskit/documentation#2128]
### URL to the relevant documentation

https://docs.quantum.ibm.com/migration-guides/v2-primitives#sampler-examples--input-and-output

### Select all that apply

- [ ] typo
- [ ] code bug
- [ ] out-of-date content
- [ ] broken link
- [x] other

### Describe the fix.

When a user used to have in V1:
`dists = job.result().quasi_dists`
Could we provide an example of conversion of his code (including a circuit example) to V2 using:
`counts = job.result()[0].data.meas.get_counts()`
?
Thanks

**Comment by beckykd** [comment]
From @jyu00 "the quasi probabilities is just counts / shots... but I don't remember the v1 syntax so I'll need to play with it. "

**Comment by jyu00** [comment]
The old output format was a dictionary of with bitstring (in int) as the key and quasi-probabilities as the value for each circuit, e.g. `[{0: 0.4589879389380925, 1: 0.5410120610619075}]`. The new format has the same key (but as string) and counts as the value. To convert the new format to the old, one can do:

```python
v2_result = sampler_v2_job.result()
v1_format = []
for pub_result in v2_result:
    counts = pub_result.data.meas.get_counts()
    v1_format.append( {int(key, 2): val/shots for key, val in counts.items()} )
```

And `v1_format` here is the same result in the v1 format. Note that `shots` is the number of shots selected per [this rule](https://docs.quantum.ibm.com/guides/specify-runtime-options#shots).
