### ISSUE TITLE
Update optimization to clip at level 1 at most 

### ISSUE THREAD

**Issue by lerongil** [Qiskit/documentation#215]
### URL to the relevant documentation

https://docs.quantum-computing.ibm.com/run/advanced-runtime-options

### Select all that apply

- [ ] typo
- [ ] code bug
- [ ] out-of-date content
- [ ] broken link
- [x] other

### Describe the fix.

Server-side (primitives) clip optimization level to 1 at most. This temporarily re-defines optimization levels 1, 2, and 3 to be identical for the Primitives. This is what we want updated in the documentation to reflect that.  Qiskit transpiler optimization level 1 will still do layout, routing, and basis gate translation so at this step we have decreased the cost of transpilation but we haven't stopped accepting abstract or virtual circuits.

**Comment by beckykd** [comment]
@lerongil - I can start working on this today.  I'll contact you about the updates

**Comment by beckykd** [comment]
We also discuss optimization levels in configure-error-suppression, so we'll need to update that file as well.

**Comment by beckykd** [comment]
It looks like the work for Step 1 of issue 109 was done here: https://github.ibm.com/IBM-Q-Software/qiskit-ibm-primitives/pull/235  so I need to watch that and make sure not to push out these changes before the next release is pushed live.
