### ISSUE TITLE
Broken link in Hello World

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#2150]
### URL to the relevant documentation

https://docs.quantum.ibm.com/guides/hello-world#next-steps

### Select all that apply

- [ ] typo
- [ ] code bug
- [ ] out-of-date content
- [x] broken link
- [ ] other

### Describe the fix.

The next steps section of hello world has a link to the learning platform. The link is specifically pointing to the tutorial category "workflow examples". but it seems that category has been removed from the learning platform so the link just goes to [an empty tutorials catalogue page](https://docs.quantum.ibm.com/guides/hello-world) (i.e. not much use for the user 😅 ).

Instead I think we should update this line in next steps to just point to the overall tutorial catalogue (i.e. with no filters set) to prevent the link breaking again in future if the filters change on the learning platform again.

**Comment by abbycross** [comment]
I did a quick ripgrep search to see if we have other broken links to learning similar to this, and surfaced a few others:

```
docs/guides/install-qiskit.mdx
253:  -  Try one of the [workflow example tutorials.](https://learning.quantum.ibm.com/catalog/tutorials?category=workflow-example)

docs/guides/setup-channel.mdx
258:  -  Try one of the [workflow example tutorials.](https://learning.quantum.ibm.com/catalog/tutorials?category=workflow-example)

docs/guides/native-gates.mdx
103:    - Apply your knowledge of basis gates to one of these [workflow example tutorials.](https://learning.quantum.ibm.com/catalog/tutorials?category=workflow-example)
```
