### ISSUE TITLE
typo in Specify observables in the Pauli basis

### ISSUE THREAD

**Issue by lucachiese25** [Qiskit/documentation#2172]
### URL to the relevant documentation

https://docs.quantum.ibm.com/guides/specify-observables-pauli

### Select all that apply

- [x] typo
- [ ] code bug
- [ ] out-of-date content
- [ ] broken link
- [ ] other

### Describe the fix.

"For observables that are not given in terms of Pauli operators but in a matrix for," should be "in a matrix form".

**Comment by Eric-Arellano** [comment]
Thanks for opening this! 🙏 Would you be interested in opening a PR to fix it?

**Comment by lucachiese25** [comment]
yes, sure.
