### ISSUE TITLE
Sampler SamplerV2 consistency

### ISSUE THREAD

**Issue by acastellane** [Qiskit/documentation#2176]
### URL to the relevant documentation

https://docs.quantum.ibm.com/guides/run-jobs-batch#open-a-batch
https://docs.quantum.ibm.com/guides/run-jobs-session#set-up-to-use-sessions

### Select all that apply

- [ ] typo
- [ ] code bug
- [ ] out-of-date content
- [ ] broken link
- [x] other

### Describe the fix.

Hi,
For historical reasons, here and there we meet `Sampler `and `SamplerV2 as Sampler` imports (see examples above)
Is Consistency possible ?
Thanks

**Comment by javabster** [comment]
thanks for flagging this! they should all say `samplerv2 as sampler` so the other way is a typo. we'll get that fixed asap
