### ISSUE TITLE
Error in 'Get started with primitives'

### ISSUE THREAD

**Issue by lucachiese25** [Qiskit/documentation#2189]
### URL to the relevant documentation

https://docs.quantum.ibm.com/guides/get-started-with-primitives

### Select all that apply

- [x] typo
- [x] code bug
- [ ] out-of-date content
- [ ] broken link
- [ ] other

### Describe the fix.

In the section "Get started with Estimator" ,  running the 127-qubit circuit of the example on the backend returned from the least_busy method , that is 'ibm_sherbrooke', I got the following error on the IBM Quantum Platform 

 Status details
Status
Failed
error icon

Job not valid. '48921 2-qubit gates exceeds the system limits by 389.210% in combination with the option configuration. -- Split circuits or PUBs into multiple jobs. See `Run jobs in a batch <https://docs.quantum.ibm.com/guides/run-jobs-batch#partition>`__ for an example. -- https://ibm.biz/error_codes#1520' 

which is different from the output in the documentation.

In the section "Get started with Simulator" the output is a 4-qubit circuit's one  while the example uses a 127-qubit circuit.

**Comment by abbycross** [comment]
@lucachiese25 the new example on the [Get started with primitives](https://docs.quantum.ibm.com/guides/get-started-with-primitives) page should work now. Thank you!
