### ISSUE TITLE
Exception in IBM Circuit function page

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/documentation#2193]
The following section contains a cell that's thrown an exception. Output shows the traceback.

https://docs.quantum.ibm.com/guides/ibm-circuit-function#fetching-error-messages

**Comment by pandasa123** [comment]
This is intended to show how to retrieve an error message

**Comment by frankharkins** [comment]
Ahh so it is. I just skimmed the page while scoping out #1951.
