### ISSUE TITLE
API generation regression in properties

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/documentation#224]
From https://github.com/Qiskit/documentation/pull/222#discussion_r1367492777:

This is a regression.

Now:

<img width="272" alt="Screenshot 2023-10-20 at 5 19 17 PM" src="https://github.com/Qiskit/documentation/assets/14852634/8423b351-3b3c-4f74-82cf-803aa793b8b9">

Before:

<img width="174" alt="Screenshot 2023-10-20 at 5 19 30 PM" src="https://github.com/Qiskit/documentation/assets/14852634/5e58cd21-21af-441c-9bb4-9093b9ed887c">

qiskit.org:

<img width="292" alt="Screenshot 2023-10-20 at 5 19 57 PM" src="https://github.com/Qiskit/documentation/assets/14852634/8019992c-3a63-487f-acff-4a2f081a27fc">

**Comment by frankharkins** [comment]
Possibly related problem in [/api/qiskit/tools#monitoring](https://docs.quantum.ibm.com/api/qiskit/tools#monitoring) (see "line_discipline").

<img width="500" alt="Screenshot 2024-01-25 at 12 03 44" src="https://github.com/Qiskit/documentation/assets/36071638/1b87c10b-8f27-46a9-9da2-32929e47a9e1">

**Comment by arnaucasau** [comment]
@frankharkins I think the issue with `line_discipline` is not related to this regression. It seems like the HTML files from the CI artifact have the same problem :thinking: 

![Captura desde 2024-02-27 20-53-14](https://github.com/Qiskit/documentation/assets/47946624/f4868f0e-dae6-4236-847f-4a8de3cb9c16)
