### ISSUE TITLE
Qiskit Functions diagram incorrect

### ISSUE THREAD

**Issue by pandasa123** [Qiskit/documentation#2250]
### URL to the relevant documentation

https://docs.quantum.ibm.com/guides/functions

### Select all that apply

- [x] typo
- [ ] code bug
- [ ] out-of-date content
- [ ] broken link
- [ ] other

### Describe the fix.

Currently the image shows the following:

![Image](https://github.com/user-attachments/assets/7ea54b03-58ac-41fb-a9cf-702324cd2359)

Application functions should have "domain-specific results" as the output, not "mitigated expectation values"

**Comment by pandasa123** [comment]
Here's the correct one

![Image](https://github.com/user-attachments/assets/9e5dbd92-7917-473b-8656-2912a0c5a536)

**Comment by Eric-Arellano** [comment]
Thanks @pandasa123! Do you have the dark mode variant of this?

**Comment by pandasa123** [comment]
![Image](https://github.com/user-attachments/assets/3c518c71-b1a9-4c20-b793-b06a4b7fb487)
