### ISSUE TITLE
Update guidance to manage tokens in environment, rather than plaintext

### ISSUE THREAD

**Issue by pandasa123** [Qiskit/documentation#2255]
## URL, if applicable

- https://docs.quantum.ibm.com/guides/setup-channel#set-up-to-use-ibm-quantum-platform
- https://docs.quantum.ibm.com/guides/setup-channel#set-up-to-use-ibm-cloud
- https://docs.quantum.ibm.com/guides/functions#get-started-with-qiskit-functions

### What needs to updates?

Currently, we state the following:

> Account credentials are saved in plain text, so only do so if you are using a trusted device.

This issue has two parts:

1. We should update the setup instructions 
2. Places where we state the above warning, we should add a link for users to learn how securely manage their token
3. Update places where `<YOUR_IQP_API_TOKEN>` is stated to `os.getenv("IQP_API_TOKEN")`

### Content

To store sensitive information like account credentials more securely, it’s a good practice to use environment variables instead of saving them in plain text. Here’s how you can modify your code to load the API token from an environment variable.

1. Set the environment variable:

Set the `IQP_API_TOKEN` environment variable in your system. You can do this by adding the following line to your shell profile (e.g., `.bashrc`, `.zshrc`) or by setting it directly in your terminal:

```bash
export IQP_API_TOKEN="<YOUR_IQP_API_TOKEN>"
```

2. Modify the Code to Retrieve the Token from the Environment Variable

Update your code to retrieve the token from the environment variable instead of saving it directly:

```python
import os
from qiskit_ibm_catalog import QiskitFunctionsCatalog

# Gather the token from your environment
iqp_api_token = os.getenv("IQP_API_TOKEN")

QiskitFunctionsCatalog.save_account(token=iqp_api_token)
```

### If this new content request is accepted, do you want to write the content?

I can help the team by providing enough information to write the material

**Comment by javabster** [comment]
if possible would be good to put this inside a twisty to save some space in an already long page
