### ISSUE TITLE
New experimental option for Qiskit Runtime

### ISSUE THREAD

**Issue by jyu00** [Qiskit/documentation#2256]
### URL, if applicable

https://docs.quantum.ibm.com/guides/runtime-options-overview#available-options

### Describe the new content you are requesting.

We'd like to add a new experimental option to the options table. ~The final name is still TBD, and I will update the issue once that's decided~. 

The options table will have 

| Option | Sub-option | Sub-sub-option | Choices | Default | 
| -- | -- | -- | -- | -- |
| experimental |  | | | | 
|  | execution_path | | gen3-turbo* | None | 

For both Sampler and Estimator.

And the footnote would say something like "Setting `gen3-turbo` enables the next generation execution path. This is currently experimental only available on `ibm_torino`".

The in the [compatibility table](https://docs.quantum.ibm.com/guides/runtime-options-overview#options-compatibility), we should add that <new flag> cannot be used with 
- dynamic circuits
- meas_type=kerneled or meas_type=avg_kerneled
- fractional gates

### If this new content request is accepted, do you want to write the content?

I can help the team by providing enough information to write the material

**Comment by beckykd** [comment]
Is there an expected timeline for this new option?

**Comment by beckykd** [comment]
> Is there an expected timeline for this new option?

Sounds like it's due by the 15th
