### ISSUE TITLE
Update the documentation about the AI-powered transpiler passes to include information about the local mode

### ISSUE THREAD

**Issue by cbjuan** [Qiskit/documentation#2257]
We're going to launch a new version of the `qiskit-ibm-transpiler` library that will allow users to run the AI-powered transpiler passes to run on local mode (instead of using the service).

We need to document the process to use install the local mode + how to use the passes locally

**Comment by javabster** [comment]
@cbjuan are you planning on opening a PR for it or should we do it?

**Comment by cbjuan** [comment]
Hi @javabster.  We’ll open a PR  for this today or tomorrow. Thanks

**Comment by cbjuan** [comment]
PR open! #2273
