### ISSUE TITLE
Create a few sample programs

### ISSUE THREAD

**Issue by Shua-github** [Qiskit/documentation#2279]
### Describe the new content you are requesting.

Create a few sample programs, such as generating a few random numbers

### If this new content request is accepted, do you want to write the content?

no

**Comment by javabster** [comment]
Hi @Shua-github generating random numbers is not really useful enough for us to warrant making a docs guide about. There are many toy examples like this out there on the internet for people to use, and for larger more useful examples you can check out: https://learning.quantum.ibm.com/catalog/tutorials
