### ISSUE TITLE
Link checker won't validate Admonitions from MDX syntax

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/documentation#228]
From what I can tell, MDX syntax like this is not checked:

https://github.com/Qiskit/documentation/blob/00d462fd689a62e544e3c9f14eafee793c1607e3/docs/start/index.mdx#L45-L56

This would presumably be because the MDX component is not being parsed, since it's non-standard markdown. I'm not sure how we'd work around this.

--

@frankharkins had the suggestion to pre-process the Markdown files to simply remove the `<Admonition>` lines. I think that's a great idea. Make sure you pre-process in memory and don't actually rewrite the file live.

**Comment by arnaucasau** [comment]
The bug should be solved in #261 by adding an apostrophe surrounding the admonition tags. Trying to solve this issue I came across another bug. There are links preceded by lines starting with space that won't be validated either. One example can be found in this file:

https://github.com/Qiskit/documentation/blob/00d462fd689a62e544e3c9f14eafee793c1607e3/docs/start/install.mdx#L249-L268

In line 249, we have a line starting with a tabulation or multiple spaces. With those spaces, the link in line 267 won't be validated.

In this case, the link is inside an admonition tag but if you delete the tag the problem doesn't disappear. One solution that I found to work, is to add a dash (-) followed by a space in front of every line. This fix can substitute the use of the apostrophe used in the last commit of #261.

The change is to replace the lines added in that PR:

```
const source_raw = readFileSync(filePath, { encoding: "utf8" });
const source = source_raw.replace(/<Admonition/g,"'<Admonition")
                         .replace(/Admonition>/g,"Admonition>'");
```

by:
```
const source_raw = readFileSync(filePath, { encoding: "utf8" });
const source = source_raw.replace(/^[a-zA-Z0-9<]/gm,"- ");
```

This seems to work fine on my end solving the two bugs, and it finds multiple links that weren't validated before. I want to test different scenarios that perhaps are not happening in the documentation we have right now, but I wanted to know your opinion @Eric-Arellano and @frankharkins before changing anything in #261 or before creating an independent issue (if you think is worth it having two independent issues).

**Comment by axelhzf** [comment]
This does not look like a good solution for the long term. We will have the same problem with other mdx component. I think we should use a mdx parser instead.

**Comment by frankharkins** [comment]
Ok looks like we use remark internally, I'll work with @arnaucasau to use that and come up with something more robust

**Comment by axelhzf** [comment]
Yes, we are using remark. For detecting links you could create a unified plugin. Something like

```ts
/** @type {import('unified').Plugin<[], import('mdast').Root>} */
export function findLinks() {
  return (tree: Root) => {
    visit(tree, 'link', (node) => {
        // node.url has the links
    });
  };
}
````

**Comment by Eric-Arellano** [comment]
Closed by https://github.com/Qiskit/documentation/pull/261. Huzzah! Thanks @arnaucasau and thanks @axelhzf for the advice <3
