### ISSUE TITLE
API docs need to handle functions better

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/documentation#231]
E.g. https://docs.quantum-computing.ibm.com/api/qiskit/compiler

<img width="762" alt="Screenshot 2023-10-23 at 6 02 53 PM" src="https://github.com/Qiskit/documentation/assets/14852634/c68fea1d-00b9-4b7c-aa2d-33ae7266e417">

The header should better show what the function name is. And the right sidebar should be more useful:
 
<img width="352" alt="Screenshot 2023-10-23 at 6 03 16 PM" src="https://github.com/Qiskit/documentation/assets/14852634/6858e58c-7420-4145-87c6-9baf4de6ad07">

But it is important the function still shows the whole import path because we have some modules right now that have functions that have functions with submodules, e.g. the module page for `my_module` has a function `my_module.submodule.my_func` -- you have to show the whole import path for the docs to be correct.

**Comment by javabster** [comment]
As part of this work can we also add anchor tags to the functions? I came across this issue earlier this week where i couldnt link people to `qiskit.compiler.transpile()` I could only provide a link to `qiskit.compiler` which is a massive page

**Comment by Eric-Arellano** [comment]
@javabster you can: the syntax is `#qiskit.compiler.transpile`. This works because the API generation script copies over this HTML:

```html
<span id="qiskit.compiler.assemble"></span>
```

But much better would be having it obvious how to copy the anchor from users simply using the website directly, which would be through the headers.
