### ISSUE TITLE
Provide Intersphinx `objects.inv` file for API docs

### ISSUE THREAD

**Issue by garrison** [Qiskit/documentation#236]
### Feedback

At qiskit.org, there is currently a file called `objects.inv`: https://qiskit.org/documentation/objects.inv.  This file contains information about the identifiers used in Qiskit so that other Sphinx projects can create cross references to the Qiskit API docs.  For instance, the Circuit Knitting Toolbox's [page on the `cut_wires` function](https://qiskit-extensions.github.io/circuit-knitting-toolbox/stubs/circuit_knitting.cutting.cut_wires.html) links to the `QuantumCircuit` documentation at qiskit.org using this mechanism.

Currently, the `objects.inv` file is missing from the build at https://docs.quantum-computing.ibm.com/api/qiskit.  If the directory structure is the same as is output by Sphinx, then allowing Intersphinx to work may be as simple as including Qiskit's `objects.inv` in the build.  If, however, the directory structure does not match, then `objects.inv` will need to be adjusted in an automated way to contain correct information.

**Comment by Eric-Arellano** [comment]
This is now live thanks to @frankharkins in https://github.com/Qiskit/documentation/pull/522 🚀 you can download https://docs.quantum.ibm.com/api/qiskit/objects.inv, for example. Projects should use these URLs:

* runtime: https://docs.quantum.ibm.com/api/qiskit-ibm-runtime
* provider: https://docs.quantum.ibm.com/api/qiskit-ibm-provider
* qiskit: https://docs.quantum.ibm.com/api/qiskit

Let's close this after we switch 2-3 projects and confirm it's working in the wild.

**Comment by frankharkins** [comment]
PR made for `qiskit-ibm-provider`: https://github.com/Qiskit/qiskit-ibm-provider/pull/797. I've checked the links and they all work. Qiskit IBM Runtime does not use intersphinx so no PR needed there.

**Comment by Eric-Arellano** [comment]
Thanks, Frank, for your great work on this issue! I opened https://github.com/Qiskit/documentation/issues/669 and https://github.com/Qiskit/documentation/issues/668 to track the follow up work.
