### ISSUE TITLE
Missing API references for Runtime

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/documentation#238]
There are a few APIs that aren't actually documented at qiskit.org/documentation and docs.quantum-computing.ibm.com. The code exists, but it isn't in the API docs because we don't put the code member in its owning module's `__init__.py` file so Sphinx doesn't generate a page for the entity. 

To fix this, you have to change the underlying API docs. For adding new modules, we need to add a file to https://github.com/Qiskit/qiskit-ibm-runtime/tree/main/docs/apidocs and also update `ibm-runtime.rst` with it.

To change what shows up in a module, you have to change the `__init__.py` like how this is set https://github.com/Qiskit/qiskit-ibm-runtime/blob/8723ccf827fd7b43bf653d76e9c254ad00f9be4b/qiskit_ibm_runtime/__init__.py#L13-L161

Then cherry-pick to the stable branch and rebuild the docs with it. Finally, regenerate our docs. (I/Eric can help with these parts.)

Tracked by ~https://github.com/Qiskit/qiskit/issues/11290 and~ https://github.com/Qiskit/qiskit-ibm-runtime/issues/1236

**Comment by kevinsung** [comment]
I found a reference that doesn't have an API page in the original docs, likely because it is meant to be an internal class: qiskit.quantum_info.states.quantum_state.QuantumState

**Comment by Eric-Arellano** [comment]
Going to close this once we finish merging https://github.com/Qiskit/qiskit-ibm-runtime/pull/1350 and regenerate the API docs with it.

**Comment by Eric-Arellano** [comment]
This is now live. Thanks @kaelynj and @beckykd! Great work.

<img width="252" alt="Screenshot 2024-02-01 at 1 31 46 PM" src="https://github.com/Qiskit/documentation/assets/14852634/7e34bd87-fb9b-49a0-b3d4-6b5de1565107">
