### ISSUE TITLE
prevent  error in Grover's algorithm tutorial

### ISSUE THREAD

**Issue by lc2507** [Qiskit/documentation#2380]
### URL to the relevant documentation

https://learning.quantum.ibm.com/tutorial/grovers-algorithm

### Select all that apply

- [ ] typo
- [ ] code bug
- [ ] out-of-date content
- [ ] broken link
- [ ] other

### Describe the fix.

With the current definition, the _grover_oracle_ function does not take into account inputs (_marked_states_) without '0', indeed it returns the error " CircuitError: 'One or more of the arguments are empty' ", because zero_inds_ is empty.  
Although in the tutorial this error is not encountered, since marked_states = ["011", "100"], it might be useful to modify the grover_oracle function to handle also this case and make the function more general for other applications. 
For example, the following piece of code can solve the issue

```
        if len(zero_inds)==0:
            qc.compose(MCMT(ZGate(), num_qubits - 1, 1), inplace=True)
            continue
```
inserted before 
```
        qc.x(zero_inds)
        qc.compose(MCMT(ZGate(), num_qubits - 1, 1), inplace=True)
        qc.x(zero_inds)
```

**Comment by beckykd** [comment]
Looks like this one should be moved here https://github.ibm.com/IBM-Q-General/ibm-quantum-learning-enablement/issues, @Eric-Arellano or @javabster

**Comment by beckykd** [comment]
Handed this off to the learning team.
