### ISSUE TITLE
Add section to Interoperate with OpenQASM 2 file on using Qiskit's built-in gate classes

### ISSUE THREAD

**Issue by abbycross** [Qiskit/documentation#240]
In [this file](https://github.com/Qiskit/documentation/blob/main/docs/build/interoperate-qiskit-qasm2.mdx), we might want to add a section on how to use more of Qiskit's built-in gate classes when importing from OpenQASM 2, or alternatively modify the "Custom instructions" section to include it. Given the timing constraints we've got at the moment, it might be something that can wait, though - it would probably need to be a significantly rewritten version of https://qiskit.org/documentation/apidoc/qasm2.html#legacy-compatibility, since that was targetted at discussing something a bit different.

_Originally posted by @jakelishman in https://github.com/Qiskit/documentation/pull/151#discussion_r1362104180_
           

We will need Jake's help to rewrite the content.

**Comment by abbycross** [comment]
Jake is swamped with 1.0 work so I will move this to a later sprint.

**Comment by jakelishman** [comment]
Sorry, I said I'd get to this this week, then got pulled into other technical discussion about the primitives interfaces that I wasn't expecting.  I've still got it on my to-dos, I'm just not going to have the draft by EOD today.  I will try again on Monday (sorry!)
