### ISSUE TITLE
Broken link at the bottom of qasm-circuits

### ISSUE THREAD

**Issue by lerongil** [Qiskit/documentation#241]
### URL to the relevant documentation

https://docs.quantum-computing.ibm.com/build/qasm-circuits

### Select all that apply

- [ ] typo
- [ ] code bug
- [ ] out-of-date content
- [X] broken link
- [ ] other

### Describe the fix.

Right now, the bottom of [this page](https://docs.quantum-computing.ibm.com/build/qasm-circuits) has a suggested next step pointing to: https://docs.quantum-computing.ibm.com/run/backends. 

We should update this to point here: https://docs.quantum-computing.ibm.com/run

**Comment by Eric-Arellano** [comment]
Hm, our link checker didn't catch this due to https://github.com/Qiskit/documentation/issues/228. That suggests to me fixing that quirk is actually pretty important.

**Comment by abbycross** [comment]
@lerongil good catch -- and totally my bad for not deleting this file -- you must have found it via search?? We have replaced this page by the two Interoperate Qiskit with OpenQASM files (one for qasm 2 and another for 3). I'll delete it asap!!

**Comment by abbycross** [comment]
Fixed in https://github.com/Qiskit/documentation/pull/242
