### ISSUE TITLE
Remove deprecated functions in `pulse.ipynb`

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/documentation#2414]
Lots of deprecation warnings in `docs/guides/pulse.ipynb` ( see https://github.com/Qiskit/documentation/actions/runs/12119882758/job/33788219418).

**Comment by Eric-Arellano** [comment]
Pulse is deprecated entirely, so I think the appropriate action is to add a big admonition to the top of the file and then ignore deprecations in code blocks.
