### ISSUE TITLE
Fix typo in comment in a code snippet

### ISSUE THREAD

**Issue by pacomf** [Qiskit/documentation#2449]
### URL to the relevant documentation

Comment should says `using the estimator`

https://github.com/Qiskit/documentation/blob/9256be30c4b34f86ed87d556c4c4868915c76ee0/docs/guides/q-ctrl-performance-management.ipynb#L216

### Select all that apply

- [x] typo
- [ ] code bug
- [ ] out-of-date content
- [ ] broken link
- [ ] other

### Describe the fix.

Modify `sampler` by `estimator`

**Comment by abbycross** [comment]
Thank you for reporting! Will be closed by https://github.com/Qiskit/documentation/pull/2458
