### ISSUE TITLE
Fix typo importing qiskit-ibm-catalog

### ISSUE THREAD

**Issue by pacomf** [Qiskit/documentation#2450]
### URL to the relevant documentation

The import should be with underscores, `qiskit_ibm_catalog`

https://github.com/Qiskit/documentation/blob/9256be30c4b34f86ed87d556c4c4868915c76ee0/docs/guides/functions.ipynb#L116

### Select all that apply

- [x] typo
- [ ] code bug
- [ ] out-of-date content
- [ ] broken link
- [ ] other

### Describe the fix.

Modify `qiskit-ibm-catalog` by `qiskit_ibm_catalog`

**Comment by abbycross** [comment]
Thank you for reporting!! Will be closed by https://github.com/Qiskit/documentation/pull/2458
