### ISSUE TITLE
Non-open-access backend used in `fractional-gates.ipynb`

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/documentation#2454]
The fractional gates notebook uses a backend that is not available on `ibm-q/open/main`. We should switch this notebook to use an open-access backend so all users can run the code examples on the page.

**Comment by Eric-Arellano** [comment]
@frankharkins this causes CI to break in https://github.com/Qiskit/documentation/pull/2491, meaning CI is broken on main. Are you able to either please fix the issue this week or should we move the notebook to not testable? If the fix isn't super hard, the former is preferred.
