### ISSUE TITLE
Misc issues with session docs

### ISSUE THREAD

**Issue by jyu00** [Qiskit/documentation#247]
### URL to the relevant documentation

https://docs.quantum-computing.ibm.com/run/sessions
https://docs.quantum-computing.ibm.com/run/run-jobs-in-session

### Select all that apply

- [ ] typo
- [ ] code bug
- [X] out-of-date content
- [ ] broken link
- [X] other

### Describe the fix.

https://docs.quantum-computing.ibm.com/run/sessions:

1. > Since data from the first session job is cached and used by subsequent jobs, if the first job is canceled, subsequent session jobs will all fail.

  This sentence is only half true. Data from the first session job is no longer cached (but subsequent jobs would still fail if the root job is cancelled).

2. > Jobs that fit within the maximum session time run back-to-back on hardware.

This line suggests that jobs in batch mode run serially. But in reality the classical processing part is actually done in parallel. We should also point that out as an advantage of using batch mode.

3. We should have code showing how to use session in iterative and batch modes. For example:

Batch:

The following example shows how you can divide up a long list of circuits into multiple jobs and run them as a batch to take advantage of the parallel processing. 

```python

backend = service.backend("ibm_sherbrooke")

with Session(backend=backend):
    estimator = Estimator()
    start_idx = 0
    jobs = []
    while start_idx < len(circuits):
        end_idx = start_idx + backend.max_circuits
        jobs.append(estimator.run(circuits[start_idx:end_idx], obs[start_idx:end_idx], params[start_idx:end_idx]))
        start_idx = end_idx
```

4. > The quantum device is locked to the session user unless the TTL is reached.

"Locked" can be misleading. Other jobs (such as calibration or jobs already running when a session started) can still run. It'd be more accurate to say a session is active and its jobs get priority until ITTL or max timeout is reached. 

Under https://docs.quantum-computing.ibm.com/run/run-jobs-in-session:

1. > Data from the first session job is cached and used by subsequent jobs.

Same as 1 above. 

2. > Directly specify a string with the backend name. Example:

The code example should include service, i.e. 

```python
service = QiskitRuntimeService()
with Session(service=service, backend="ibmq_qasm_simulator"):
    ...
```

**Comment by beckykd** [comment]
Suggestion from Jay:  Add a code example showing that you need close if you use a class
