### ISSUE TITLE
Adjust `multiverse-computing-singularity.ipynb` to run from start to finish

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/documentation#2481]
The notebook `docs/guides/multiverse-computing-singularity.ipynb` had undefined variables, so we can't currently run it to check it works. We should consider adjusting the notebook so we can test it.

See #2463 for examples of how I adjusted other notebooks to get them working, but this one will require more work and understanding to make sure we preserve the meaning.

**Comment by Eric-Arellano** [comment]
Duplicate of https://github.com/Qiskit/documentation/issues/2297
