### ISSUE TITLE
[ NEW PAGE ] Add documentation on Batch mode

### ISSUE THREAD

**Issue by jyu00** [Qiskit/documentation#272]
### Describe the new content you are requesting.

Qiskit Runtime is introducing a new `Batch` class that works similarly as `Session`, but the former is for submitting multiple jobs at once while the latter is for iterative workloads. 

cc @kt474 

### If this new content request is accepted, do you want to write the content?

I can help the team by providing enough information to write the material

**Comment by javabster** [comment]
hey @jyu00 thanks for opening an issue whats the target date to release this page? And can you provide an outline of what you want covered?

**Comment by mriedem** [comment]
I'm also interested in how this is going to work without server side changes in the scheduler. Like, is qiskit runtime going to keep track of jobs submitted in a Batch context manager and block being able to wait for results before the context manager is exited and "closes" the session under the covers from accepting more jobs?

**Comment by jyu00** [comment]
@javabster This is needed for Summit, so whenever before that. I'm thinking having a separate `Batch` section that's similar to `Session` and contains largely wording from [session batch mode](https://docs.quantum-computing.ibm.com/run/sessions#batch), with code example.

@mriedem Nope nothing fancy. It'll literally work like the existing `Session` until server side support is done. So we "expect" you to send jobs without delay in between, but we don't enforce it lol

**Comment by beckykd** [comment]
@jyu00 - Will there still be a batch mode for sessions, or is this replacing that behavior?

**Comment by jyu00** [comment]
@beckykd It's a replacement for session batch mode (but not iterative).

**Comment by mriedem** [comment]
> So we "expect" you to send jobs without delay in between, but we don't enforce it lol

What could go wrong! 😅
