### ISSUE TITLE
In API script, increase the number of headings on the right

### ISSUE THREAD

**Issue by beckykd** [Qiskit/documentation#274]
### URL to the relevant documentation

Example where we really need more headings: https://docs.quantum-computing.ibm.com/api/qiskit/compiler#compilation-routines

Same file in Qiskit.org: https://qiskit.org/documentation/apidoc/compiler.html#qiskit.compiler.transpile

### Please describe the UI problem.

There's no way to find the areas that you need in the topic I linked above. Note that in the Qiskit version, the sections on the right have titles that aren't in the actual document, so I have no idea where they came from. 

1 Docs screenshot and Qiskit screenshot are attached. 
![Screenshot 2023-10-31 095251](https://github.com/Qiskit/documentation/assets/66339736/b54bedaf-213c-4688-9b7c-2fded439ba4a)

![Screenshot 2023-10-31 095303](https://github.com/Qiskit/documentation/assets/66339736/36ec3134-c94b-4d65-bc9c-929d7ed1d780)

**Comment by Eric-Arellano** [comment]
Fixed by @frankharkins in https://github.com/Qiskit/documentation/pull/683! 🚀
