### ISSUE TITLE
Adding "-f" to instruction line about creating conda environment

### ISSUE THREAD

**Issue by vanitery** [Qiskit/documentation#280]
### URL to the relevant documentation

https://qiskit.org/ecosystem/metal/installation.html#text-instructions

### Select all that apply

- [ ] typo
- [ ] code bug
- [X] out-of-date content
- [ ] broken link
- [ ] other

### Describe the fix.

I believe it's out of date from current python kernel, but it might also be specific to my set-up. Nevertheless I don't believe it will break anybody's installation to change from:

"conda env create -n <env_name> environment.yml"

into:

"conda env create -n <env_name> -f environment.yml"

And it should save some people from spending the time debugging the following error message that I got:

"SpecNotFound: Invalid name 'environment.yml', try the format: user/package"

**Comment by Eric-Arellano** [comment]
Hi, thanks for opening this! This repository is for the Qiskit docs at https://docs.quantum-computing.ibm.com, not for Qiskit Metal. Can you please open an issue at https://github.com/qiskit-community/qiskit-metal instead?
