### ISSUE TITLE
Add note to readme about what this repo does NOT cover

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#284]
We've had a few issues and PRs opened in this repo by people misunderstanding what the purpose of this repo is for. We should add a section to the readme explaining what this repo does not cover and where they should go instead

Specifically:
- for stuff relating to the qiskit api references they should open issues and PRs to the Qiskit repo
- for stuff relating to Qiskit Ecosystem projects they should open issues and PRs in the relevant ecosystem project repo

**Comment by frankharkins** [comment]
Maybe we should add something to the issue templates too, it's easy for stuff to get buried in the README

**Comment by beckykd** [comment]
> Maybe we should add something to the issue templates too, it's easy for stuff to get buried in the README

I agree - thoughts, @javabster ?

**Comment by javabster** [comment]
yeah i think updating the issue templates would be good as well. I think in markdown you can add a little warning ⚠️ emoji or message, maybe add one of those to the top of the issue template before the first question

**Comment by beckykd** [comment]
The Readme has already been updated and #597 covered the rest of these updates
