### ISSUE TITLE
Switch all diagrams to use the IQP style

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/documentation#286]
### Feedback

There are different ways to draw a quantum circuit.

- Default `draw()` (text)
- `draw("mpl")`
- `draw()` (but with `mpl` set as default in `~/.qiskit/settings.conf`)

If choosing the Matplotlib drawer, there are different styles too (`default`, `textbook`, `iqp`).

We should decide on one and make it consistent across the docs.

### Other comments

- In the textbook we were told to use `draw()` with default set to `mpl`, but that was a long time ago. I think the reasoning was in case people copy the code into a text environment.

- A follow up issue could create a script notebooks to enforce this, but that's out of scope of this issue.

**Comment by Eric-Arellano** [comment]
> draw() (but with mpl set as default in ~/.qiskit/settings.conf)

That's cryptic. With docs, it's important that users running the code get the same result as the docs in the "happy case". 

In Slack, @kevinsung pointed out he's only seen MPL used. I agree. It's more interesting and useful to readers than the text output.

So I'd vote always using `mpl`.

**Comment by frankharkins** [comment]
If we go with `draw("mpl")`, should we use the `iqp` style?

**Comment by Eric-Arellano** [comment]
> Also, what's the "happy path"?

Essentially the default case. There are some edge cases for users following along with the docs, like that they themselves have set `~/.qiskit/settings.conf`. While we should be aware of that, our docs should be focused on doing the right thing for the majority of our users; the majority will not have `~/.qiskit/settings.conf` set.

I don't like our docs relying on `~/.qiskit/settings.conf` because it will be confusing for that default case why they are getting different results because they didn't realize they need to set up that file.

**Comment by frankharkins** [comment]
Ok so decision is `draw("mpl")` with default style. I'll close this but feel free to reopen if anyone disagrees.

**Comment by Eric-Arellano** [comment]
> with default style.

The default is going to change in Qiskit 1.0 from `clifford` to `iqp`. Abby M thinks we should be using `iqp` for everything. Anytime that we have `.draw("mpl")`, we need to add `style="iqp'`, and regenerate the images.

**Comment by kevinsung** [comment]
We don't want the code to have an argument that's going to become unnecessary, though, right? Can't we just leave the code as is, and let the pictures change later?

**Comment by Eric-Arellano** [comment]
> We don't want the code to have an argument that's going to become unnecessary, though, right?

It's not the end of the world imo. We can remove it once Qiskit 1.0 is released. 

> Can't we just leave the code as is, and let the pictures change later?

Abby M things it's important that we use the iqp style when on an ibm.com site.

**Comment by javabster** [comment]
Taking another look at this and given all the other stuff we have to do for the 1.0 milestone I'm fine with dropping this. It's important to have the styling of the images match the branding of IQP, but as the default is going to change to the IQP colours anyway when 1.0 comes out I would rather we not waste resources fixing this only to un-fix it later.

What we do need to do is make sure that all code blocks are using the `mpl` styling (i.e. not text or latex) and make sure to rerun all the notebooks with 1.0 to get the new styles once 1.0 comes out
