### ISSUE TITLE
Add an Overview page to the Test section

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#29]
The Test section should have an overview page explaining what the "test" phase is, similar to what we already have for the [build section](https://docs.quantum-computing.ibm.com/build)

This page should include a section about when the use of simulators are appropriate, and what the limits are. Generally we want to strike a balance between documenting this part of the workflow while encouraging people to move on to larger experiments on real hardware as quickly as possible

**Comment by abbycross** [comment]
First pass completed in https://github.ibm.com/IBM-Q-Software/iqp-channel-docs/pull/804. Still need to clarify when the use of simulators are appropriate
