### ISSUE TITLE
Figure out how to do Qiskit release notes in the future

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/documentation#294]
Relates to https://github.com/Qiskit/documentation/issues/281. 

Qiskit has been using Reno, which they're happy with. A key feature is that Reno allows them to write cross-references to the API docs easily. It's not feasible to expect them to instead write the cross-reference directly to docs.quantum-computing.ibm.com, and it's error prone to have them write API references as relative links like `[foo](../api/qiskit/)` as we would do in this repository because they don't have the API reference markdown files in this repository to validate that the references exist.

The issue is that Reno outputs in RST and we need to output it to Markdown or MDX. 

--

I investigated https://towncrier.readthedocs.io and https://scriv.readthedocs.io, but they won't handle our requirement for cross-references. I don't think they're viable.

--

So, our options seem to me to be:

1. Automate converting RST to Markdown. Or,
2. Use our API generation script to convert the Sphinx-generated HTML into Markdown.

**Comment by frankharkins** [comment]
> Use our API generation script to convert the Sphinx-generated HTML into Markdown.

This is what I used in #346 and #352. It seems to work well, so I propose continuing with it.

**Comment by Eric-Arellano** [comment]
Thanks! I opened https://github.com/Qiskit/documentation/issues/359 to track getting release notes to work automatically with future releases.
