### ISSUE TITLE
Replace "What is Qiskit" section

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#30]
The docs should have a page defining Qiskit, designed to be a "single source of truth" that others can refer to. Ideally when people google "what is qiskit" this should be the first page they see.

## What the new page should cover:

- Qiskit, Primitives, Runtime, Provider
- Qiskit ecosystem, i.e. what is not Qiskit
- maybe: information about qiskit 1.0? some background info about historical versions/naming?
- maybe: introduction to Qiskit Patterns?

## SME collaborators (involve for planning and review):
@lerongil , Tushar, Blake, @1ucian0 , @javabster 

## supporting resources:

Qiskit definition from Qiskit readme: 

> Qiskit is an open-source SDK for working with quantum computers at the level of extended quantum circuits, operators, and primitives.
> 
> This library is the core component of Qiskit, which contains the building blocks for creating and working with quantum circuits, quantum operators, and primitive functions (sampler and estimator). It also contains a transpiler that supports optimizing quantum circuits and a quantum information toolbox for creating advanced quantum operators
>

**Comment by javabster** [comment]
This issues needs a rethink, putting on hold for now

**Comment by abbycross** [comment]
This material was removed from the Start/index page to streamline the content -- the suggestion was to possibly move the open source stats/shoutout to a What is Qiskit page -- leaving it here so it doesn't get lost:


> - **Scalable and flexible quantum software**. 
> 
>   IBM Quantum is committed to open-source innovation. Preferred by 81% of quantum programmers[^2], the Qiskit software development kit works with eight different hardware manufacturers, making it the lingua franca of quantum computing, and its circuit optimization is the most advanced (seven times faster utility-scale circuit transpilation than competing frameworks). Build quantum circuits and operators in Qiskit, the transpile and run on quantum systems using primitives, a simplified interface for circuit execution. When you pair Qiskit with Qiskit Runtime, you'll benefit from seamless circuit execution powered by advanced runtime compilation, error suppression, and error mitigation techniques.  
> 
> [^2]: 2022 Unitary Fund survey findings.
