### ISSUE TITLE
Refactor "Introduction to Primitives" page

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#34]
This page should focus on teaching the overall concepts of primitives (the base definition in Qiskit and the Runtime implementations), rather than showing the code of how to use them which is covered in later pages

```[tasklist]
### Tasks
- [ ] Rename to "What are Primitives"?
- [ ] Replace this file with the `build-with-primitives.mdx` from iqp-channel-docs repo that was never released
```

**Comment by abbycross** [comment]
As I compare the [build-with-primitives file](https://github.ibm.com/IBM-Q-Software/iqp-channel-docs/blob/a5430e9dba47b13f708d645c2ca44947642a8419/docs/build/build-with-primitives.mdx) with [what we have now](https://docs.quantum-computing.ibm.com/build/primitives), they are very similar.  @javabster would you suggest we remove particular sections? There isn't really much code in the current version.

**Comment by abbycross** [comment]
Opened a PR here: https://github.ibm.com/IBM-Q-Software/iqp-channel-docs/pull/811

**Comment by javabster** [comment]
yeah i believe the original intent was to remove the page we have now and replace it with the [build-with-primitives file](https://github.ibm.com/IBM-Q-Software/iqp-channel-docs/blob/a5430e9dba47b13f708d645c2ca44947642a8419/docs/build/build-with-primitives.mdx), but for whatever reason it never got deployed to the current onedocs prod
