### ISSUE TITLE
Add more information to page on dynamic circuits considerations and limitations

### ISSUE THREAD

**Issue by kevinsung** [Qiskit/documentation#357]
### URL, if applicable

The article being added in https://github.com/Qiskit/documentation/pull/356

### Describe the new content you are requesting.

Request from @taalexander :

>Perhaps we should add a small section on
>- control-flow characteristic latencies
>- Limitations on IO for conditional measurements
>- Limitations on the number of measurements within a period of time?

### If this new content request is accepted, do you want to write the content?

I only want to review the material when it's finished

**Comment by abbycross** [comment]
Who would be a good SME for this? @SooluThomas would you be or know someone who would be?

**Comment by taalexander** [comment]
Soolu would be a great start. It might be a good idea to maybe start with a conversation/requests in #ws-qcf-compiler to get input/interest from the team?

**Comment by abbycross** [comment]
@SooluThomas I don't have access to the #wf-qcf-compiler Slack channel -- would you be able to post to that channel and relay the request for input for this issue? Thanks :)

**Comment by abbycross** [comment]
@taalexander @SooluThomas @kevinsung 
I'm revisiting this issue, and was going to re-post in the ws-qcf-compiler channel, but I find it's archived :) Do we still need this issue and if so do we know who can help write it?
