### ISSUE TITLE
Link checker: validate Qiskit release notes

### ISSUE THREAD

**Issue by arnaucasau** [Qiskit/documentation#368]
Currently, we skip the release notes validation:

https://github.com/Qiskit/documentation/blob/20843983fb3f16903625319b7feb1be5b3897a2e/scripts/commands/checkLinks.ts#L164-L166

To validate the release notes, we shouldn't do it by default because we want our validation to be fast with internal links. Instead, we should take the same approach as with the external links and use an extra argument called `--release_notes` to decide when we want to check them.

### Bonus credit: Skip an entire folder

Sometimes, we need to skip the validation of all the files in a whole directory. It would be great to have something similar to the ignore mechanism implemented in #338 where we ignore the links in specific files.

This mechanism should be able to skip sub-folders of different directories without having multiple entries. For example `docs/qiskit/*/release_notes` will ignore the sub-folder `release_notes` in every directory of `docs/qiskit`.

**Things to add**

- [x] Add validation of the latest release note by default
- [x] A dedicated argument to validate the release notes
- [x] A weekly cron job to validate all the release notes
- [x] A method to skip complete folders

**Comment by arnaucasau** [comment]
We don't have the time in CI without `zxMain` and validating the release notes, but I just tested it locally, and we have roughly 3 minutes without release notes and approximately 10 minutes with release notes.

**Comment by Eric-Arellano** [comment]
Oh wow. That's a big difference. So some ideas:

1. Only check the most recent release note file
2. Add a flag (CLI argument) to check release notes, and check those with a cron job that runs every week.
