### ISSUE TITLE
Add code example of retrieving Qiskit Runtime jobs from retired systems

### ISSUE THREAD

**Issue by Matt-Stypulkoski** [Qiskit/documentation#398]
### URL, if applicable

Addition to already existing example here: https://docs.quantum-computing.ibm.com/run/retired-systems#retrieve-a-job-from-a-retired-system

### Describe the new content you are requesting.

The code snippet can be something similar to this:

```
from qiskit_ibm_runtime import QiskitRuntimeService

# Load your IBM Quantum account(s). Replace "hub/group/project" with your desired instance
service = QiskitRuntimeService(channel="ibm_quantum", instance="hub/group/project")

# Retrieve a single job by id
job = service.job("<job_id>")

# Retrieve a batch of jobs. Filtering options can be found in the QiskitRuntimeService.jobs api reference
jobs = service.jobs(backend_name="<backend>")
```

We should also mention that users will need to use the specific provider (either QiskitRuntimeService or IBMProvider) from which a job was sent when retrieving it. So to retrieve a job sent through QiskitRuntimeService, they would need to run the job retrieval code specific to QiskitRuntimeService.

### If this new content request is accepted, do you want to write the content?

I can help the team by providing enough information to write the material

**Comment by abbycross** [comment]
I can't seem to tag you in the PR, but @Matt-Stypulkoski FYI, @beckykd made a PR to close this here: https://github.com/Qiskit/documentation/pull/423
