### ISSUE TITLE
Set up link checker

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/documentation#4]
We should make sure that internal links are valid for the state of the docs in the PR, i.e. HEAD. That is, if we reorganize HTML pages, that's fine as long as we update the right links.

External links should be valid no matter what.
```[tasklist]
### Tasks
```

**Comment by Eric-Arellano** [comment]
Some thoughts before I implement this:

## Don't copy over closed source checker

I was hoping to simply duplicate what we do in closed source, which starts up a server, uses a custom web crawler to find all links, and then checks if they're valid. 

This won't work well because starting up a server is non-trivial in this repository, since the infrastructure does not live here. Instead, we start up the server via Docker, which can be intimidating for docs contributors and also can be very slow. We want to keep the check easy and fairly fast to run locally.

## Use static analysis

Instead of starting a web server and crawling it, statically analyze the MDX and Jupyter notebook files to extract out their links. For internal links, simply check that the file exists. For external links, make a request.

Our Jupyter notebooks use Markdown syntax, so we can use the same Markdown parser between MDX and Jupyter. We'd use a Markdown parsing library for this.

> For internal links, simply check that the file exists.

That is advantageous because it's much faster and avoids the flakiness of network connections.

## Custom tooling

I wanted to use https://github.com/tcort/markdown-link-check, a popular tool to check links for Markdown. But it has two issues:

1. Can't handle the Jupyter notebooks
2. Makes live requests even for internal links, which is much slower

So, instead, we'd use a custom script, similar to how we do it in closed source. But with a focus on maintainability and reusing libraries for e.g. parsing Markdown.

**Comment by Eric-Arellano** [comment]
I talked it over with the original author of the link checker in closed source. We think the static analysis approach is reasonable given the context of this open source project. We'll still have the full link checker from closed source.

I recommend we split the implementation up into stages:

1. Validate internal links
2. (maybe) Improve internal links to check for anchors
3. Validate external links

The priority is internal links. It's fine to do external links in a later follow up.

**Comment by frankharkins** [comment]
> The hard part here is needing to extract out the valid anchors from our MDX and Jupyter files.

Actually, `markdown-link-extractor` also extracts all the anchors from the markdown files too. So you should be able to do

```typescript
markdownLinkExtractor(source).anchors
```

Maybe we should replace the list of filepath strings with a list of objects

```typescript
interface File {
  path: string
  links: Link[]
  anchors: string[]
}
```

Then you could do something like

```typescript
linkedFile = files.find(file => file.path === link.value)
if linkedFile.anchors.includes(link.anchor) {
   ...
```

**Comment by Eric-Arellano** [comment]
I split this out into the more granular https://github.com/Qiskit/documentation/issues/305 and https://github.com/Qiskit/documentation/issues/306. 

The core link checker has been added and works great thanks to @arnaucasau and @frankharkins. Thanks!
