### ISSUE TITLE
Compilation is used in place of transpilation

### ISSUE THREAD

**Issue by jyu00** [Qiskit/documentation#436]
### URL to the relevant documentation

https://docs.quantum.ibm.com/run/configure-runtime-compilation

### Select all that apply

- [ ] typo
- [ ] code bug
- [X] out-of-date content
- [ ] broken link
- [ ] other

### Describe the fix.

For a while we were using the word "compile" in place of "transpile". Looks like we are going back to "transpile" now (e.g. there is a whole section on transpile). But the linked page still use "compile", which should now be "transpile" to be consistent with the rest.

**Comment by blakejohnson** [comment]
This word choice is very much intentional to distinguish what the Primitives do from what a user does locally.

**Comment by blakejohnson** [comment]
Another comment to clarify. Transpile and compile reference different parts of the flow. Transpilation is something a user does locally (step 2 in the Qiskit pattern) prior to sending their job to a Primitive. "Runtime compilation" is what the Primitives do to make a user job executable.
