### ISSUE TITLE
different qubit chains of FakeTokyo between document and configuration image

### ISSUE THREAD

**Issue by JiwonI788** [Qiskit/documentation#469]
### URL to the relevant documentation

URL : https://docs.quantum.ibm.com/api/qiskit/qiskit.providers.fake_provider.FakeTokyo
github : qiskit.providers.fake_provider.FakeTokyo.md
```
00 ↔ 01 ↔ 02 ↔ 03 ↔ 04
 ↕        ↕        ↕        ↕  ⤫  ↕
05 ↔ 06 ↔ 07 ↔ 08 ↔ 09
 ↕. ⤫   ↕       ↕.  ⤫. ↕
10 ↔ 11 ↔ 12 ↔ 13 ↔ 14
 ↕       ↕  ⤫           ↕  ⤫  ↕
15 ↔ 16 ↔ 17     18     19
```

### Select all that apply

- [X] typo
- [ ] code bug
- [ ] out-of-date content
- [ ] broken link
- [ ] other

### Describe the fix.

qubit chains of FakeTokyo in the URL is different from the configuration image of FakeTokyo() command in Quantum Lab
Here is description of  FakeTokyo() command ouput.
```
00 ↔ 01 ↔ 02     03      04
 ↕        ↕  ⤫            ↕  ／  ↕
05 ↔ 06 ↔ 07 ↔ 08 ↔ 09
 ↕. ⤫   ↕       ↕.  ／. ↕
10 ↔ 11 ↔ 12 ↔ 13 ↔ 14
 ↕       ↕  ⤫           ↕  ⤫  ↕
15 ↔ 16 ↔ 17 ↔ 18     19
```

**Comment by frankharkins** [comment]
@JiwonI788 how did you generate the coupling map in quantum lab?

**Comment by frankharkins** [comment]
Closing as we don't control that file; see https://github.com/Qiskit/documentation/pull/491#issuecomment-1850547148.
