### ISSUE TITLE
[ REFACTOR ] combine qiskit "How-Tos" into a single "Simulate using the Qiskit reference primitives" page

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#47]
As part of the qiskit docs file migration we have moved the following "how to" guides to the Test section:
- (How To) Compute circuit output probabilities with Sampler primitive
- (How To) Compute an expectation value with Estimator primitive

we should combine these how-tos into a single page titled "Simulate using Qiskit reference primitives"

**Comment by abbycross** [comment]
Once @Eric-Arellano has finished converting to .mdx in #170, I will combine these into a single ipynb
