### ISSUE TITLE
Set up issue templates in qiskit and qiskit-ibm-runtime to redirect here

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/documentation#48]
@abbycross heard about GitHub allowing you to have an issue template that redirects you to another repository. We'd add this to qiskit and qiskit-ibm-runtime to make it clear to people that docs problems should go to this repo. 

I think that might be something like this? https://github.com/orgs/community/discussions/50220

This is on hold until we remove qiskit.org/documentation. Until then, it is legitimate to have docs issues in qiskit because its docs files are different than the ones here.

**Comment by Eric-Arellano** [comment]
Closed by @abbycross in https://github.com/Qiskit/documentation/pull/122. Thanks!

**Comment by abbycross** [comment]
Is this still needed? The API docs are still generated from qiskit/qiskit and /qiskit-ibm-runtime, so any changes to those docs would need to be reported to those repos. 

I'm trying to recall if we thought we needed to clarify in those repos that non-API docs issues should be opened here 🤣  Anyone remember @Eric-Arellano @javabster @beckykd ?

**Comment by abbycross** [comment]
[PR for qiskit-ibm-runtime here](https://github.com/Qiskit/qiskit-ibm-runtime/pull/1260)

[PR for qiskit/qiskit here](https://github.com/Qiskit/qiskit/pull/11373)

**Comment by Eric-Arellano** [comment]
Both have been merged. Thanks @abbycross !
