### ISSUE TITLE
Check in CI that every page renders

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/documentation#511]
This would have caught the issue in https://github.com/Qiskit/documentation/pull/510.

The only approach I can think of is to use the `./start` Docker image in CI to start up the server, then visit every doc page that we have in the repo. Make sure they each give back a 200.

This will slow down CI, but that's worth it.

--

Note that the closed source repo already have this check because when it builds the app, it checks every page beforehand. But it would be better to catch this error early.

**Comment by javabster** [comment]
I think adding something like selenium tests to our testing suites shouldn't add too much overhead if we keep them minimal: https://www.selenium.dev/documentation/webdriver/getting_started/first_script/

**Comment by Eric-Arellano** [comment]
I don't think we even need something that complex. It should be sufficient to do `python3 -m http.server`, statically find all our URLs by inspecting the `docs/` folder, and then making a GET request to each of those.

**Comment by Eric-Arellano** [comment]
I got started on this in https://github.com/Qiskit/documentation/pull/572. Some questions for @arnaucasau and @frankharkins (and others):

1. Do you think this makes sense for when we run the script?
    - The script is quite slow. On my M1, it takes ~2 minutes to check non-API docs. Granted, that's because I have Apple Silicon so Docker is really slow because it's built for Intel. 
    - So, in CI, only check non-API docs for every PR
    - Have our external link checker workflow check every night API docs & Qiskit release notes, including historical API docs
2. Do we want the script to auto-start the Docker image for you (`./docker`), or is it fine to have users need to start the server and we only eagerly validate at the beginning of the script that it's set up?
    - Normally, I'd say that the script should auto-set it up so it's easier to run the check
    - But, `./start` will fail if you don't have Docker running, and it also can be very slow to start the server if you have a "cold" (un-cached) build. That would complicate our code to ping if the server is up every N seconds. We'd want to use a library for exponential backoff:

https://github.com/Qiskit/documentation/blob/494e6b632e1de74e8d863a321d706494f45556a2/scripts/lib/webServer.ts#L20-L31

    - So, I personally prefer to keep it simple. I doubt people will even run this script much _locally_ and they'll rely on CI.
