### ISSUE TITLE
Switch Qiskit, Runtime, and Provider to have more precise source code links

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/documentation#517]
Thanks to https://github.com/Qiskit/documentation/pull/620, we now have source code links for these three projects back to GitHub. But those links only take you to the overall file and it would be better if we took you to the specific lines of code.

See https://github.com/Qiskit/qiskit_sphinx_theme/issues/186#issuecomment-1651974704 for how we'd do this. We'd also need to update this repository to know how to consume `sphinx.ext.linkcode`.

**Comment by melechlapson** [comment]
Hi Eric, Could this not jus tbe resolved by adding #L<line number> to the end of the URLs so that it will ink to the line in the file not just the file itself?

**Comment by Eric-Arellano** [comment]
> Could this not jus tbe resolved by adding #L to the end of the URLs so that it will ink to the line in the file not just the file itself?

That's the end state that we want, indeed. But we need an _automated_ way to get the specific line numbers. It's not realistic for a human to go and add the line numbers for every code object.

So, we need to switch the way that Sphinx generates the GitHub URLs. Right now, we're using `sphinx.ext.viewcode` which only takes us to the overall file. `sphinx.ext.linkcode` should let us instead have the specific line numbers.

**Comment by melechlapson** [comment]
I think I'd like to take on this issue. It would be my first contribution

**Comment by melechlapson** [comment]
@Eric-Arellano can you assign me this issue?

**Comment by Eric-Arellano** [comment]
Hey @melechlapson, great to hear you're interested in this one! So there will be two stages to implementing:

1. Figure out how to get `sphinx.ext.linkcode` working well in the source repositories themselves.
2. Improve our API generation script so that we can consume Sphinx's output and convert it into something understood by the docs application.

Those are sequential, so let's start with step 1. Even if things get busy and you don't have time to do step 2, it would still be a big help to figure out step 1.

To do this, you'll want to choose a Sphinx-based project and experiment with how to get useful URLs generated that link to specific lines of code. Reminder that the goal is specific lines of code; we already know how to link to the overall file. You may find it convenient to test with our example docs in `qiskit-sphinx-theme` since it's a simple set up designed to experiment: https://github.com/Qiskit/qiskit_sphinx_theme. You'd be using the `example_docs` directory.

As I mention in this comment https://github.com/Qiskit/qiskit_sphinx_theme/issues/186#issuecomment-1651974704, NumPy has interesting code for what we want: Numpy has interesting code that will link to the correct place in GitHub: https://github.com/numpy/numpy/blob/v1.25.0/doc/source/conf.py#L441

Start with seeing how the extension works with a project like qiskit-sphinx-theme, then we can start scoping out how to get our API generation script to work with it.

**Comment by Eric-Arellano** [comment]
Thanks for your work on step 1 in https://github.com/Qiskit/qiskit_sphinx_theme/pull/589, @melechlapson! That was useful for us to see how things work. 

Turns out, there is no step 2! This repository already does the right thing 🚀 See https://github.com/Qiskit/documentation/pull/849. Review appreciated.

So, the next steps are:

1. Get the file name logic working in https://github.com/Qiskit/qiskit_sphinx_theme/pull/589.
2. Once that is working, open up PRs in qiskit-ibm-provider, qiskit-ibm-runtime, and qiskit to switch to `sphinx.ext.linkcode`
3. We will regenerate the API docs with the better source links 🙌

**Comment by Eric-Arellano** [comment]
Qiskit is updated in https://github.com/Qiskit/documentation/pull/1144 and https://github.com/Qiskit/documentation/pull/1145. Thanks @melechlapson for your persistence on this issue! This is a huge improvement and I'm excited for it to go live on Monday 🙌
