### ISSUE TITLE
Design GitHub source code links

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/documentation#518]
This ticket is to track the visual design of https://github.com/Qiskit/documentation/issues/454.

# Current implementation

We simply use an external link on the same line as the code object's description. It always appears at the end of the code and is normal text - we don't do any funky floating or anything.

<img width="586" alt="Screenshot 2024-01-11 at 4 49 15 PM" src="https://github.com/Qiskit/documentation/assets/14852634/7828fec0-2126-45dd-a176-c1e8090f4e1d">

I suspect this design is probably fine other than weirdness with the padding. Note how the underline extends directly to the code. I couldn't fix this by adding extra whitespace in the content - it wouldn't work. I think we need to adjust the CSS. 

<img width="104" alt="Screenshot 2024-01-11 at 4 50 32 PM" src="https://github.com/Qiskit/documentation/assets/14852634/b35c9811-3174-4398-9592-8086b675c24a">

But what is tricky about adjusting the CSS is it will impact all inline code highlighting:

<img width="338" alt="Screenshot 2024-01-11 at 4 51 25 PM" src="https://github.com/Qiskit/documentation/assets/14852634/5b4d2fc7-9bd2-472a-94a3-0ad6f3b655b0">

Note that we're using padding-right for inline code, rather than margin-right, which would result in the background not being the shaded gray.

# Original notes

## What the old qiskit.org design looks like

<img width="714" alt="Screenshot 2023-12-12 at 12 46 18 PM" src="https://github.com/Qiskit/documentation/assets/14852634/bca8048f-3ec8-4978-83c9-43c610a0ebb4">

When you click the `[source]` link, it takes you a new webpage on qiskit.org with a copy of the source code:

<img width="794" alt="Screenshot 2023-12-12 at 12 46 54 PM" src="https://github.com/Qiskit/documentation/assets/14852634/fbdb3c5f-047a-4c06-8988-a52659d27f7b">

Our implementation will instead take you to GitHub.com, so be an external link.

Note how the old design handles the `#` icon to get the permalink for the current code object. This only happens on hover:

<img width="515" alt="Screenshot 2023-12-12 at 12 47 51 PM" src="https://github.com/Qiskit/documentation/assets/14852634/6aac227f-a9c9-4134-8177-1f063fced91d">

## Which code objects have links?

Note that not every single code object has a link, For example, in the first image in this issue, only `exception QiskitNatureError` has it, but not its method `with_traceback()`.

However, there are other places where methods do have their own link. (Methods are a lower information hierarchy than the class they belong to.)

<img width="1031" alt="Screenshot 2023-12-12 at 12 49 35 PM" src="https://github.com/Qiskit/documentation/assets/14852634/813114e1-c6ea-447a-bf10-01ec6c48364d">

So, I think the safest thing to design for is that both the top-level code object—like the class—and also the code objects one level lower—like methods—can have the link but they might not.

--

The link should probably show up on the same line as the name of the code object itself? But, it is common that the line will wrap:

<img width="1219" alt="Screenshot 2023-12-12 at 12 54 20 PM" src="https://github.com/Qiskit/documentation/assets/14852634/57a91300-08d9-4d3e-a9b7-ed524deec058">

## Copy for the link

We discussed in a meeting that `[source]` might be vague. We only used that name with qiskit.org because it's what Sphinx itself uses and we can't easily change it.

For the new Qiskit docs, maybe we want something more explicit like `[GitHub]`? Or `GitHub ↗`?

**Comment by gracelindsell** [comment]
@Eric-Arellano In the new [figma](https://www.figma.com/file/sNXucK1uMaZ8XXyLTZrdrs/OneDocs?type=design&node-id=4918%3A32646&mode=design&t=GtbayO3rDnjhf4QD-1) designs, I have updated 
<img width="675" alt="github example" src="https://github.com/Qiskit/documentation/assets/89415444/ff673cc9-e336-4c57-8633-ba530b462756">
so the padding is corrected. I think keeping it to Github instead of Source is more clear

**Comment by Eric-Arellano** [comment]
@gracelindsell yes to that part. My doubt is whether we should be changing the behavior for all code blocks outside of API docs. Look at this screenshot:

![image](https://github.com/Qiskit/documentation/assets/14852634/965138f1-86ea-4d35-8971-a9b11c1eae54)

Should that padding be there for `run()`? Or should it be a margin? Or less padding/margin either way?

**Comment by Eric-Arellano** [comment]
We discussed that the padding is too big in general. Rather than `0.5rem` which we think is roughly 8px, it should be about `0.25rem` which would be 4px. That will impact all inline code blocks.

But independently, we also need to figure out why the `GitHub` text has no margin between the code block, which differs from other code blocks we have like this `run()` example.

**Comment by gracelindsell** [comment]
@Eric-Arellano Right, any text or link that follows a code block should be 8px away from the code block, and thus 12px away from the text in the code block

**Comment by Eric-Arellano** [comment]
Closing this in favor of https://github.com/Qiskit/documentation/issues/856. Thanks, Grace!
