### ISSUE TITLE
[ DESIGN ] Update API Docs Styling

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/documentation#521]
Part of https://github.com/Qiskit/documentation/issues/479. This issue is focused on the visual design of the API docs.

Right now, API docs are not using design elements to accurately reflect information hierarchy. For example, no colors or indentation.

This is an example class:

<img width="957" alt="Screenshot 2023-12-13 at 1 37 26 PM" src="https://github.com/Qiskit/documentation/assets/14852634/aab175f4-e43d-4e2f-9de3-880b21baf92e">

Some methods:

<img width="501" alt="Screenshot 2023-12-13 at 1 38 13 PM" src="https://github.com/Qiskit/documentation/assets/14852634/1d261fd0-7045-4d03-8816-de997ceac91c">

A standalone function, but note that it starts after the `Return type QasmQobj | PulseQobj` text:

<img width="894" alt="Screenshot 2023-12-13 at 1 39 09 PM" src="https://github.com/Qiskit/documentation/assets/14852634/699e5033-8e83-40b6-8554-975cfda745ac">

## Compare to qiskit.org

These screenshots come from our repository for the Qiskit Sphinx Theme, the files starting with `api-docs-`: https://github.com/Qiskit/qiskit_sphinx_theme/tree/main/tests/js/tests.js-snapshots

A class with methods:

![image](https://github.com/Qiskit/documentation/assets/14852634/f4e6179e-567c-4a53-91fc-e29736679e51)

A module page showing a standalone function
![image](https://github.com/Qiskit/documentation/assets/14852634/9ec6fcc9-e0ad-481e-9df2-cca9b80d59dd)

**Comment by gracelindsell** [comment]
@Eric-Arellano [Here](https://www.figma.com/file/sNXucK1uMaZ8XXyLTZrdrs/OneDocs?type=design&node-id=4918%3A32646&mode=design&t=6Kl6eSdC8bNa6BbR-1) are the breakpoints for the API Docs styling. To the right please find a version without indentation for initial implementation

**Comment by Eric-Arellano** [comment]
Thanks! Implementation is tracked by https://github.com/Qiskit/documentation/issues/735 and https://github.com/Qiskit/documentation/issues/736, where I also put screenshots.
