### ISSUE TITLE
[ DISCUSSION ] Review docs section names

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#525]
We constantly get feedback that some of the names of the sections are difficult to understand. In addition there is some push to rename the sections to match the "Qiskit Patterns" titles. I am hesitant to push forward with changing the section names to be the Qiskit pattern names as I fear this will cause additional confusion.

I think it would be worth reviewing the current titles and see if there are better names we can come up with. I'd also like to consider the following as part of this issue:

- Do we have any user data/research about how people understand the current titles? I get the sense that "build", "transpile" and run are more easily understandable, however "verify" seems to be one that people struggle with
- Could we extend the length of the section titles to be more than one word? I think that part of the reason people struggle with understanding the names is because it's very difficult to convey the meaning of an entire section in a single word. For example
- could we re-design the landing page of docs to give more of an indication of what pages are in each section? I think just seeing which page names are in the section helps give some extra context. Other docs pages do similar things, e.g. the [stripe docs homepage](https://stripe.com/docs) does a similar thing with their "no-code" and "stripe hosted" sections on their homepage. Even if I don't no what "no-code" means I can get some understanding by looking at the page links underneath that section

**Comment by Eric-Arellano** [comment]
We now have a new home page design and top nav bar design, so I think this can be closed. We're working on implementing these changes in the next month.
