### ISSUE TITLE
SEO Audit

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#534]
I've noticed a few times when googling that old links from qiskit.org or IQP that no longer exist are showing up on the front page of the search results. I think we should do some sort SEO audit and see what we can do to de-prioritise old links and more highly prioritise high profile content. Also if there are just any general things we could be doing to improve our SEO that would be great. In the past we have been updating page metadata but I wonder if there's more we could be doing 🤔

**Comment by javabster** [comment]
related: https://github.com/Qiskit/documentation/issues/347#issue-1992669444

**Comment by Eric-Arellano** [comment]
We've chatted with the SEO team and I don't think there's more we could be doing. It took some time for qiskit.org's old SEO to switch over, and we're still negatively impacted by how older versions were prioritized, but we're doing what we can to address that.

We now have automated checks to ensure our metadata meets standards for guides pages.
