### ISSUE TITLE
Add warnings about sunsetting of cloud simulators

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#536]
The cloud based simulators are due to be sunset sometime in 2024. Before they are fully removed we should add some warnings to the docs pages letting people know when the simulators are going away and link them to alternative simulator docs.

The docs pages that currently discuss the cloud simulators:
- https://docs.quantum.ibm.com/verify/using-ibm-quantum-simulators
- https://docs.quantum.ibm.com/verify/cloud-based-simulators

Proposed warning text:
" As of [DATE] the IBM Quantum cloud-based simulators will be sunset, instead users are advised to use local simulators such as the [Qiskit Primitives](https://docs.quantum.ibm.com/verify/simulate-with-qiskit-primitives) or [Qiskit Aer Primitives](https://docs.quantum.ibm.com/verify/simulate-with-qiskit-aer)"

**Comment by abbycross** [comment]
FYI @pandasa123

**Comment by javabster** [comment]
closed by #1023
