### ISSUE TITLE
Broken Link Report 

### ISSUE THREAD

**Issue by lerongil** [Qiskit/documentation#540]
### URL to the relevant documentation

Below is a list of broken links reported: 

Getting links from: https://docs.quantum.ibm.com/transpile
├─BROKEN─ https://learning.quantum.ibm.com/tutorial/reduce-transpiled-circuit-depth-with-circuit-cutting (HTTP_404)

Finished! 78 links found. 66 excluded. 1 broken.
​
Getting links from: https://docs.quantum.ibm.com/transpile/qiskit-transpiler-service
├─BROKEN─ https://learning.quantum.ibm.com/tutorial/reduce-transpiled-circuit-depth-with-circuit-cutting (HTTP_404)

Finished! 65 links found. 62 excluded. 1 broken.
​
Getting links from: https://docs.quantum.ibm.com/transpile/defaults-and-configuration-options
├─BROKEN─ https://docs.quantum.ibm.com/_next/image?url=%2Fimages%2Ftranspile%2Fdefaults-and-configuration-options%2Ftranspiled-circuit.png&w=3840&q=75 (HTTP_520)

├─BROKEN─ https://learning.quantum.ibm.com/tutorial/reduce-transpiled-circuit-depth-with-circuit-cutting (HTTP_404)

Finished! 81 links found. 74 excluded. 2 broken.
​
Getting links from: https://docs.quantum.ibm.com/api/qiskit/qiskit.circuit.QuantumCircuit#quantumcircuit
├─BROKEN─ https://docs.quantum.ibm.com/api/qiskit/qiskit.org/documentation/tutorials/circuits/3_summary_of_quantum_operations (HTTP_404)

Finished! 1418 links found. 1354 excluded. 1 broken.
​
Getting links from: https://docs.quantum.ibm.com/api/qiskit-ibm-runtime/qiskit_ibm_runtime.QiskitRuntimeService
├─BROKEN─ https://auth.quantum-computing.ibm.com/api (HTTP_404)
├─BROKEN─ https://auth.quantum-computing.ibm.com/api (HTTP_404)

Finished! 118 links found. 116 excluded. 2 broken.
​
Getting links from: https://docs.quantum.ibm.com/api/qiskit-ibm-provider/qiskit_ibm_provider.IBMProvider
├─BROKEN─ https://auth.quantum-computing.ibm.com/api (HTTP_404)
├─BROKEN─ https://auth.quantum-computing.ibm.com/api (HTTP_404)
├─BROKEN─ https://auth.quantum-computing.ibm.com/api (HTTP_404)

Finished! 97 links found. 94 excluded. 3 broken.
​
Getting links from: https://docs.quantum.ibm.com/transpile/ai-transpiler-passes
├─BROKEN─ https://learning.quantum.ibm.com/tutorial/reduce-transpiled-circuit-depth-with-circuit-cutting (HTTP_404)

Finished! 60 links found. 59 excluded. 1 broken.

### Select all that apply

- [ ] typo
- [ ] code bug
- [ ] out-of-date content
- [X] broken link
- [ ] other

### Describe the fix.

There is no replacement for  https://learning.quantum.ibm.com/tutorial/reduce-transpiled-circuit-depth-with-circuit-cutting so these should simply be removed.

**Comment by beckykd** [comment]
@lerongil - we don't own the API topics.  I'll move the records of those broken links into a separate issue.

**Comment by abbycross** [comment]
Since everything that is part of this repo has been fixed, is this safe to close @beckykd @lerongil? I see related issue https://github.com/Qiskit/qiskit/issues/11481 and PR https://github.com/Qiskit/qiskit/pull/11294. Are there outstanding issues/PRs in the qiskit-ibm-runtime and qiskit-ibm-provider repos too?

**Comment by beckykd** [comment]
seems safe to close.

**Comment by Eric-Arellano** [comment]
I think we should deal with the https://auth.quantum-computing.ibm.com/api links first. Are those valid? If so, we'll keep them in the link checker ignore list. Otherwise we should update runtime: https://github.com/search?q=repo%3AQiskit%2Fqiskit-ibm-runtime%20https%3A%2F%2Fauth.quantum-computing.ibm.com%2Fapi&type=code

**Comment by beckykd** [comment]
> I think we should deal with the https://auth.quantum-computing.ibm.com/api links first. Are those valid? If so, we'll keep them in the link checker ignore list. Otherwise we should update runtime: https://github.com/search?q=repo%3AQiskit%2Fqiskit-ibm-runtime%20https%3A%2F%2Fauth.quantum-computing.ibm.com%2Fapi&type=code

They seem to be genuinely broken.  I already opened an issue for them to be dealt with in the code base.
