### ISSUE TITLE
[Docs] Explain session TTLs before using them

### ISSUE THREAD

**Issue by jyu00** [Qiskit/documentation#576]
**What is the expected feature or enhancement?**

The session docs talks about the iterative and max TTLs in the [Iterations and batching](https://qiskit.org/ecosystem/ibm-runtime/sessions.html#iterations-and-batching) section. However, it doesn't explain what these TTLs are until after, in the [How long a session stays active](https://qiskit.org/ecosystem/ibm-runtime/sessions.html#how-long-a-session-stays-active) section. 

**Acceptance criteria**

We should talk about the TTLs first. 

cc @beckykd

**Comment by beckykd** [comment]
Messaged @jyu00 about this.  She agrees that the current text is OK, but requested that we add in the TTL animation.  I'll find that and add it in.
