### ISSUE TITLE
Revert changes from issue #190 after server changes are made

### ISSUE THREAD

**Issue by mriedem** [Qiskit/documentation#582]
### URL, if applicable

https://docs.quantum.ibm.com/run/run-jobs-in-session#open-a-session for this part:

>If the first session job is canceled, subsequent session jobs will all fail.

https://docs.quantum.ibm.com/run/run-jobs-in-session#close-a-session for this part:

>Note that when you cancel the root job in the session (the job which has the same ID as the session), the session closes and fails any remaining queued jobs in the session.

### Describe the new content you are requesting.

The pay-go cloud channel and quantum (IQP) channel server side behaviors are going to change such that the docs changes for issue #190 can be reverted **once the server side changes are in production for both channels**.

With epic [Decouple session from root job](https://github.ibm.com/IBM-Q-Software/requirements-and-priorities/issues/341) the API is going to support explicitly creating a session rather than implicitly with the first job in the session such that the first (root) job and session have the same ID. With that decoupling we'll be able to revert the previous change where we would close the session and fail any remaining queued jobs, so we won't need those notes in the docs anymore.

I'm not sure if a qiskit-ibm-runtime issue exists for this yet, but eventually that code will need to change to create the session explicitly for [batch mode support](https://github.ibm.com/ibm-q-software/ws-qiskit-runtime-api/issues/380).

This issue is a placeholder to make sure we don't forget about the docs updates, but again don't make these until we've confirmed that the server sides changes in both channels is in production.

### If this new content request is accepted, do you want to write the content?

I can help the team by providing enough information to write the material

**Comment by mriedem** [comment]
@abbycross @beckykd This is no longer blocked.

**Comment by beckykd** [comment]
@abbycross, I'm in the process of updating all of the session docs right now, so I can just make this change with that PR.

**Comment by beckykd** [comment]
https://github.com/Qiskit/documentation/pull/783
