### ISSUE TITLE
Latex math sometimes renders incorrectly due to Katex vs Mathjax

### ISSUE THREAD

**Issue by kevinsung** [Qiskit/documentation#59]
### URL to the relevant documentation

https://docs.quantum-computing.ibm.com/api/qiskit/qiskit.circuit.library.RYGate
https://docs.quantum-computing.ibm.com/api/qiskit/qiskit.circuit.library.RYYGate
https://docs.quantum-computing.ibm.com/api/qiskit/qiskit.circuit.library.RYYGate
https://docs.quantum-computing.ibm.com/api/qiskit/qiskit.circuit.library.RYYGate

... probably many others

### Select all that apply

- [ ] typo
- [ ] code bug
- [ ] add new content
- [ ] out-of-date content
- [ ] it's just wrong
- [X] other

### What is the documentation issue/request?

The LaTeX does not render properly on my computer (running Google Chrome on Fedora).

Example:
![image](https://github.com/Qiskit/documentation/assets/4296166/f82bc5d8-4f5b-411b-a1da-9bd90cbd4728)

**Comment by abbycross** [comment]
Thank you @kevinsung! @axelhzf are you able to help with how this is rendered? I can propose whatever change is needed in the qiskit/qiskit repo.

**Comment by abbycross** [comment]
Hi @Eric-Arellano -- I see you're here too :) I know Axel has fixed this issue in the past, but if you can help with it too that would be wonderful!!

**Comment by jhwatrous** [comment]
There's unnecessarily complicated LaTeX code here for something simple and it's not rendering properly. For example, for $R_Y$ this code should work:

```
$$
R_Y(\theta) = \exp\left(-i \frac{\theta}{2} Y\right) = 
\begin{pmatrix}
   \cos\left(\frac{\theta}{2}\right) & -\sin\left(\frac{\theta}{2}\right) \\
   \sin\left(\frac{\theta}{2}\right) & \cos\left(\frac{\theta}{2}\right)
\end{pmatrix}
$$
```

$$
R_Y(\theta) = \exp\left(-i \frac{\theta}{2} Y\right) = 
\begin{pmatrix}
   \cos\left(\frac{\theta}{2}\right) & -\sin\left(\frac{\theta}{2}\right) \\
   \sin\left(\frac{\theta}{2}\right) & \cos\left(\frac{\theta}{2}\right)
\end{pmatrix}
$$

I suspect that the problem is with the use of the `align` environment, which may not be implemented. (And it isn't really needed here is it? Nothing is being aligned, and anyway `aligned` is typically used *inside* of math mode for alignment, not `align`.)

If this works let me know and I'd be happy to provide LaTeX code that works for all of these.

**Comment by kevinsung** [comment]
> There's unnecessarily complicated LaTeX code here for something simple and it's not rendering properly. For example, for RY this code should work:
> 
> ```
> $$
> R_Y(\theta) = \exp\left(-i \frac{\theta}{2} Y\right) = 
> \begin{pmatrix}
>    \cos\left(\frac{\theta}{2}\right) & -\sin\left(\frac{\theta}{2}\right) \\
>    \sin\left(\frac{\theta}{2}\right) & \cos\left(\frac{\theta}{2}\right)
> \end{pmatrix}
> $$
> ```
> 
> RY(θ)=exp⁡(−iθ2Y)=(cos⁡(θ2)−sin⁡(θ2)sin⁡(θ2)cos⁡(θ2))
> 
> I suspect that the problem is with the use of the `align` environment, which may not be implemented. (And it isn't really needed here is it? Nothing is being aligned, and anyway `aligned` is typically used inside of math mode for alignment, not `align`.)
> 
> If this works let me know and I'd be happy to provide LaTeX code that works for all of these.

The source itself does not use `align`: https://github.com/Qiskit/qiskit/blob/523ea748b34cc1c007eda6e9e673ab6742b304a0/qiskit/circuit/library/standard_gates/ry.py#L43-L49

It appears that the `align` environments are being added by the documentation generation software. @axelhzf @Eric-Arellano do you know what's going on?

**Comment by kevinsung** [comment]
Ok it appears that it's Sphinx which is adding the `align`. Specifically, the MathJax code is
```
\begin{align}\begin{aligned}\newcommand{\th}{\frac{\theta}{2}}\\\begin{split}RY(\theta) = \exp\left(-i \th Y\right) =
    \begin{pmatrix}
        \cos\left(\th\right) & -\sin\left(\th\right) \\
        \sin\left(\th\right) & \cos\left(\th\right)
    \end{pmatrix}\end{split}\end{aligned}\end{align}
```
I found this by inspecting the docs build at https://github.com/Qiskit/qiskit/actions/runs/7140175059 (am currently having trouble building locally). I inspected a few other examples and only the ones with the `align` environments failed to render. It looks like Sphinx will automatically add "wrapper" environments to the LaTeX, so far not sure what causes it to add the `align` environment...

**Comment by Eric-Arellano** [comment]
Thanks, @kevinsung! Some other things to experiment with:

1. Confirm that removing the align environment does fix how things render with the IBM docs. Do this by previewing the docs locally via `./start` or a PR preview.
2. Figure out if we can have Sphinx stop setting the environment
3. Or, add code to post-process the HTML. Most of this post-processing currently happens in `sphinxHtmlToMarkdown.ts`.

**Comment by kevinsung** [comment]
It turns out that the issue is not the `align`, but rather, the use of `newcommand`. What engine is being used to render the LaTeX? Why can't it handle `newcommand`?

**Comment by Eric-Arellano** [comment]
We use https://katex.org. I'll DM you where to look at the internal code.

**Comment by kevinsung** [comment]
This issue has been resolved in https://github.com/Qiskit/qiskit/pull/11435 by fixing the tex in the source so that it compiles in KaTeX. That PR also switches the documentation build process for the Qiskit repository to use KaTeX instead of MathJax; using the same rendering software for both builds should help prevent similar issues from arising in the future.

**Comment by Eric-Arellano** [comment]
Additionally, @axelhzf made some changes to the docs application to handle Katex better. The original broken pages are now rendering properly in prod.

Thanks @kevinsung and @jhwatrous for the bug report, and @axelhzf and @kevinsung for the thorough fix!
