### ISSUE TITLE
[ EPIC] Add open source related information to "Additional resources" tab

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#605]
Because of the time crunch of the last milestone we never got round to finding a good home in docs for some of the open-source related information including:

- version strategy
- operating system support
- contributing guidelines + maintainer guidelines
- deprecation policy

some of these pages were added to https://docs.quantum.ibm.com/start/install, others were just added as markdown files in the qiskit repo. But the current placement doesn't feel like it exactly "fits" so we should come up with a better place.

Terris also started looking into designs for a "contributing" section of the docs, I think it would be good to re-open this discussion now that things have calmed down a bit

```[tasklist]
### Tasks
- [ ] #796
- [ ] #716
- [ ] https://github.com/Qiskit/documentation/issues/1698
```

**Comment by abbycross** [comment]
Just so we don't lose it, mentioning here that another place where the open-source info got placed is on the Support page: https://docs.quantum.ibm.com/support#open-source-governance

**Comment by javabster** [comment]
related #716

**Comment by Eric-Arellano** [comment]
We plan to have a new "Additional resources" section in the top nav bar. Open source will live here. We can use this epic to plan creation of the content for that folder.

**Comment by abbycross** [comment]
Right now the Error Code Registry is under the API reference menu - is it a candidate for "Additional resources"?

**Comment by Eric-Arellano** [comment]
> Right now the Error Code Registry is under the API reference menu - is it a candidate for "Additional resources"?

We were thinking that stays under API references since it's very API-like, but it could be moved if we want. Migration guides would move, though, since they never really belonged in API reference.

**Comment by Eric-Arellano** [comment]
This is now live. The ecosystem documentation is tracked by https://github.com/Qiskit/documentation/issues/1711, and citations / FAQs by https://github.com/Qiskit/documentation/issues/716 and https://github.com/Qiskit/documentation/issues/1699
