### ISSUE TITLE
[ REMOVE ] cloud simulator pages

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#607]
Once the cloud simulator service has been removed, the following pages should be removed from docs:

- https://docs.quantum.ibm.com/verify/using-ibm-quantum-simulators
- https://docs.quantum.ibm.com/verify/cloud-based-simulators

Also remove the Test setup example from the IQP setup section on the start/install page.

depends on: https://github.com/Qiskit/documentation/issues/536

**Comment by beckykd** [comment]
Is there an issue we can watch for this, or a date we're waiting for?

**Comment by abbycross** [comment]
Completed with #1425
