### ISSUE TITLE
Add names of contributors to each page

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#608]
In the spirit of the docs being open-source I think it would be a nice feature to add an automatically generated footnote to each docs page with the usernames and a word of thanks to the people that contributed to that particular page. Not anything too big, but just a small note at the bottom of the page would suffice

**Comment by javabster** [comment]
I don't think we need such a big "thankyou" title, I think this can just be a couple of lines and text with no header

**Comment by gracelindsell** [comment]
[Here](https://www.figma.com/design/sNXucK1uMaZ8XXyLTZrdrs/IBM-Quantum-Documentation?node-id=7174-39884&t=GIeSutsuCJkUNVjg-1) are the updated designs without a header
