### ISSUE TITLE
Audit all non-api ref code blocks in preparation for qiskit 1.0

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#609]
before the release of qiskit 1.0 in feb we should check that all code cells in docs are runnable using qiskit 1.0 code. This could be done running the notebooks locally with 0.46 or the 1.0 pre-release  installed (once either is released).

The goal is for none of the code blocks to break or throw deprecation warnings with 1.0

**Comment by frankharkins** [comment]
Update: All notebooks seem to work fine with `qiskit[all]~=1.0.0b1`, I'll double-check the outputs tomorrow and also check the markdown code blocks.
