### ISSUE TITLE
Parsing error in runtime IBMBackend page

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/documentation#610]
### URL to the relevant documentation

https://docs.quantum.ibm.com/api/qiskit-ibm-runtime/qiskit_ibm_runtime.IBMBackend#run

### Select all that apply

- [ ] typo
- [X] code bug
- [ ] out-of-date content
- [ ] broken link
- [ ] other

### Describe the fix.

Look like the API docs are being parsed incorrectly (see "or" / "to")

<img width="827" alt="Screenshot 2024-01-03 at 10 51 44" src="https://github.com/Qiskit/documentation/assets/36071638/36fb0b49-6e6e-41a5-a30f-fea94a1f6149">

**Comment by arnaucasau** [comment]
It seems like the problem was in the HTML. I created a [PR](https://github.com/Qiskit/qiskit-ibm-runtime/pull/1510) in the runtime repo to fix it :+1:
