### ISSUE TITLE
Parsing error in RuntimeEncoder page

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/documentation#611]
### URL to the relevant documentation

https://docs.quantum.ibm.com/api/qiskit-ibm-runtime/qiskit_ibm_runtime.RuntimeEncoder#attributes

### Select all that apply

- [ ] typo
- [X] code bug
- [ ] out-of-date content
- [ ] broken link
- [ ] other

### Describe the fix.

Looks like the attributes are not being parsed correctly

<img width="827" alt="Screenshot 2024-01-03 at 11 58 06" src="https://github.com/Qiskit/documentation/assets/36071638/0160f562-989b-4d34-aab4-2cec9ace4dcd">

**Comment by Eric-Arellano** [comment]
Relates to https://github.com/Qiskit/documentation/issues/224

**Comment by frankharkins** [comment]
Closing as duplicate of #224
