### ISSUE TITLE
Add links to GitHub for non-API pages

### ISSUE THREAD

**Issue by beckykd** [Qiskit/documentation#613]
The source code is hard to find.  There are plans to link to source code as appropriate from topics with example code (#454 ), but we should also just help people find it.

**Comment by Eric-Arellano** [comment]
> but we should also just help people find it.

What does this mean?

**Comment by beckykd** [comment]
> > but we should also just help people find it.
> 
> What does this mean?

I mean, it's really hard to find the actual source code right now.

**Comment by Eric-Arellano** [comment]
Sure, but I'm not understanding what this means once we have https://github.com/Qiskit/documentation/issues/454 in place. Are you suggesting the non-API docs link more frequently to GitHub? Or we add GitHub to the top or left navigation?

**Comment by Eric-Arellano** [comment]
Oh. So this is the suggestion to have something like this edit button on every non-API page which will take you back to the Qiskit/documentation repository.

Other projects do that too:

<img width="819" alt="Screenshot 2024-01-10 at 10 50 15 AM" src="https://github.com/Qiskit/documentation/assets/14852634/04d2d250-9f50-4476-af61-9c95cbfeecee">

**Comment by beckykd** [comment]
> If possible I think it could be a nice addition to the non-api-ref pages as well, what do you think?

Oh - so that comment is to have the button on every page; not to just add a link somewhere - got it

**Comment by beckykd** [comment]
We're going to wait for the infra fix
