### ISSUE TITLE
Possibility for hosting a full documentation-mirror site

### ISSUE THREAD

**Issue by glebx-f** [Qiskit/documentation#621]
### Feedback

The domain `qiskit.org`, where the documentation was hosted previously, has no geographical limitations. However, this is not the case for the new location `docs.quantum.ibm.com`. As Qiskit is an open source project, a good idea is to provide capabilities for making community-hosted mirrors possible. Docs preview may be the option and it was greatly enhanced in #150, but "the live preview has a worse UI", so this method won't be very suitable for publicly available mirror. The main drawback is the lack of navigation and search bar. Is there a way to build/host the documentation that replicates original UI as close as possible?

**Comment by Eric-Arellano** [comment]
Hey @glebx-f, thank you for the feedback! I acknowledge this is frustrating.

There unfortunately is not a way to get the original UI other than docs.quantum.ibm.com. The preview from https://github.com/Qiskit/documentation/pull/150 is the best that we're able to provide for now in terms of community hosting, along with the API docs still being accessible via Sphinx builds from CI for the respective open source repositories, like https://github.com/Qiskit/qiskit/actions/workflows/docs_deploy.yml.
