### ISSUE TITLE
Ideas to simplify API pipeline

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/documentation#63]
Follow up to https://github.com/Qiskit/documentation/issues/9. The initial focus was simply copying it over as is.

Some possible ideas:

* Get rid of the GitHub API client code and have another way of determining the versioning, even the user specifying it.
* Don't pull HTML docs from published websites. Instead do something like getting it from CI at specified commits. That will make the script deterministic, remove a synchronization problem of requiring the docs to already be published, and facilitate us having multiple versions of the API docs.
* Have the user specify which of the 3 packages to regenerate.

**Comment by frankharkins** [comment]
> Don't pull HTML docs from published websites. Instead do something like getting it from CI at specified commits. That will make the script deterministic, remove a synchronization problem of requiring the docs to already be published, and facilitate us having multiple versions of the API docs.

I imagine you've already considered this, but maybe we can get Sphinx to output something nicer than HTML? A quick search brings up [`sphinx-markdown-builder`](https://github.com/liran-funaro/sphinx-markdown-builder)), and Sphinx supports a few different [builders](https://www.sphinx-doc.org/en/master/usage/builders/index.html) that may (or may not) be easier to work with.

**Comment by Eric-Arellano** [comment]
> A quick search brings up [sphinx-markdown-builder](https://github.com/liran-funaro/sphinx-markdown-builder)), and Sphinx supports a few different [builders](https://www.sphinx-doc.org/en/master/usage/builders/index.html) that may (or may not) be easier to work with.

Yeah, unfortunately they all aren't very robust :( the markdown builder fails to parse Qiskit, and the builtin Sphinx builders have issues too. 

The medium term plan is that we will probably want to migrate to https://vemel.github.io/handsdown/ rather than this custom Sphinx -> MDX parser.

**Comment by Eric-Arellano** [comment]
Closing in favor of more granular tracking:

* you can already choose which project to run
* we'll no longer get the version from GitHub as part of https://github.com/Qiskit/documentation/issues/77
* https://github.com/Qiskit/documentation/issues/311 tracks building from CI rather than the live site.
