### ISSUE TITLE
Gate error: Defined

### ISSUE THREAD

**Issue by zlatko-minev** [Qiskit/documentation#636]
### URL, if applicable

https://docs.quantum.ibm.com/api/qiskit-ibm-runtime/qiskit_ibm_runtime.IBMBackend#properties

### Describe the new content you are requesting.

In searching the documentation, and it appears to be challenging to find explicit information explaining the specific gate error metric reported for the backend properties in Qiskit. It is not explicitly mentioned whether the reported metric is related to RB Fidelity, average channel fidelity, entanglement fidelity, or another specific metric. Having this information would be valuable for theoreticians and users to better understand the quality and characteristics of the quantum device. It may be beneficial for the Qiskit documentation to specify the exact nature of the gate error metric for clarity and transparency.

For reference if useful,
<img width="661" alt="image" src="https://github.com/Qiskit/documentation/assets/15937254/f817e0ab-83b9-4cac-817e-378fd984b8d8">

### If this new content request is accepted, do you want to write the content?

I can help the team by providing enough information to write the material

**Comment by abbycross** [comment]
Thanks @zlatko-minev! To clarify: is this content you expect to be in the qiskit-ibm-runtime API docs, or in the non-API docs (somewhere in Start, build, transpile, verify, run)?

**Comment by zlatko-minev** [comment]
I believe that this information is closely tied to the specific quantum provider and backend, and it would be best suited for inclusion in the runtime documentation. However, I don't have a strong preference regarding its placement; I simply believe it should be accessible somewhere within the documentation. It's worth noting that different quantum providers may opt to report different metrics of gate fidelity, so the choice of metric may be more provider-specific than fundamental to Qiskit Terra.

**Comment by javabster** [comment]
good people to talk to about this issue: Andrew Wack and David McKay

**Comment by dcmckayibm** [comment]
It's average gate fidelity; I figured that was noted somewhere but maybe it isn't

**Comment by dcmckayibm** [comment]
maybe should be added here too https://docs.quantum.ibm.com/run/system-information

**Comment by abbycross** [comment]
@jyu00 which API docs need to reflect this clarification? I can open an issue in those repos.

@zlatko-minev @dcmckayibm would it be particularly useful to also clarify this on the detailed info for each system in the UI?  For example, somewhere on the card below: 
<img width="1049" alt="Screenshot 2024-04-15 at 2 20 33 PM" src="https://github.com/Qiskit/documentation/assets/28769477/14538c2b-9ea1-433d-9b6f-8b8c3dd82c04">

**Comment by dcmckayibm** [comment]
I think something like that little (i) next to processor type would make sense @francabrera

**Comment by dcmckayibm** [comment]
Beside median ECR error (in the example above) and median CZ error (for heron). EPLG already has a tooltip.

**Comment by abbycross** [comment]
Here is the issue for Fran's team https://github.ibm.com/IBM-Q-Software/sw-iqx-web/issues/5299
Please let me know if I missed any salient details!

In the meantime I am drafting for our docs the following:

> Note that the metric for median ECR error (for Eagle processors) and median CZ error (for Heron processors) is the average gate fidelity, which is the average over all possible input states of the fidelity between the state produced by the actual operation and the state produced by the ideal operation.

This would go on the [System information](https://docs.quantum.ibm.com/run/system-information) page, in an "Note" box.

**Comment by abbycross** [comment]
Done!
