### ISSUE TITLE
Issue templates are misbehaving

### ISSUE THREAD

**Issue by beckykd** [Qiskit/documentation#650]
### URL to the relevant documentation

Bug or New content issue template

### Please describe the UI problem.

The issue templates (this has happened on Bug and New content) are making you fill out non-required fields before you can submit the issue.  Here's a snippet from the New content template.  You can see that the URL one is not marked required. 

  - type: textarea
    attributes:
      label: URL, if applicable
      description: Provide a URL and section name/paragraph where the new content belongs, if applicable.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Describe the new content you are requesting.
      description: >
        Please give a clear and concise description. What value does the new content bring?
    validations:
      required: true

**Comment by abbycross** [comment]
Hm. I tried both types of issues and I was able to submit without filling in the URL field. But if I didn't have the title field filled out, the submit button remained unclickable. Had you added a title to the issues you tried out @beckykd ?

**Comment by Eric-Arellano** [comment]
Can this be closed?

**Comment by beckykd** [comment]
Here's something odd.  If I fill out just the required information, then scroll up and back down, I can submit it.  But otherwise, I can't:  
![Screenshot 2024-02-12 085445](https://github.com/Qiskit/documentation/assets/66339736/befaff16-7cad-47cf-afda-372a3aad051c)
![Screenshot 2024-02-12 085615](https://github.com/Qiskit/documentation/assets/66339736/c3c038fe-9dd1-481c-88e7-e70a3e702010)


Maybe we just can't do anything about that.

**Comment by Eric-Arellano** [comment]
Weird. 

> Maybe we just can't do anything about that.

I think the best we can do is file a bug report. A lot of times devs don't know about bugs like this, so it's really helpful for them to submit, if you're willing https://support.github.com/contact/bug-report

I'm going to close this for our repo as not fixable by us.
