### ISSUE TITLE
update hello world post-1.0

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#699]
speak to Derek

**Comment by HuangJunye** [comment]
Love the description of this issue. Is there any details on this? I recently took a look at the hello world example and would like to suggest a few things if there is big change coming up for the hello world example.

In short, I find the current hello world example hard to explain. Was there a strong reason to use observable and estimator versus the good old introduction to qiskit tutorial where sampler and get counts were used? I personally think that was easier to understand for first time users and therefore better suited for a hello world example.

**Comment by beckykd** [comment]
> Love the description of this issue. Is there any details on this? I recently took a look at the hello world example and would like to suggest a few things if there is big change coming up for the hello world example.
> 
> In short, I find the current hello world example hard to explain. Was there a strong reason to use observable and estimator versus the good old introduction to qiskit tutorial where sampler and get counts were used? I personally think that was easier to understand for first time users and therefore better suited for a hello world example.

Jay prefers us to show Estimator and updated the file on Oct. 1 to do so.
