### ISSUE TITLE
Figure out folder structure for translations

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/documentation#7]
We need to figure out URL scheme and folder organization for docs, which are tied together.

## URL/file names will stay the same

That is, we don't try translating `/start/my_file` to `/empieza/mi_archivo` for example. It's a common convention in localization to use consistent URLs and it makes everything much easier to implement.

## Proposed URL scheme

English URLs will still the same w/o language in the URL/file, e.g. `/start`. But English _does_ still need to show up in the language toggle.

Translations will start with `/<lang>` in their URL, e.g. `/es/start` and `/fr/run`. Everything after in the URL will be the same. Each language will have a full copy of the normal documentation but translated, and excluding API docs.

To communicate the language information to the docs app, we could reuse `_package.json` from https://github.com/Qiskit/docs/issues/8? Or add `_language.json`? Whatever makes the most sense for the application.

```json
{"code": "es", "name": "Spanish"}
```

```json
{"code": "zh-TW", "name": "Chinese (traditional)"}
```

Similar to how version toggling works, changing the language via the language toggle would change which top-level language folder is loaded (or English). It changes the language setting for the entire Docs app.

## Locales vs languages

In qiskit.org, we had a concept of locales: the combination of language and region, e.g. `es_UN` for Spanish universal. The region part is useful to do things like show currencies and times/dates differently. 

But in practice, we only had one locale per language, _except for_ Chinese having both simplified and traditional.

Given the nature of the Qiskit documentation, I propose that we simplify and only use langauge codes like `/es` and `/fr`, without locales for every language but Chinese. It seems unlikely that we'll have the bandwidth to differentiate by locale. We didn't have the bandwidth before. It also doesn't seem super critical.

Chinese would be `zh-CN` (simplified) and `zh-TW` (traditional), though.

We could always add locales in the future to the other languages. We could set up redirects from `/es/` to `/es-UN/`, for example.

#### FYI: how to integrate with Crowdin

Crowdin exports the folders with the locale as the prefix, e.g. `es-es/`. I couldn't change this behavior via their `language mapping` mechanism, even though [the docs](https://support.crowdin.com/file-management/#file-export) suggest it should have worked. For all but Chinese, we'll post-process the folder after downloading translations to remove the locale portion from the folder.

### `_toc.json`

This file controls the names of things in the left sidebar, and what URLs they take you to.

We should not change the URLs. But it makes sense to translate the page titles.

```json
  "children": [
    {
      "title": "Introducción",
      "url": "/start"
    },
```

## Won't translate API docs

We took this decision for qiskit.org and the translations team has continued to plan for that.

So, the URL scheme for API docs from https://github.com/Qiskit/docs/issues/8 is orthogonal to the URL scheme for historical API docs.

Still, we should account for the possibility of changing our mind. If so, the URL scheme could be:

```
/es/api/qiskit/utils
/es/api/qiskit/0.44/utils
```

## Internal links handled by the docs app

With internal links, it's important that we take you to the correct language for the sibling file.

There are two ways of doing internal links:

```
/start/my_file
../start/my_file
```

The first style starting with `/` would always refer to the English version of the file; you'd need to use `/es/start/my_file` to get the Spanish version. Or we'd need to have the docs app interpret the URL differently.

I originally proposed banning the first style and always using relative links, but we decided in https://github.com/Qiskit/documentation/issues/532 to instead have the docs app correctly set up internal links.

Note that links to `/api` should _always_ point to English since there are no translated API docs.

## Anchor links

Normally, we link to headers for anchors with internal links, i.e. `#my-header` section of a URL. That works because the docs app automatically assigns an HTML ID to headers, like `My Header` becoming `my-header`.

But when the headers are translated, `My Header` would now become `Mi Cabecera`, so `#mi-cabecera`. It would be very finicky if we expected translators to change all of these URL anchors for each language.

Instead, I think we do want something like https://github.com/Qiskit/documentation/issues/185 so that we can always use the same anchor regardless of the language. We'd ban using anchors from headers (except API docs).

## How to keep files in sync

We'll use the [Crowdin GitHub Action](https://github.com/crowdin/github-action) to handle a) uploading changes to the source docs, and b) downloading updated translations.

I propose using the GitHub action rather than Crowdin's GitHub integration in the app itself because it allows us more precise control over the behavior. The Crowdin Integration will open up a PR every time there is a new translation, for example, which is noisy. Instead, by using the GitHub action, we can batch changes to e.g. run once every week. 

See https://github.com/Qiskit/documentation/pull/541 for how this implemented, including the different schedules we did for uploading English sources vs. downloading translations weekly.

## Translations live in this repository

It's useful for the translations to live in Qiskit/documentation because it simplifies the setup. For example, it makes it easier for us to synchronize these open source docs with the closed source infrastructure that deploys this all to ibm.com. We also don't need to duplicate config and tooling like our link checker.

The major concern with translations living here would be if it's too noisy because of lots of PRs to update the translations. That is where batching is important (see "How to keep files in sync"). Rather than a PR for every translation, we'll only pull in translations e.g. once a week.

**Comment by SooluThomas** [comment]
Thank you so much, Eric for writing this up. This is AMAZING!!! ✨ 

But, here are my thoughts --

> URL/file names will stay the same

I agree

> But in practice, we only had one locale per language.
> 
> Given the nature of the Qiskit documentation, I propose that we simplify and only use langauge codes like /sp and /fr, without locales. It seems unlikely that we'll have the bandwidth to differentiate by locale. We didn't have the bandwidth before. It also doesn't seem super critical.

Yes, it's true that we have only one locale per language except for  Simplified Chinese and Traditional Chinese. Spanish and Portuguese also had translations in 2 different locals which we later merged it and called Spanish, United and Portuguese, United. We also combined the teams for Bengali too. So, in cases like Chinese, when we are not able to combine the locales, We might want to keep the locales. But having a redirect option is a good option. 

> But English does need to show up in the language toggle.

Can you please clarify this? I think we do need English in the toggle to toggle back from, let's say, Japanese docs.

> Ban absolute internal links?

We currently change it to `<language>/rest-of-the-link` in Crowdin when we translate

> Anchor links

Good point!

> How to keep files in sync?

This used be an issue with qiskit.org docs where the translations after a release would be outdated or have partially completed translations. I remember @mtreinish suggesting long time back to have a docs freeze or so, a week prior to the actual release so that (volunteers/professional) translators would have enough time to get the updated docs translated. So, this would be my very first suggestion.

If we are not able to have a docs freeze before actual release, then we might end up with having outdated or partially translated docs.

**Comment by Eric-Arellano** [comment]
Closing this as completed, after discussing the design with @SooluThomas and @axelhzf. Axel thinks we'll likely want to use `_language.json`, but that can be finalized later. The overall architecture is approved and it's implemented in https://github.com/Qiskit/documentation/pull/541.

Refer to the epic https://github.com/Qiskit/documentation/issues/476 for follow up changes to get translations to production.
