### ISSUE TITLE
Add warning when not on current version of API docs

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/documentation#702]
Our SEO was bad for qiskit.org, so old versions of qiskit.org API pages are often the top results. Those then get redirected to ibm.com and users don't realize they're on the old version of the docs unless they open up the version selector

<img width="276" alt="Screenshot 2024-01-24 at 12 18 21 PM" src="https://github.com/Qiskit/documentation/assets/14852634/a7491c9e-bc99-4556-b51c-e13a45f0ffc6">

We've heard a lot of user complaints about the docs being out-of-date, when really they're only looking at the old version. So we should make it more obvious to users by adding a warning. This is only for API pages.

Example:

<img width="953" alt="Screenshot 2024-01-24 at 12 19 30 PM" src="https://github.com/Qiskit/documentation/assets/14852634/64de5482-9850-473b-85a4-791fa13112fb">

**Comment by beckykd** [comment]
Text suggestion:  "This document is for an unsupported version of Qiskit. To view the current documentation, choose the version marked (latest) from the dropdown at the top of the page. "

Maybe @abbycross can think of a way to shorten it, but I do think it's important to tell them HOW to view the current version.

**Comment by abbycross** [comment]
> Text suggestion: "This page refers to an unsupported version of Qiskit. To view the current documentation, choose the version marked (latest) from the version menu. "

Just a couple small changes, and changing "top of the page" in case the dropdown ends up not being at the top of the page for mobile users 🤷

**Comment by gracelindsell** [comment]
Designs are completed for the banner on old API's and can be found [here](https://www.figma.com/file/sNXucK1uMaZ8XXyLTZrdrs/OneDocs?type=design&node-id=4302%3A8562&mode=design&t=gqDwyWc6QiaANYmt-1).

**Comment by Eric-Arellano** [comment]
@gracelindsell @Vanguardbots @javabster, do we want this dev warning to show up for Qiskit 0.46 when 1.0 is released? What about Qiskit 1.0 when Qiskit 2.0 is released? That is, should we have the notion of "stable" docs versions that aren't "latest" but also don't have a dev warning saying there are newer docs available?

My opinion: this nuance is not necessary. Even when Qiskit 0.46 is released, we do still want to encourage people to switch to Qiskit 1.0. We want them to realize they are not on the latest.

**Comment by gracelindsell** [comment]
@Eric-Arellano I agree with your opinion. The goal is to have people realize they are not on the latest version and thus to update that language upon release

**Comment by Eric-Arellano** [comment]
Added! Thanks @kaelynj and @gracelindsell 



![Image](https://github.com/Qiskit/documentation/assets/14852634/d9bc87e0-4a0b-486e-befc-e595ce42fcb2)
