### ISSUE TITLE
Debug why translated Japanese files fail to render

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/documentation#705]
Found by `npm run check-pages-render -- --translations` on Jan 24:

```
translations/ja/build/bit-ordering.mdx
translations/ja/build/introduction-to-qasm.mdx
translations/ja/build/specify-observables-pauli.mdx
translations/ja/build/unitary-synthesis.mdx
translations/ja/run/circuit-execution.mdx
translations/ja/run/configure-runtime-compilation.mdx
translations/ja/run/instances.mdx
translations/ja/run/processor-types.mdx
translations/ja/run/reserve-system-time.mdx
translations/ja/run/retired-systems.mdx
translations/ja/run/system-information.mdx
translations/ja/start/install.mdx
translations/ja/transpile/defaults-and-configuration-options.mdx
translations/ja/api/migration-guides/qiskit-algorithms-module.mdx
translations/ja/api/migration-guides/qiskit-quantum-instance.mdx
```

To check that they render, run `./start` locally then go to e.g. `localhost:3000/ja/build/bit-ordering`.

**Comment by SooluThomas** [comment]
@ilyaspiridonov ([ilyaspiridonov](https://github.com/ilyaspiridonov)) sent the following message over slack

> Hi all,
> upon looking at those errors with our dev team, here are the issues we have identified:
> 1. The JA folder seems to contain English files that we did not translate. I don’t believe they are supposed to be there. Here’s an example https://github.com/Qiskit/documentation/blob/main/translations/ja/api/migration-guides/qiskit-algorithms-module.mdx
> 2. Those English files contain certain issues that were likely introduced after copying (do you have some sort of processor?). Example from the above file:
> ```**[Legacy]\:**```
> while in the En source this string looks like this
> ```**[Legacy] Using QuantumInstance:**```
> 3. The files we have translated seem to have common issues introduced by Crowdin, which is escaping that makes the the formula parser go crazy:
> ```\\```
> instead of:
> ```\```
> 4. Another issue presumably introduced by crowdin is the extra Tab characters before the closing tags like here:
> ```
> <Admonition type="tip" title="Recommendations">
> 
> - Learn how to generate OpenQASM code in the [Explore gates and circuits with the Quantum Composer](https://learning.quantum.ibm.com/tutorial/explore-gates-and-circuits-with-the-quantum-composer) tutorial.
> - Review the [OpenQASM 3 feature table](qasm-feature-table).
> - Read the [OpenQASM 3 Qiskit API](/api/qiskit/qasm3) reference.
> - Read the [OpenQASM 2 Qiskit API](/api/qiskit/qasm2) reference.
> - Visit the [OpenQASM Live Specification](https://openqasm.com/).
> 	</Admonition>
> ```
> Perhaps you also downloaded the untranslated files from Crowdin (English)? Which may explain why there are English files in the JA folder, and why they are also broken.
>
> We’ve fixed those issues in the files we translated, here’s the package: [fixed-translations.zip](https://github.com/Qiskit/documentation/files/14145968/fixed-translations.zip)
>
> You may want to remove the other English files from the JA directory and talk to Crowdin about fixging those issues (escaping and closing html tags being not on the same level as the open tags (extra tabulation)
