### ISSUE TITLE
Some functions and exceptions don't show up in the right sidebar

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/documentation#714]
Thanks to https://github.com/Qiskit/documentation/pull/713 and https://github.com/Qiskit/documentation/pull/683, we now add headers at level 3, whereas before we didn't add headers. This is a big UX improvement because in most cases, the headers show up in the right side bar; it also allows users to get an anchor link to the code object.

However, `h3` is not always the right choice; it depends on the heading level of the surrounding context. For example:

* /api/qiskit/circuit#circuiterror should be h4
* All exceptions in /api/qiskit/exceptions should be h2

Some of the functions in `api/qiskit/utils` should be h2, whereas some should remain h3.

This issues causes certain code objects to not show up in the right sidebar.

## Example: `utils` module

<img width="224" alt="Screenshot 2024-01-26 at 10 24 09 AM" src="https://github.com/Qiskit/documentation/assets/14852634/7ef82e31-1cf5-4a60-89b2-6bc50cf435f6">

an h2:

<img width="427" alt="Screenshot 2024-01-26 at 10 24 28 AM" src="https://github.com/Qiskit/documentation/assets/14852634/38b5a563-83b0-4cb3-83df-5cbcfce99ce3">

an h3:

<img width="663" alt="Screenshot 2024-01-26 at 10 24 58 AM" src="https://github.com/Qiskit/documentation/assets/14852634/3f818523-8ca3-414a-aeac-5f9c085f930d">

## Alternative: change right side bar behavior

Visual design wise, is it okay for some functions/exceptions to be h2? 

The alternative would be to change the right sidebar so that `h3` shows up even if there isn't a parent `h2`. That way we're consistent with how functions look.

## Alternative: change the content itself to always have h2 headers

For example, in utils, add a section like `## General utility functions`

**Comment by javabster** [comment]
After discussion with design we think this is the best option moving forward:
<img width="371" alt="Screenshot 2024-01-26 at 12 46 59" src="https://github.com/Qiskit/documentation/assets/23662430/f88733f7-2f13-4eb9-9b7c-da2dab45c803">

**Comment by Eric-Arellano** [comment]
Fixed by Eric Harvey in closed source. Thanks!
