### ISSUE TITLE
Where should the citation information live?

### ISSUE THREAD

**Issue by abbycross** [Qiskit/documentation#716]
@SMLPfaendler noted that some client onboarding material uses an out-of-date link for how to cite systems/software in research. The citing information now lives in the [FAQs section of the support page](https://docs.quantum.ibm.com/support#frequently-asked-questions). 

Sieglinde asks if we can set up a redirect from the old link (quantum-computing.com/docs/manage/systems) to the new location.
 
It is not easy to directly link to an item within the FAQ (we can create a custom link but it requires the person who wishes to use the link to look into the code to find that link), so the question is, should the citation info move somewhere more discoverable before re-routing the broken link?

cc: @Eric-Arellano @javabster @beckykd

**Comment by beckykd** [comment]
We're also trying to figure out where to put the contribution guidelines etc.  I wonder if this ought to live nearby wherever we decide to put that stuff.

**Comment by SMLPfaendler** [comment]
On Friday, January 26, 2024, abbycross ***@***.***> wrote:
> @SMLPfaendler noted that some client onboarding material uses an
out-of-date link for how to cite systems/software in research. The citing
information now lives in the FAQs section of the support page.
>
> Sieglinde asks if we can set up a redirect from the old link (
quantum-computing.com/docs/manage/systems) to the new location.
>
> It is not easy to directly link to an item within the FAQ (we can create
a custom link but it requires the person who wishes to use the link to look
into the code to find that link), so the question is, should the citation
info move somewhere more discoverable before re-routing the broken link?
>
> cc: @Eric-Arellano @javabster @beckykd
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID:
***@***.***>
