### ISSUE TITLE
Add notices file

### ISSUE THREAD

**Issue by beckykd** [Qiskit/documentation#727]
We should have a notices file that lists 3rd party trademarks and other information as required. Typically this contains legal information in it, but we should investigate with someone who knows about open source to know if there's anything else we need to include. 

List of companies required to be in the special attribution notice: https://www.ibm.com/legal/copyright-trademark#special

**Comment by abbycross** [comment]
We should add the instructions and the link to the special attribution requirements to our readme also.

**Comment by abbycross** [comment]
Note these instructions for Slack: 

> For usage only within the U.S., use the ® symbol on the most prominent use of the word Slack (Slack®), and say “Slack is a registered trademark and service mark of Slack Technologies, Inc.” at the bottom of the page on which the Slack word mark first appears

**Comment by abbycross** [comment]
Update: It's possible that this required notices file should live in the footer of the UI, alongside Terms, Privacy, Accessibility, etc., which involves a different repo. Conversations are in progress

**Comment by abbycross** [comment]
Update: Jules mocked up a solution to add to this link: https://quantum.ibm.com/terms. Fran is in agreement, and we are waiting on the lawyers to verify we don't need a full re-review of the terms to implement this change. I've been regularly pinging Peter Golcher/Douglas Patterson/James Carroll about it.

**Comment by abbycross** [comment]
We have approval from Legal to move ahead with Jules' mockup. Issue to resolve this is here: https://github.ibm.com/IBM-Q-Software/sw-iqx-web/issues/5296

**Comment by abbycross** [comment]
Closing since it has been handed off to the sw-iqx-web team
