### ISSUE TITLE
Add left colored bars to API docs for distinct code objects like methods

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/documentation#735]
See [Figma](https://www.figma.com/file/sNXucK1uMaZ8XXyLTZrdrs/OneDocs?type=design&node-id=4918%3A32646&mode=design&t=6Kl6eSdC8bNa6BbR-1).

Attributes should be purple

<img width="999" alt="Screenshot 2024-03-22 at 11 59 23" src="https://github.com/Qiskit/documentation/assets/47946624/11d5d7a3-5e59-4d82-aa08-05ff277afa2b">

Methods and functions purple

<img width="641" alt="Screenshot 2024-01-31 at 2 17 03 PM" src="https://github.com/Qiskit/documentation/assets/14852634/d8582770-d36a-4553-bd22-19b4fc49401a">

Decide color for exceptions.

--

To implement this, we'll need to wrap each code object in a `<div>` with an appropriate class name set on it. Then the docs app will need to add styling for those classes. Adding `<div>` to the markdown will be interesting - an alternative approach could be to develop a proper MDX component.

**Comment by frankharkins** [comment]
I vote for the MDX component as it might
- allow for more semantic tags (e.g. parameters/returns/raises should be `h4`)
- open up more interesting design possibilities such as indentation, having certain parts in a lighter font (like the old API docs), etc.
