### ISSUE TITLE
Where to host Qiskit CLA PDF?

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/documentation#796]
We host the Contributor License Agreement as a PDF at https://qiskit.org/license/qiskit-cla.pdf and https://qiskit.org/license/qiskit-corporate-cla.pdf. It's referenced in the Qiskit contributor guide:

https://github.com/Qiskit/qiskit/blob/1dd9a5796683ca5a086d4ccc0b753fdad7601e9a/CONTRIBUTING.md?plain=1#L230

Does this need to be a PDF? If so, where should we host it with `qiskit.org` sunset?

**Comment by mtreinish** [comment]
Yes, people and organizations have signed the corporate CLA.
