### ISSUE TITLE
Some page URLs end in .rst

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/documentation#798]
The following files in `docs/api/qiskit` end in `.rst.md`:

```
qiskit.pulse.library.Constant_class.rst.md
qiskit.pulse.library.Cos_class.rst.md
qiskit.pulse.library.Drag_class.rst.md
qiskit.pulse.library.Gaussian_class.rst.md
qiskit.pulse.library.Sawtooth_class.rst.md
qiskit.pulse.library.Sech_fun.rst.md
qiskit.pulse.library.Sin_class.rst.md
qiskit.pulse.library.Square_fun.rst.md
qiskit.pulse.library.Triangle_class.rst.md
```

The `.rst` ends up in the URL. For example, see https://docs.quantum.ibm.com/api/qiskit/qiskit.pulse.library.Square_fun.rst.

**Comment by Eric-Arellano** [comment]
Yeah, this quirk has caused a lot of problems, including with our redirect rules. We should fix this, but make sure we set up redirects correctly.

**Comment by Eric-Arellano** [comment]
I've opened up https://github.com/Qiskit/qiskit/pull/13107. Assuming that gets merged, we'll need to set up redirects.
