### ISSUE TITLE
Figure out link checker rate limiting in CI

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/documentation#823]
For example, we got rate limited by GitHub on https://github.com/Qiskit/documentation/pull/822.

I'm wondering if we can have some type of persistent cache across PR runs. Don't check links within N days. See internal PR 1082 for how this was done in closed source.

--

~Outside of an externally-managed cache, we should definitely at least have an in-memory cache. Note that we don't store what external links have been checked between `FileBatch`es, so we check the same URL multiple times if e.g. Qiskit 0.44 and 0.45 have the same link.~

~This internal cache won't completely solve the problem: we may still make too many requests to the same host but with different pages, like GitHub source code links. But it helps with certain websites.~

This was implemented by https://github.com/Qiskit/documentation/pull/916. We also now only check links once a week in a cron job, so this issue is less urgent.

**Comment by frankharkins** [comment]
I think you could have an action run a slow, extended check on `main` every month or so, then PRs could use that cache, at least according to this [SO answer](https://stackoverflow.com/a/66632107).

**Comment by Eric-Arellano** [comment]
One technique is to set the auth for GitHub like this:

```
 headers.append('Authorization', `token ${getRequiredEnv('GITHUB_TOKEN')}`);
```

Won't help with other hosts, but GitHub is the most common where this happens.

**Comment by Eric-Arellano** [comment]
This hasn't happened in a long time, in large part thanks to using the GitHub token https://github.com/Qiskit/documentation/pull/1392.
