### ISSUE TITLE
Re-draw images for MDX files with Qiskit 1.0

### ISSUE THREAD

**Issue by abbycross** [Qiskit/documentation#833]
~In most cases, code in the docs has been updated to use `style="iqp"` (note: still need to fix several code blocks that do not have this update!).~ (Not necessary in 1.0)

In order to bring the images in line with IBM Quantum colors etc., we need to regenerate the images in the docs so that the output style matches the updated code. 

This means re-running notebooks for ipynb files, and for .mdx files it means running the code and import the output image file.

**Comment by Eric-Arellano** [comment]
Now that we're using Qiskit 1.0, it's not necessary to set `style="iqp"`. Notebooks should be handled via https://github.com/Qiskit/documentation/pull/795.

But MDX does indeed need regeneration of images.

**Comment by abbycross** [comment]
Thanks for the clarification @Eric-Arellano :)

**Comment by abbycross** [comment]
So the places where i'm still seeing iqp need to be removed? @Eric-Arellano

**Comment by abbycross** [comment]
The colors do change when we add/subtract the iqp, so would be good for consistency!
