### ISSUE TITLE
[ NEW PAGE ] Serialising job results

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#840]
Note: on hold until we figure out where in docs to put this and overall patterns structure

Content to include:
- how to dump job results to json
- maybe something about QPy? or pickling?

**Comment by pedrorrivero** [comment]
We have a lengthy example of when it is interesting to serialize/deserialize jobs [here](https://github.com/IBM-Quantum-Technical-Enablement/quantum-enablement/blob/scaling/docs/notebooks/scaling/scaling.ipynb).

I personally don't like it much though, and would love to find a more seamless (i.e. less involved) way of handling it.
