### ISSUE TITLE
[ NEW PAGE ] DIY Readout Error Mitigation

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#843]
Note: on hold until we figure out where in docs to put this and overall patterns structure

the new primitives won't include automatic readout error mitigation, so it would be good to include a docs page to show users how they can do it themselves

**Comment by kevinsung** [comment]
We won't be able to include a code example until https://github.com/Qiskit/qiskit-aer/issues/2078 is resolved.

**Comment by kevinsung** [comment]
Oh, actually, we could do it using [local testing mode](https://github.com/Qiskit/documentation/pull/1023) once qiskit-ibm-runtime 0.22 is released.

**Comment by kevinsung** [comment]
Closing since this content will be on the learning platform instead.
