### ISSUE TITLE
Guide for the backend primitives

### ISSUE THREAD

**Issue by beckykd** [Qiskit/documentation#846]
### Describe the new content you are requesting.

@ElePT suggested creating a guide for the backend primitives.  This can probably wait until the V2 backend primitives are out. For now, the content has been pulled from https://docs.quantum.ibm.com/verify/simulate-with-qiskit-primitives into https://docs.quantum.ibm.com/run/primitives-get-started

### If this new content request is accepted, do you want to write the content?

no

**Comment by javabster** [comment]
do we have enough content to fill a whole page for this? Or is the small section in the primitives page basically it?

**Comment by beckykd** [comment]
Done
