### ISSUE TITLE
[ NEW PAGE ] Transpilation "Under the Hood"

### ISSUE THREAD

**Issue by kaelynj** [Qiskit/documentation#878]
### Describe the new content you are requesting.

(Title TBD)

To help users write new transpiler plugins I'm of the opinion that more technical information could be exposed on how transformation passes such as the `UnitarySynthesis` pass works under the hood.  This (hopefully) should give plugin authors some context on how the library of transpiler passes function to ensure they aren't doubling up on functionality that's already been created.  (Granted a lot of this info can be found in the API refs, but some that requires more technical background/context do not exist there).

Take the `UnitarySynthesis` pass as an example.  From what I understand it's largely based on the methods described in [arXiV:quant-ph/0406176](https://arxiv.org/pdf/quant-ph/0406176.pdf) which defines a quantum multiplexor formalism and is what `decompose()` uses if a gate or dag has no decomposition rules defined.  But this isn't immediately clear and the paper reference is not in the API docstrings (it's buried in a couple comments that you have to dig through the source code to find).  It'd be helpful to, at the very least, have this reference exposed in the docs, but imo a dedicated page for it in the transpile section is better.

### If this new content request is accepted, do you want to write the content?

I will write a draft of the proposed content

**Comment by javabster** [comment]
closing as superseded by #1046
