### ISSUE TITLE
[ REFACTOR ] OpenQASM 3 and Qiskit

### ISSUE THREAD

**Issue by kaelynj** [Qiskit/documentation#888]
### URL to the relevant documentation

https://docs.quantum.ibm.com/build/interoperate-qiskit-qasm3

### Select all that apply

- [ ] typo
- [ ] code bug
- [X] out-of-date content
- [ ] broken link
- [ ] other

### Describe the fix.

Qiskit 1.0 now has a native OpenQASM 3 parser and users no longer need to import the external `qiskit-qasm3-import` package.  I believe the syntax for using it is the same, but need to double check.

**Comment by abbycross** [comment]
I found [this about OpenQASM 3](https://docs.quantum.ibm.com/api/qiskit/release-notes/1.0#openqasm-features) in the release notes -- @kaelynj can you confirm that all we need do is remove the instructions to install qiskit-qasm3-import in the docs?

**Comment by kaelynj** [comment]
Actually I was wrong about this sorry!  I just checked in a separate virtual environment and the `qiskit-qasm3-import` does need to be installed.

**Comment by abbycross** [comment]
No problem!
