### ISSUE TITLE
Sessions don't work with simulators

### ISSUE THREAD

**Issue by jyu00** [Qiskit/documentation#894]
### URL to the relevant documentation

https://docs.quantum.ibm.com/run/run-jobs-in-session

### Select all that apply

- [ ] typo
- [ ] code bug
- [ ] out-of-date content
- [ ] broken link
- [ ] other

### Describe the fix.

The [session documentation](https://docs.quantum.ibm.com/run/sessions) explicitly calls out that sessions don't work with simulators. Yet the [code examples](https://docs.quantum.ibm.com/run/run-jobs-in-session) still use simulators for sessions. I believe the intent was to show the `Session` code syntax, and simulator was chosen for fast execution. But since we are retiring cloud simulators anyway, it makes sense to update the code to use a real backend instead.

**Comment by beckykd** [comment]
This was fixed with the release of the V2 primitives.
