### ISSUE TITLE
Update URLs and set redirects for "build" links to "map" pattern step

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#909]
The build section is being renamed to "Map problem to circuits", the url should be updated accordingly and redirects set up.

Question: how verbose should we make the url? I'm open to either of the following options:
- /map-problem-to-circuits/page-name
- /map/page-name
- some other option?

**Comment by Eric-Arellano** [comment]
Replaced by https://github.com/Qiskit/documentation/issues/1297
