### ISSUE TITLE
Move "Verify" section into "optimize for hardware section"

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#911]
As part of the refactoring of  of docs to use qiskit patterns, the "verify" section should be folded into the "optimize for hardware" section and redirects set up.

The following pages should be moved into the "optimize for hardware" section under a new subheading:

- Verify circuits through simulation
  - verify [Introduction](https://docs.quantum-computing.ibm.com/verify) (NEEDS REFACTOR)
  - [Exact Simulation with Qiskit Primitives](https://docs.quantum-computing.ibm.com/verify/simulate-with-qiskit-primitives)
  - [Exact and Noisy Simulation with Qiskit Aer Primitives](https://docs.quantum-computing.ibm.com/verify/simulate-with-qiskit-aer)
  - [Building Noise Models](https://docs.quantum-computing.ibm.com/verify/building_noise_models) 
  - [Efficient Simulation of stabilizer circuits with Qiskit Aer primitives](https://docs.quantum-computing.ibm.com/verify/stabilizer-circuit-simulation)
  - [IBM Quantum simulators](https://docs.quantum-computing.ibm.com/verify/cloud-based-simulators)
  - [using the cloud based simulators](https://docs.quantum-computing.ibm.com/verify/noisy-simulators)

**Comment by Eric-Arellano** [comment]
This will now go into a "Guides" section. It's tracked by closed source.
