### ISSUE TITLE
Set up cron job to test notebooks that submit jobs

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/documentation#917]
Action item from https://github.com/Qiskit/documentation/issues/133.

We want to test that the notebooks that submit jobs to actual hardware work correctly. We don't run them in normal CI because they are so slow and cost resources.

https://github.com/Qiskit/documentation/blob/8158062c29fc0157d61a3bfc99e61cc658b0eb6a/scripts/nb-tester/test-notebook.py#L35-L37

We still shouldn't them in PRs, but it would be good to test them in a cron job, at least every month and possibly every 2-3 weeks. The `nb-tester` script already supports that:

https://github.com/Qiskit/documentation/blob/8158062c29fc0157d61a3bfc99e61cc658b0eb6a/scripts/nb-tester/test-notebook.py#L232-L240

We also already have the Qiskit Runtime account credentials set up in CI. So this ticket is only setting up the GitHub workflow to test all notebooks that have jobs every 2-4 weeks. Bonus points if we create an issue on failures (relates to https://github.com/Qiskit/documentation/issues/547).

I am a little concerned if we'll exceed GitHub Actions' timeout. We should investigate that when working on this.

**Comment by frankharkins** [comment]
> I am a little concerned if we'll exceed GitHub Actions' timeout.

This will be fine with our current notebooks, but likely to be a problem if we convert some of the `docs/run` files to notebooks (which I would recommend eventually). The max execution time is [6 hours](https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#usage-limits) and queuing can often take a few hours per job. Another solution is to have an action create an issue asking a human to re-run the script locally.
