### ISSUE TITLE
Add a way to dynamically render the version of Qiskit, Runtime, and Aer to notebooks

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/documentation#922]
Split out of https://github.com/Qiskit/documentation/issues/133.

We want to render something like:

```
qiskit: 1.0.1
qiskit-ibm-runtime: 0.20.0
qiskit-aer: 13.3.0
```

It should use the values from the virtual environment used to run the notebook, so the values should be auto-generated and come from e.g. `qiskit.__version__` or whatever the import is. That means this will need to be a code block rather than markdown block. Open question if we can make the formatting look nicer, though.

We discussed it being nice to not show Aer if Aer is not used in the file. We should see if we can automate that by seeing if Aer has already been imported earlier. Otherwise, we discussed if code authors manually mark it, but that is error-prone.

I imagine we'll need to copy-and-paste the same code snippet, rather than DRYing it with a helper function. That's because the notebooks need to run on their own and not depend on other notebooks. In the past, Qiskit itself had a version table to solve this problem; I think that's been removed?

**Comment by woodsp-ibm** [comment]
>  Qiskit itself had a version table to solve this problem; I think that's been removed?

As we wanted these values in the notebooks/tutorials run for the apps, so users can see what versions and when it was run, I made copy of the code and updated that which was in Qiskit in each of the app repos. Maybe that works for you too? I put it in with the tutorials so unlike Qiskit its not shipped with the apps just used with the notebooks when they are run. I subset some of the other information just to python version, os and date. Qiskit had some more fields but I did not think them all that useful.

E.g for ML its here https://github.com/qiskit-community/qiskit-machine-learning/blob/main/docs/tutorials/tutorial_magics.py (similar location in other repos too) And you can see the usage in any of the tutorials there.

And the usage is pretty much as before - a cell with the following - maybe just version_table is all you need as I had updated the copyright to no longer say this is part of Qiskit, as it did when that was in Qiskit. This is how it looks etc - the formatting seemed ok to me.

![image](https://github.com/Qiskit/documentation/assets/40241007/eb12d1d6-dc07-434c-97a0-1412bcfc69bb)

**Comment by frankharkins** [comment]
If we need more control, another option is to append a markdown cell in [`test-notebook.py`](https://github.com/Qiskit/documentation/blob/main/scripts/nb-tester/test-notebook.py#L162) which would let you format it however you need (e.g. in an admonition tag).
