### ISSUE TITLE
Hello World documentation has several typos

### ISSUE THREAD

**Issue by melechlapson** [Qiskit/documentation#926]
### URL to the relevant documentation

https://docs.quantum.ibm.com/start/hello-world

### Select all that apply

- [X] typo
- [ ] code bug
- [ ] out-of-date content
- [ ] broken link
- [ ] other

### Describe the fix.

Here are some issues I found on this doc:
1. In the second code block we do Pauli operators on the 2 bit circuit we created. Based on the discussion here https://qiskit.slack.com/archives/C7SS31917/p1708073215109889, it seems this should be changed to SparsePauliOp since the Pauli class does not have an `apply_layout` method (used in the next code block) but SparsePauliOp class does.
2. In the third code block we call `generate_preset_pass_manager` with a `backend` parameter when none is initialized until the next cell.
3. This is more of suggestion than a typo but in the 4th cell the code initializes a `QiskitRuntimeService` instance without any parameters. This will fail if the user hasn't setup their runtime service with their account's API token. Perhaps there should be a note or comment there referencing https://docs.quantum.ibm.com/start/setup-channel#set-up-to-use-ibm-quantum-platform

**Comment by beckykd** [comment]
I'm working on getting this working with the V2 primitives.

**Comment by frankharkins** [comment]
We should also work out how this passed the automated tests and try to prevent that in the future.

**Comment by Eric-Arellano** [comment]
@frankharkins don't we skip hello world because it submits jobs? This is why we created https://github.com/Qiskit/documentation/issues/917
