### ISSUE TITLE
Handle inline classes in API docs redesign

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/documentation#947]
https://github.com/Qiskit/documentation/issues/521 came up with a great design for API docs when we have dedicated function and class pages, where the page solely exists to document the class or the function. There, everything on the page is in support of that class / function. For example, all methods and attributes describe the same class.

However, we sometimes have _inline_ classes in our API docs (https://github.com/Qiskit/documentation/issues/199), meaning that the class definition is only one part of the rest of the page. When that's the case, we need to somehow distinguish what is the class itself. It's tricky that we also still want to distinguish what the underlying methods and attributes belonging to that class are.

For example, maybe we have a left colored bar that extends across the entire class. Then we have smaller bars for each method and attribute next to it, so certain parts of the doc have two colored bars.

[PDF of current (lack of) styling](https://github.com/Qiskit/documentation/files/14496329/inline-classes-mdx.pdf)

[PDF of Sphinx styling](https://github.com/Qiskit/documentation/files/14465730/inline-classes_sphinx.pdf)

**Comment by gracelindsell** [comment]
Designs have been finalized and can be found [here](https://www.figma.com/file/sNXucK1uMaZ8XXyLTZrdrs/IBM-Quantum-Documentation?type=design&node-id=4918%3A32646&mode=design&t=vSSxNBU0qL7pbjJp-1)
