### ISSUE TITLE
Failed - Instruction not in basis gates: instruction: ecr, qubits: [0, 1], params: []

### ISSUE THREAD

**Issue by tralala87** [Qiskit/documentation#950]
### URL to the relevant documentation

When running my circuit on ibm_brisbane I get:
Failed - Instruction not in basis gates: instruction: ecr, qubits: [0, 1], params: []
Despite ibm_brisbane supporting ecr gate.

### Select all that apply

- [ ] typo
- [ ] code bug
- [ ] out-of-date content
- [ ] broken link
- [ ] other

### Describe the fix.

When running my circuit on ibm_brisbane I get:
Failed - Instruction not in basis gates: instruction: ecr, qubits: [0, 1], params: []
Despite ibm_brisbane supporting ecr gate.

**Comment by abbycross** [comment]
Hi @tralala87 -- looks like you've also opened an issue [here](https://github.com/Qiskit/qiskit-ibm-runtime/issues/1462) as well. I'll close this issue since the documentation for ibm_brisbane's basis gates don't need updating.
