### ISSUE TITLE
DAGCircuit.compose API Reference omitting `wrap` parameter.

### ISSUE THREAD

**Issue by potatoboiler** [Qiskit/documentation#972]
### URL to the relevant documentation

[DAGCircuit.compose](https://docs.quantum.ibm.com/api/qiskit/qiskit.dagcircuit.DAGCircuit#compose)

### Select all that apply

- [ ] typo
- [ ] code bug
- [X] out-of-date content
- [ ] broken link
- [ ] other

### Describe the fix.

Copy the source code's documentation in
```
wrap (bool): If True, wraps the other circuit into a gate (or instruction, depending on
                whether it contains only unitary instructions) before composing it onto self.

**Comment by Eric-Arellano** [comment]
Hey @potatoboiler, can you please link to the source code you're referring to? I'm not seeing it in the 0.46, 1.0, and `main` branches if you search for "wrap" on that page: https://github.com/Qiskit/qiskit/blob/stable/1.0/qiskit/dagcircuit/dagcircuit.py

**Comment by potatoboiler** [comment]
Sorry! I was accidentally looking at the source for QuantumCircuit. 
I mistakenly was working with QuantumCircuit when I was really trying to use DAGCircuit.
