### ISSUE TITLE
Runtime 0.21.0 doesn't generate all release notes versions

### ISSUE THREAD

**Issue by arnaucasau** [Qiskit/documentation#978]
Qiskit-ibm-runtime stopped including release notes for 0.16+ versions when building the documentation, starting on the `stable/0.21` branch. @Eric-Arellano and I have been investigating and found that using `reno list`, the release notes of 0.16+ are grouped together under the 0.15 version, and running the `reno -q semver-next` command, reno thinks the next version is also 0.15.

This happened on `main` at 4632a0644391b42b7b7ee333a7cdc5f718773dc4 and on `stable/0.21`, but not on `stable/0.20`, which behaved properly. The regression first appeared at 18ce57f3596b3483ed4be44be5553ed937f71352.

We are able to build the 0.16+ release notes if we skip the 0.15.0 tag. As a workaround, we had to split the release notes into two sections at https://github.com/Qiskit/qiskit-ibm-runtime/pull/1479:
```
..
.. release-notes:: Release Notes
  :earliest-version: 0.16.0

.. release-notes:: HACK FOR RENO ISSUE
  :earliest-version: 0.1.0rc1
```

The API generation script removes this new title to display the release notes as we expect: https://github.com/Qiskit/documentation/pull/980. The title is necessary to avoid having different heading levels for <0.16 versions.

We need to investigate more closely how to fix it or switch away from Reno. See https://github.com/Qiskit/documentation/issues/979

**Comment by Eric-Arellano** [comment]
We couldn't get Reno working, so we switched to Towncrier in https://github.com/Qiskit/qiskit-ibm-runtime/pull/1501.
